### ISSUE TITLE
Openfire meeting watermark images does not show up

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#103]
No left watermark is shown :
![screenshot77](https://user-images.githubusercontent.com/29485972/100379538-5d23b600-3015-11eb-82f9-247f7d9c55a0.png)

After checking this concern only left watermark

**Comment by deleolajide** [comment]
left watermark name has changed and It looks like right watermark is no more supported in jitsi meet. I will disable it for now.
