### ISSUE TITLE
Enhancement: Cam don't switch offline if Video is disabled

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#104]
In conferences via OFMeet (old and new version), the cam device stay online (controll-light on) while video broadcast is disabled. This is a little bit spooky, like a HAL9000 still watching you.

Recently I was using a more "native" Jitsi plattform (Freifunk München e.V, http://meet.ffmuc.net). Here, the cam goes offline as long as video is disabled.

In my eyes, this is much better from the point of "user experience" and it's a bit curious that something in OFMeet disturbs this.

In the other way round, here the application pop-ups a warning message about muted audio broadcast if there's some sound coming in from the mic. That's also spooky, but to my "user experience" after many month with A/V-conferences, a very helpful hint for the participants. I also don't notice this hints on OFMeet.

**Comment by deleolajide** [comment]
> In conferences via OFMeet (old and new version), the cam device stay online (controll-light on) while video broadcast is disabled

Unfortunately this is a side effect for client-side recording. The video recorder has a copy of the stream which remains open. When video recording is not enabled, it will behave as expected.

>I also don't notice this hints on OFMeet.
enableNoisyMicDetection is now enabled.

**Comment by gjaekel** [comment]
This points to OFMeets additional "full screen" video recorder feature or the build-in "multi-stream" recorder?

**Comment by deleolajide** [comment]
Both I guess
