### ISSUE TITLE
Add support for configuring the new video quality settings

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#105]
See https://github.com/jitsi/lib-jitsi-meet/commit/f74cd0abe9c696a9c3ca7dbb9ca170e6e84d6756

**Comment by gjaekel** [comment]
I just was preparing to fill-in an issue about low video quality using JVB2. Will this solve this issue?

**Comment by deleolajide** [comment]
I also added to admin web page and used meet.jit,si values as default

![image](https://user-images.githubusercontent.com/110731/100521747-545dec00-319d-11eb-8eee-7d4d7d06ec5d.png)

**Comment by gjaekel** [comment]
I already noticed it by studying your changes to the source before installing.

To configure it in **bit per second** is a bit awkward to users in my eyes. :)
