### ISSUE TITLE
Member a room gets host permissions

### ISSUE THREAD

**Issue by dieghostz** [igniterealtime/openfire-pade-plugin#106]
I have configured different persistent room in openfire,  I assigned moderator and multiples members, but if a member enters the room earlier than a host, the member gets privileges

Room Settings 
![image](https://user-images.githubusercontent.com/74977972/100466726-23ec5400-30b0-11eb-815c-e0e4b41dd6a6.png)

![image](https://user-images.githubusercontent.com/74977972/100466933-76c60b80-30b0-11eb-8969-d1ddc2b6023c.png)

this is already implemented in plugin?

![image](https://user-images.githubusercontent.com/74977972/100467084-b42a9900-30b0-11eb-8587-1a9fc83b089f.png)

Thanks for support.

**Comment by gjaekel** [comment]
The default behavior of the "focus" pseudo-user (the technical user that manage the rooms) is to assign the moderator role to the first joining participant. I think currently it's simply not implemented to lookup if there's a predefined host.

**Comment by deleolajide** [comment]
> this is already implemented in plugin?

No. That is achieved by an xmpp server that uses an additional domain for anonymous/guest users. Openfire uses a single domain for anonymous and registered users. Jitsi standalone uses Prosody which supports multiple domains per server.

You might be better off using the [lobby feature](https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v0.9.13-snapshot). It does not work with members only persistent rooms yet.
![image](https://user-images.githubusercontent.com/110731/100473240-ccf97580-30d5-11eb-9d04-79e28d0730ae.png)

**Comment by droobah** [comment]
Would it be possible to add the following setting to this plugin?  I have added the setting using a custom plugin I wrote to specifically set this value to disable the automatic promotion to owner.

System.setProperty("org.jitsi.jicofo.DISABLE_AUTO_OWNER", "true");

**Comment by gjaekel** [comment]
> Would it be possible to add the following setting to this plugin? 

Yes. But @deleolajide has to decide if this is the right way.
