### ISSUE TITLE
Poor Video Performances with Firefox & ofmeet 1.1.2

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#107]
Hello,

I have a poor video résolution when using ofmeet with Firefox compared to pure Jitsi server.
Bad video quality on https://www.free-solutions.org (ofmeet Jitsi )
Good quality on https://meet.free-solutions.ch (Jitsi)
Upload stream is poor when using ofmeet compare to pure jitsi. No clue if it is a config or version issue
Probably a jitsi config setting as both instances run as dockers on same server

**Comment by gjaekel** [comment]
Dear Claude,
thank you for your report! Dele is already working about, compare to #105. Please give the latest release V1.1.2 (https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v1.1.2) a try.
Guido

**Comment by ClaudeStabile** [comment]
> Dear Claude,
> thank you for your report! I observed this, too and Dele is already working about, compare to #105. Please give the latest release V1.1.2 (https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v1.1.2) a try.
> Guido

Guido,

Sorry for duplicate, you can cancel this one same problem as per #105
@deleolajide
