### ISSUE TITLE
Video Quality is alway low (LD)

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#110]
Using OFMeet V1.1 (currently ofmeet.jar v1_1_2.20201127-150016), the video qualtity is lower than before. In the non-tiled view, the mark at top-right always shows (LD) but not (HD) or others as before.

Changing the quality settings via the main burger menu have no infect, except that in the leftmost position video is switched off completely as expected.

**Comment by droobah** [comment]
I would like to confirm this same issue is occurring in my environment running 1.1.2.

**Comment by gjaekel** [comment]
"Bad video quality in comparison to the state before" (using JVB1) was also the main feedback of a field test I had invited all our institution members: I pleased them to give it a short try on our approval stage after their regular meetings.

**Comment by ClaudeStabile** [comment]
Same problem especially with screensharing. This was not observed in previous releases (JVB1)

**Comment by gjaekel** [comment]
Disabling "Simulcast" seems to provide better "user experience". But I don't know if this is reasonable from the technical point of view. I leave "Adaptive Simulcast" still enabled, but don't know if this is a independent setting or a sub-option of the first.

**Comment by ClaudeStabile** [comment]
@gjaekel 

Guido,

I have disable simultcast on all our openfire servers with ofmeet. It gives correct performances results, similar as usual performances for screensharing. So i would recommend to disable Simullcast options.
Just untick & restart Jitsi videobridge plugin to fix it

Test case 
Connect with 3 user to a room. Perform a screenshare from one user, check resulting quality on another participant.
Check before and after untick Simulcast, do not forget to restart.

![screenshot110](https://user-images.githubusercontent.com/29485972/101161529-3a0a8f00-3631-11eb-9b60-6fc62309a2a8.png)
KO : simulcast enable
![screenshot105](https://user-images.githubusercontent.com/29485972/101161949-f1070a80-3631-11eb-8a1e-8b373b9f369c.png)
OKI : Simulcast Disabled
![screenshot106](https://user-images.githubusercontent.com/29485972/101162010-08de8e80-3632-11eb-869b-04fc76e6ff39.png)

This fix/change works with OF 4.5.x & 4.6.x within docker or baremetal install on Ubuntu & CentOS

You can try out at https://www.free-solutions.org

Thanks to all persons that contribute to help fixing this issue :)

**Comment by gjaekel** [comment]
Thank you for the screen shots, this reflect my observations very well - especially the term "KO" :)

I disabled "Simulcast" at our approval stage last night and today, I got first positive feedbacks from the field test users. Now, I'm hunting for #119.

**Comment by deleolajide** [comment]
See https://community.jitsi.org/t/disable-simulcast-based-on-of-users/77104

**Comment by deleolajide** [comment]
I have made most the video config settings available in ofmeet and tried all combinations, but video is low quality. I suspect that this a bug upstream in Jitsi code or I am still missing something. For now, switch off sumulcast if video quality is more important to you than bandwidth

![image](https://user-images.githubusercontent.com/110731/101293061-2d419300-380b-11eb-9cdc-d91b47e71c13.png)

**Comment by gjaekel** [comment]
Thank you for your restless work!
