### ISSUE TITLE
Feature Request: Vertical scrollbar in Contacts Manager

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#111]
After participating some larger meetings at the company, the Contact Manager become unusable because the panel becomes bigger than the screen and the action buttons off-screen.

![Contacts_Manager 20201130](https://user-images.githubusercontent.com/19855721/100640373-9ff7cd80-3336-11eb-899e-1fd843d5d378.png)

**Comment by gjaekel** [comment]
If I add
```
.tingle-modal-box {
    height: 80%;
    overflow-y: scroll;
}
```
via `custom_ofmeet.css`, a vertical scrollbar appear and the dialog becomes usable.

![image](https://user-images.githubusercontent.com/19855721/101525161-33f71400-398b-11eb-988f-f9f99c734575.png)

Is this the right way or should this done programmatically?

**Comment by deleolajide** [comment]
> Is this the right way or should this done programmatically?

perfect 👍

**Comment by gjaekel** [comment]
Should this added here at [tingle.css#L75](https://github.com/igniterealtime/openfire-pade-plugin/blob/075a427c69852cdb5529b49987f9442f00f647c9/web/src/main/webapp/tingle.css#L75) ?
