### ISSUE TITLE
jvb user not working with LDAP

### ISSUE THREAD

**Issue by ChicagoJay** [igniterealtime/openfire-pade-plugin#112]
I installed the new 1.1.2 plugins and now the Meets start, but crash almost immediately.

I've been working with @gjaekel, and he thinks there may be a problem with the jvb user, since OF is read-only, because I am using Active Directory LDAP.

These messages repeat over and over, in the logs:
```2020.11.30 11:43:37 INFO [Thread-14]: org.jivesoftware.openfire.plugin.ofmeet.JvbPluginWrapper - WARNING: [23] [hostname=ofmeet.d83.org id=shard] MucClient.setPresenceExtensions#420: Cannot set presence extension: not connected.
2020.11.30 11:43:39 INFO [Thread-14]: org.jivesoftware.openfire.plugin.ofmeet.JvbPluginWrapper - INFO: [14] [hostname=ofmeet.d83.org id=shard] MucClient$1.connected#259: Connected.
2020.11.30 11:43:39 INFO [Thread-14]: org.jivesoftware.openfire.plugin.ofmeet.JvbPluginWrapper - INFO: [14] [hostname=ofmeet.d83.org id=shard] MucClient.lambda$getConnectAndLoginCallable$7#594: Logging in.
2020.11.30 11:43:39 INFO [Thread-14]: org.jivesoftware.openfire.plugin.ofmeet.JvbPluginWrapper - WARNING: [14] [hostname=ofmeet.d83.org id=shard] MucClient.lambda$getConnectAndLoginCallable$7#608: Failed to login. Disconnecting to trigger a re-connect.
2020.11.30 11:43:39 INFO [Thread-14]: org.jivesoftware.openfire.plugin.ofmeet.JvbPluginWrapper - INFO: [14] [hostname=ofmeet.d83.org id=shard] MucClient$1.connectionClosed#271: Closed.
```

The focus user is in sessions, but the jvb user is not.

@gjaekel has gotten around it by creating a secondary auth with a local db.  I think he and I can get that working here as well, but we felt you should know about the issue.

**Comment by gjaekel** [comment]
Actually, I may not affected by this because I already had set up a 2nd auth provide before (for other reasons)

**Comment by gjaekel** [comment]
To chain-in the `Hybrid{Auth,User}Provider`-class, one have to 
* link its 1st destination to the `LdapAuthProvider`-class
* link its 2nd destination to the `Default{Auth,User}Provider`-class (that will use the database)
* use it as the new value for the `provider.{auth,user}`-class

|Tag |Value |Default |
|------|--------|-----------|
|hybridAuthProvider.primaryProvider.className|org.jivesoftware.openfire.ldap.LdapAuthProvider|org.jivesoftware.openfire.auth.DefaultAuthProvider|
|hybridUserProvider.primaryProvider.className|org.jivesoftware.openfire.ldap.LdapUserProvider||
|hybridAuthProvider.secondaryProvider.className|org.jivesoftware.openfire.auth.DefaultAuthProvider||
|hybridUserProvider.secondaryProvider.className|org.jivesoftware.openfire.user.DefaultUserProvider||
|provider.auth.className|org.jivesoftware.openfire.auth.HybridAuthProvider|org.jivesoftware.openfire.auth.DefaultAuthProvider|
|provider.user.className|org.jivesoftware.openfire.user.HybridUserProvider|org.jivesoftware.openfire.user.DefaultUserProvider|

**Comment by deleolajide** [comment]
![image](https://user-images.githubusercontent.com/110731/100667114-fc1c1b00-3351-11eb-8260-03529f063a68.png)

**Comment by gjaekel** [comment]
In contrast to the focus user, I had no luck by providing a jvb user at LDAP.

**Comment by deleolajide** [comment]
I have pasted the notes on how to add a hybrid provider into a [wiki page](https://github.com/igniterealtime/openfire-pade-plugin/wiki/To-chain-in-the-%60hybrid%7BAuth,User%7DProvider%60-class)

**Comment by deleolajide** [comment]
> In contrast to the focus user, I had no luck by providing a jvb user at LDAP.

![image](https://user-images.githubusercontent.com/110731/100667614-9f6d3000-3352-11eb-9b57-025c00a97f3d.png)

I don't have ldap to test this, but if focus user works, the jvb should as well. With jvb, there is the option to use a different name unlike focus that is hardcoded in Jitsi code.

**Comment by gjaekel** [comment]
While the user `jvb`was in the WinAD, for me it works again at once after changing the JVM user name to `jvb2`. Therefore, I request to delete the user `jvb` in the WinAD and switched back. This was not working first until I delete the `jvb` user via the GUI. It's a bit strange because I don't understand the core quick yet.

**Comment by ChicagoJay** [comment]
I copied the focus user to a new AD user, called jvb.  I set the
    password in AD, then I saved it in the screen Guido posted.  No
    joy.  The meet crashes as soon as the second person tries to enter. 
    JVB never shows up in the Client Sessions list.
    
    When I followed Guido's instructions on using the hybrid database,
    ofMeet was able to create it's own JVB account, and the meetings
    were able to be sustained.  There were other problems, but I'll wait
    for this to be resolved before I open another issue.
    --
Jay Duff, CCE, ACMT, ACiT
Network Specialist
Mannheim School District 83
Franklin Park, IL

**Comment by deleolajide** [comment]
>but I'll wait  for this to be resolved before I open another issue.

Sorry, but there is nothing to resolve of fix for this issue. The plugin cannot created users in LDAP or any read-only user provider for Openfire. Creating users for jvb and focus and configuring them (name/password) has to be done manually by the system administrator.

**Comment by ChicagoJay** [comment]
I created a jvb user in Active Directory.  It's not working.

**Comment by gjaekel** [comment]
... but -- I' sorry -- this will not work.

**Comment by deleolajide** [comment]
> I created a jvb user in Active Directory. It's not working.

I open to suggestions. What is the plugin supposed do? It works perfectly ok with openfire users

**Comment by gjaekel** [comment]
As written: I don't have an idea what's going on in deep concerning **this* jvb user. There's no usable hints in the standard logging. And in the other hand, there's was and is no problem with the focus user (or others).

**Comment by iamnacho** [comment]
Not to pile on, but to confirm:  I have a server that uses a non-AD LDAP (generic LDAP server).  I've done the same steps - create a "jvb" user account in LDAP + password and have put that information in OpenFire - I even tried setting org.jitsi.videobridge.ofmeet.jvb.user.password in System Properties,   but no luck.
I never see the jvb user with a logged in status (and the meetings crash right away when the 2nd user joins).  My LDAP-enabled focus user account DOES login though,  just not the jvb user

**Comment by gjaekel** [comment]
@deleolajide It's a bit complicated to **me** to add an delete it to the WinAD because I'm **not** the admin for this facility. But @ChicagoJay and @iamnacho probably are.
May they configure some Log4-Logger to DEBUG or TRACE to get an idea what's going on?

**Comment by deleolajide** [comment]
> I never see the jvb user with a logged in status (and the meetings crash right away when the 2nd user joins).

If you don't see the jvb online, there is no point trying to start a conference. It is guaranteed  not to work. For every change you make to fix the issue, you have to refresh/restart the ofmeet plugin because the JVB session will be running with the old jvb credentials.

Enable openfire debug and look at the log files and confirm your username/password are correct

xmpp-client {
configs {
shard {
hostname= "desktop-545pc5b"
domain = "desktop-545pc5b"
username = "jvb"
password = "AvszgRa11CEsIx3lNbj7mRakQ8S10N3dkSiSexS4"
muc_jids = "ofmeet@conference.desktop-545pc5b"
muc_nickname = "jvb"
disable_certificate_verification = true
}
}
}
}

**Comment by gjaekel** [comment]
> confirm your username/password are correct
... that's a part of the generated file `.../plugins/ofmeet/classes/jvb/application.conf`

**Comment by ChicagoJay** [comment]
Thanks, @gjaekel I found it:

apis {
        xmpp-client {
               configs {
                # Connect to the first XMPP server
                shard {
                    hostname= "ofmeet.d83.org"
                    domain = "d83.org"
                    username = "jvb"
                    password = "*correct password from AD*"
                    muc_jids = "ofmeet@conference.d83.org"
                    muc_nickname = "jvb"
                    disable_certificate_verification = true
                }
               }

Looks good, @deleolajide - how can I help?  Also, can we please get the issue opened back up?

Thanks!

**Comment by ChicagoJay** [comment]
I got jvb to show up!  I noticed that it wasn't in the LDAP list, and I figured out why: I have a filter on LDAP, that only lists users with email addresses.  I forgot to give the jvb service account an email address!  When I gave it one, the jvb account showed up in the sessions list!

Will be testing soon!

**Comment by ChicagoJay** [comment]
![image](https://user-images.githubusercontent.com/13546758/100762685-e6424080-33b9-11eb-8a82-2029ed99146d.png)

No joy.  Even with the sessions listed above, the meet crashes as soon as the second user joins.

**Comment by ChicagoJay** [comment]
I'm over my head, but the focus user is able to use the LDAP
    credentials.  Shouldn't the jvb user be able to as well?
    --
Jay Duff, CCE, ACMT, ACiT
Network Specialist
Mannheim School District 83
Franklin Park, IL
    On 11/30/2020 3:55 PM, Dele Olajide
      wrote:
    
    
      
      
        I created a jvb user in Active Directory. It's not working.
      
      I open to suggestions. What is the plugin supposed do? It works
        perfectly ok with openfire users
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/igniterealtime/openfire-pade-plugin/issues/112#issuecomment-736079607",
"url": "https://github.com/igniterealtime/openfire-pade-plugin/issues/112#issuecomment-736079607",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by droobah** [comment]
I'm having the same issues with LDAP.  I do not even see it attempting to authenticate against my LDAP servers.

**Comment by iamnacho** [comment]
Please forgive my ignorance & lack of thorough examination of my logs.  The reason my jvb user was not logging in to LDAP is because the process was crashing/not starting properly due to https://github.com/igniterealtime/openfire-pade-plugin/issues/114

**Comment by droobah** [comment]
Okay I believe this is due to the Smack client in Jicoco blacklisting PLAIN authentication by default, which is the only one allowed by LDAP providers.  Checking to see if there's a way to pass a configuration that allows PLAIN again.

**Comment by droobah** [comment]
Actually, not PLAIN. But GSSAPI was making it angry.

Here's a strange/annoying workaround (I'm hoping the jvb user doesn't have to login very often).

If you disable GSSAPI SASL temporarily, JVB will login.  Then you can reenable it and it will stay logged in.

**Comment by billroland** [comment]
Yeah, count me in as well, we use Active Directory and the JVB user never logs in.  The credentials are right and the focus user logs in with no problem.

**Comment by gjaekel** [comment]
@billroland As documented above, you may setup the hybrid authentication provider mechanism. Even the "embedded" SQL database should be good enough to stem the job. And if you have the admin account there (from initial setup?) , you may be able to log in even if your LDAP provider is faulty.

But be aware that in case of a typo during the setup of this, you may kick you out completely; take some snapshot before!

**Comment by billroland** [comment]
I enabled the hybrid authentication provider mechanism as described above and it does not work for me.  I believe this is because I'm running into what droobah reported above, I'm using GSSAPI in my setup and I am guessing Smack is trying that and dying.

**Comment by gjaekel** [comment]
But with a working secondary provider, the JVB account may be authenticated from that. Did you check that it's working by creating any addition account, maybe a 2nd temporary admin account?

**Comment by billroland** [comment]
Yes, I created a secondary jvb user account in the local Openfire DB (not Active Directory).  It shows up in the user list but never the session list.  I changed Pade to use this JVB username but nothing ever happens in the Openfire logs that I see.

**Comment by gjaekel** [comment]
If you please provide a clean log of the OpenFire startup (roll it before start), we'll may take a look on.
