### ISSUE TITLE
Breakout feature is inconsistent 

### ISSUE THREAD

**Issue by ayushbhat** [igniterealtime/openfire-pade-plugin#117]
The Breakout icon most of the time doesn't appear on the screen, sometimes it does after refreshing like 20 times.

**Comment by gjaekel** [comment]
Are you sure with this observation? It will not appear at once together with the other icons but a few seconds later for technical reasons. And (at the moment) one have to own the moderator role.

**Comment by ayushbhat** [comment]
Yes, sometimes (if the user refreshes the page) user loses the moderator role which makes the Breakout icon disappear.
Later when the user is granted the moderator role again, the icon doesn't come back.

**Comment by gjaekel** [comment]
Right, that's an "also observed by me, but not filed" issue or TODO: At the moment, the "decisions" are made only once at join but not on the "upgrade" event.

**Comment by ayushbhat** [comment]
Can't we put this "decision" in a setInternal with timer of 10 secs?

**Comment by ayushbhat** [comment]
and I just noticed even at the joining the user who is creating the meeting room is not moderator by default

**Comment by gjaekel** [comment]
I can't imagine this because the focus user allway elects the first participant if you don't had disconfigured it.

> Can't we put this "decision" in a setInternal with timer of 10 secs?

I think you're welcome by @deleolajide to work it out and send a pull request.

**Comment by ayushbhat** [comment]
I think it has something to do with moderator rights, sometimes even for new meetings the moderator rights are not given to the creator.
