### ISSUE TITLE
Wrong URL path colibiri-ws

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#119]
I just found recent messages in the log about a "404". IMHO, ther's a wrong URL path (`colibiri-ws` instead of `colibiri`). But where it comes from?
```
20201204-094433.241 INFO  [Jetty-QTP-BOSH-25572] [o.j.o.p.o.OfMeetPlugin] JvbSocketCreator /colibri-ws/default-id/d63a3928ac487eba/265c8a64?pwd=79jf658s586ed3ojkrj64iko3m pwd=79jf658s586ed3ojkrj64iko3m
20201204-094433.241 INFO  [Jetty-QTP-BOSH-25572] [ProxyConnection] ProxyConnection ws://localhost:8080/colibri-ws/default-id/d63a3928ac487eba/265c8a64?pwd=79jf658s586ed3ojkrj64iko3m null
20201204-094433.264 ERROR [HttpClient@3df5e091-42767] [ProxyConnection] Error: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 404 Not Found
```

**Comment by gjaekel** [comment]
Might it be possible that this is requested by an (older?) *Jitsi Meet* smartphone app?
Should we implement internal path translation or http redirect?

**Comment by gjaekel** [comment]
This also happens using V1.1.3
```
20201207-092340.498 INFO  [Thread-92] [o.j.o.p.o.JitsiJicofoWrapper] Jicofo INFO: [150] org.jitsi.jicofo.xmpp.FocusComponent.log() Focus request for room: bastelkeller@conference.appr.xmpp.dnb.de
20201207-092340.562 INFO  [Thread-92] [o.j.o.p.o.JitsiJicofoWrapper] Jicofo INFO: [39] org.jitsi.jicofo.ChatRoomRoleAndPresence.log() Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@4559184f member=ChatMember[bastelkeller@conference.appr.xmpp.dnb.de/0de22d27, jid: null]@535267048]
20201207-092340.562 INFO  [Thread-92] [o.j.o.p.o.JitsiJicofoWrapper] Jicofo INFO: [39] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Member bastelkeller@conference.appr.xmpp.dnb.de/0de22d27 joined.
20201207-092340.563 INFO  [Thread-92] [o.j.o.p.o.JitsiJicofoWrapper] Jicofo INFO: [39] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Added participant jid= bastelkeller@conference.appr.xmpp.dnb.de/0de22d27, bridge=ofmeet@conference.appr.xmpp.dnb.de/jvb
20201207-092340.563 INFO  [Thread-92] [o.j.o.p.o.JitsiJicofoWrapper] Jicofo INFO: [39] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Region info, conference=52297 octo_enabled= false: [[region1, null, null, null]]
20201207-092340.563 INFO  [Thread-92] [o.j.o.p.o.JitsiJicofoWrapper] Jicofo INFO: [138] org.jitsi.jicofo.discovery.DiscoveryUtil.log() Doing feature discovery for bastelkeller@conference.appr.xmpp.dnb.de/0de22d27
20201207-092340.563 INFO  [Thread-92] [o.j.o.p.o.JitsiJicofoWrapper] Jicofo INFO: [138] org.jitsi.jicofo.discovery.DiscoveryUtil.log() Successfully discovered features for bastelkeller@conference.appr.xmpp.dnb.de/0de22d27 in 0
20201207-092340.564 INFO  [Thread-92] [o.j.o.p.o.JitsiJicofoWrapper] Jicofo INFO: [138] org.jitsi.jicofo.AbstractChannelAllocator.log() Using ofmeet@conference.appr.xmpp.dnb.de/jvb to allocate channels for: Participant[bastelkeller@conference.appr.xmpp.dnb.de/0de22d27]@1266625632
20201207-092340.574 INFO  [Thread-23] [o.j.o.p.o.JvbPluginWrapper] INFO: [60] [confId=705f11c32386d1c6 epId=0de22d27 local_ufrag=eg8531eou4p58t gid=336535 conf_name=bastelkeller@conference.appr.xmpp.dnb.de ufrag=eg8531eou4p58t] Agent.gatherCandidates#622: Gathering candidates for component stream-0de22d27.RTP.
20201207-092340.578 INFO  [Thread-23] [o.j.o.p.o.JvbPluginWrapper] INFO: [60] [confId=705f11c32386d1c6 epId=0de22d27 gid=336535 conf_name=bastelkeller@conference.appr.xmpp.dnb.de] Endpoint.lambda$setTransportInfo$11#1049: Ignoring empty DtlsFingerprint extension: <transport xmlns='urn:xmpp:jingle:transports:ice-udp:1'><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0' required='false'/></transport>
20201207-092340.583 INFO  [Thread-92] [o.j.o.p.o.JitsiJicofoWrapper] Jicofo INFO: [138] org.jitsi.jicofo.ParticipantChannelAllocator.log() Sending session-initiate to: bastelkeller@conference.appr.xmpp.dnb.de/0de22d27
20201207-092341.206 INFO  [Jetty-QTP-BOSH-170] [o.j.o.p.o.OfMeetPlugin] JvbSocketCreator /colibri-ws/default-id/705f11c32386d1c6/0de22d27?pwd=5tqccvvht0mcvdvrargv31lusb pwd=5tqccvvht0mcvdvrargv31lusb
20201207-092341.206 INFO  [Jetty-QTP-BOSH-170] [ProxyConnection] ProxyConnection ws://localhost:8080/colibri-ws/default-id/705f11c32386d1c6/0de22d27?pwd=5tqccvvht0mcvdvrargv31lusb null
20201207-092341.224 ERROR [HttpClient@3230566a-2049] [ProxyConnection] Error: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 404 Not Found
20201207-092341.629 INFO  [Thread-92] [o.j.o.p.o.JitsiJicofoWrapper] Jicofo INFO: [39] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Got session-accept from: bastelkeller@conference.appr.xmpp.dnb.de/0de22d27
20201207-092341.630 INFO  [Thread-92] [o.j.o.p.o.JitsiJicofoWrapper] Jicofo INFO: [39] org.jitsi.jicofo.JitsiMeetConferenceImpl.log() Received session-accept from bastelkeller@conference.appr.xmpp.dnb.de/0de22d27 with accepted sources:Sources{ audio: [ssrc=1951433429 ] }@1598311287
```

**Comment by gjaekel** [comment]
Maybe the context path declared in https://github.com/igniterealtime/openfire-pade-plugin/blob/2d41e77cbaadf6987f92a2c32c99fb48ef8a86a6/ofmeet/src/java/org/jivesoftware/openfire/plugin/ofmeet/OfMeetPlugin.java#L243 is hidden because the colibri websocket at `colibri-ws` is declarde **before** the main application at `OFMeetConfig().getWebappContextPath()` which is not the defaut (`/ofmeet`) but the ROOT context (`/`) in my setup.

**Comment by deleolajide** [comment]
> Must this sections arranged in the other way around for this reason?

We had this discussion before. A root web context has to be defined  last otherwise it will own all sub folders. That is what Openfire does for the default root web context.

If you are not running Windows, try using a datachannel instead of websockets
```
config.openBridgeChanne = 'datachannel';
```
in custom.config.js

**Comment by gjaekel** [comment]
> We had this discussion before.

I'm sorry that I forgot this.

I set up maven and started to play with `OfMeetPlugin.java`. In addition, I start niffing the traffic at `localhost:8080` It seems to me that there's a problem with the protocol. 

Will add details in a while ...

**Comment by deleolajide** [comment]
I tested on Linux  with datachannel instead of websocket and confirmed active speaker switching works. I am going to make it a configurable setting. That should fix this issue and #120

**Comment by gjaekel** [comment]
Hmm - this is no fix but a workaround, right?

**Comment by deleolajide** [comment]
No. It is a fix until Jitsi deprecate data-channels.Over the weekend I was working with latest Jitsi code which seems to have gone back to using data-channels which were failing on my Windows dev PC

**Comment by gjaekel** [comment]
BTW: I can't get any websocket connection to the JVM on localhost:8080, yet.

**Comment by deleolajide** [comment]
If you want a working solution, forget websocket for now s and switch back to using datachannel connection between Jitsi Meet and JVB. Websoockets on 7743 for XMPP on Openfire is working fire

**Comment by gjaekel** [comment]
Yes, I confirm! (It takes me some time to get familiar with maven, the target directory and which jar to replace)

**Comment by naive924** [comment]
For reference, commenting out does not seem to affect the operation of openfire-pade-plugin.

![image](https://user-images.githubusercontent.com/6185430/101364961-8500fc80-38e6-11eb-8454-b5da49392e66.png)


I'm not sure about the features that colibiri-ws provides
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/web-sockets.md

**Comment by gjaekel** [comment]
@naive924 Sorry, that's the wrong place. One has to replace what is delivered to the **client** when it's request `.../config.js`.

**Comment by deleolajide** [comment]
![image](https://user-images.githubusercontent.com/110731/101366098-755cc600-389c-11eb-8d37-036968253cad.png)

**Comment by naive924** [comment]
Colibiri-ws seems to work on my Linux and Windows local network, but I don't know what I need in the first place.
![image](https://user-images.githubusercontent.com/6185430/101365325-00fb4480-38e7-11eb-94e8-8567fa75e9c1.png)

**Comment by gjaekel** [comment]
> Colibiri-ws seems to work on my Linux and Windows local network

That's remarkable!

**Comment by naive924** [comment]
`Disable` I want to try it.
https://github.com/igniterealtime/openfire-pade-plugin/issues/119#issuecomment-739969950

**Comment by deleolajide** [comment]
> `Disable` I want to try it.
> [#119 (comment)](https://github.com/igniterealtime/openfire-pade-plugin/issues/119#issuecomment-739969950)

use the updated ofmeet.jar plugin file from here - https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v1.1.3

**Comment by naive924** [comment]
Hi @deleolajide 
When I tried  `WebSockets Data Channel >  Disabled`  in my Windows Env, I seemed to get the following issues:

```
 Exception in thread "Smack-Single Threaded Executor 1 (0)" java.lang.UnsatisfiedLinkError: org.jitsi_modified.sctp4j.SctpJ
       at org.jitsi_modified.sctp4j.SctpJni.usrsctp_init(Native Method)
       at org.jitsi_modified.sctp4j.Sctp4j.init(Sctp4j.java:41)
       at org.jitsi.videobridge.sctp.SctpManager.<clinit>(SctpManager.java:61)
       at org.jitsi.videobridge.Endpoint.createSctpConnection(Endpoint.java:833)
       at org.jitsi.videobridge.shim.ContentShim.createSctpConnection(ContentShim.java:167)
```

I thought that this setting (`WebSockets Data Channel >  Disabled` > `openBridgeChannel=datachannel` ) would probably run into the following issues:

- https://github.com/igniterealtime/openfire-pade-plugin/issues/100
- https://github.com/jitsi/jitsi-sctp/pull/3


![image](https://user-images.githubusercontent.com/6185430/101374320-5c323480-38f1-11eb-9d8d-612b7c5276ab.png)

**Comment by gjaekel** [comment]
@naive924 I wonder why you see an estalbished colibri-ws connection but I see a 404 ?!

**Comment by naive924** [comment]
@gjaekel 
> I wonder why you see an estalbished colibri-ws connection but I see a 404 ?!

Hmm. I'm not sure but, with this error, it is possible that the 8080 is not listening.What about the status of netstat? 
`[ProxyConnection] Error: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 404 Not Found`


```
$ netstat -an | grep 8080
tcp6       0      0 127.0.0.1:8080          :::*                    LISTEN
```

**Comment by gjaekel** [comment]
The JVM with the JVB is running an listening, see https://github.com/igniterealtime/openfire-pade-plugin/issues/119#issuecomment-739893014.

```
root@evalfire0 /home/openfireE/openfire/plugins/ofmeet/lib # netstat -tulpen | grep -E '8080|8443'
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      2059       277459529  36757/java          
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN      2059       277478544  36757/java
```

**Comment by naive924** [comment]
>When I tried WebSockets Data Channel > Disabled in my Windows Env, I seemed to get the following issues:

Oh, I confirmed the comment. can't check it on Windows.
![image](https://user-images.githubusercontent.com/6185430/101382061-dca96300-38fa-11eb-9cca-6951f791994d.png)

@gjaekel
Probably, if it is `WebSockets Data Channel > Disabled`, colibri-ws will not be used(I'm going to try it on linux tomorrow).

**Comment by gjaekel** [comment]
Now I installed latest ofmeet.jar V1.1.3@20201207-16500 and tested a conference with three participants with great results:

1.:) Using _Data Channels_ for WebRTC, all works well: The Focus is changing as expectd. And also, there are messages concerning video hight and I would say, with this the video quality now is changing to more than LD on other clients.

2.:) Switching to _WebSockets_, *now* still all work well: There's the second websocket appearing and it's transporting messages via SSL. Sniffing at localhost:8080 now shows encrypted traffic. Only at join, there's still one time the _404_ message:
```
20201207-222124.603 INFO  [Jetty-QTP-BOSH-893] [o.j.o.p.o.OfMeetPlugin] JvbSocketCreator /colibri-ws/default-id/31621ea1a0fce10d/c88aaf16?pwd=2is4v43nhacbmplc8t1j5h6jmp pwd=2is4v43nhacbmplc8t1j5h6jmp
20201207-222124.603 INFO  [Jetty-QTP-BOSH-893] [ProxyConnection] ProxyConnection ws://localhost:8080/colibri-ws/default-id/31621ea1a0fce10d/c88aaf16?pwd=2is4v43nhacbmplc8t1j5h6jmp null
20201207-222124.619 ERROR [HttpClient@35414dc6-1868] [ProxyConnection] Error: Failed to upgrade to websocket: Unexpected HTTP Response Status Code: 404 Not Found
```

**Comment by Jenfong** [comment]
> ![image](https://user-images.githubusercontent.com/110731/101366098-755cc600-389c-11eb-8d37-036968253cad.png)

I  disabled WebSockets Data Channel ,but Pade still use WebSocket  (openfire-pade-plugin 1.7.7 deploy in CentOS 7.8 with nginx ,single node).
refer [Considerations-On-Setting-Up-Pade-Behind-a-Reverse-Proxy](https://github.com/igniterealtime/openfire-pade-plugin/wiki/Considerations-On-Setting-Up-Pade-Behind-a-Reverse-Proxy)
web log:
```shell
lib-jitsi-meet.min.js:17089  WebSocket connection to 'wss://node2:7443/colibri-ws/node2/85aa57dc31a34d65/39ddc58c?pwd=4a24ggqqr8e56a6ilf3rccrdp6' failed: 
```
server log:

```shell
[root@node2 logs]# tail -200f openfire.log | grep colibri-ws
2023.11.29 13:33:49 DEBUG [Thread-14]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJvbWrapper - WARNING: [1] ColibriWebSocketService.<init>#51: Websockets enabled, but no domains specified: URLs=[wss://node2:7443/colibri-ws/node2], Relay URLs=[]
2023.11.29 13:33:49 DEBUG [Thread-14]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJvbWrapper - INFO: [1] ColibriWebSocketService.registerServlet#87: Registering servlet with baseUrls = [ws
```
nginx conf:
public -> nginx -> local
https://demo.resource.com:7666 ->nginx 80 -> https://local:7443
https://demo.resource.com:7667->nginx 7442 ->UDP stream 10000

```shell
   upstream Pade_7443{
          server 127.0.0.1:7443;
       }


    server {
        listen       80 ssl;
        server_name  test.resource.com;
        ssl_certificate      /etc/nginx/conf.d/ssl/private.crt;
        ssl_certificate_key  /etc/nginx/conf.d/ssl/private.key;


        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        proxy_ssl_verify off;
        location /colibri-ws/ {
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_pass https://Pade_7443/colibri-ws/;
        }
        location /ws/ {
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                         proxy_pass https://Pade_7443/ws/;
        }
        #location /pade/ {
        #        proxy_pass https://Pade_7443/pade/;
        #}
        location /http-bind/ {
                proxy_pass https://Pade_7443/http-bind/;
        }
        location /ofmeet/ {

                  proxy_set_header Host $http_host;
                  proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;

                  proxy_connect_timeout 300;
                  # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";

                 proxy_set_header Connection "";
                  chunked_transfer_encoding off;

                proxy_pass https://Pade_7443/ofmeet/;
}
```

moderator join the meeting; then  participant join the meeting ;Error occurred:
1.page auto refresh 
2.can send msg but video broken
