### ISSUE TITLE
Enhancement: Support raw additions to the client config files

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#135]
To ease development and evaluations of new features, I suggest to support raw adds to the JSON object delivered as `.../config.js` and `.../interface_config.js`

**Comment by deleolajide** [comment]
That is what config_custom.js was created for

https://github.com/igniterealtime/openfire-pade-plugin/blob/master/web/src/main/webapp/config_custom.js

**Comment by gjaekel** [comment]
Ups! Is there a interface_config_custom.js, too?

**Comment by gjaekel** [comment]
Maybe I don't describe it propper: The System Properties should take raw JSON to allow to provide former unkown **tags** and it **values** in a quick way.

**Comment by deleolajide** [comment]
I appreciate that, but it can be abused and when Jitsi Meet stops working, **end users** will raise issues here and at github.com/jitsi first before checking their own syntax, We have to find a way to make sure the text entered is sanitized and valid before appending

**Comment by deleolajide** [comment]
I think end-users should cope with missing Jitsi default values. Developers extending ofmeet should modify directly or raise PRs on config_custom.js before it gets adopted in ofmeet-settings.jsp later.

**Comment by gjaekel** [comment]
I'm looking for a way to play with new option without compiling and installing "the whole thing". In a plain Jitsi installation, i just would change a text file.

**Comment by deleolajide** [comment]
> i just would change a text file.

I would not call config.js and interface_config.js text files

**Comment by gjaekel** [comment]
Its a plain ascii file which might be altered using any editor or other framework to generate this files.

I know that this proposal is just for developers and not to be used for end-users.

BTW: Is there really a propper check for JSON-code-injection at the moment? ;)

**Comment by deleolajide** [comment]
This is what I do while testing new config and interface_config options

https://github.com/igniterealtime/openfire-pade-plugin/commit/84a61a9453e6bcbb9fb1b4be2e553cd60a697fb3#diff-8094ca8db11bc2da58be7f0368599965243719d5dc17bddfdb4b1e56a57bbaba

>BTW: Is there really a proper check for JSON-code-injection at the moment? ;)

Yes, use the config object to add your extensions or new/replacement settings before it gets converted to string. That way, the text is sanitized and validated. Any badly formed JSON will throw an exception.

**Comment by gjaekel** [comment]
Editing `custom_config.js` in vito is OK for mangleling with the `config.js`. But the `interface_config.js` is played out by the Servlet and I have to compile and replace a class.

As an alternative, *I* may steal the request at the reverse proxy and deliver a modified version. But this is not sustainable because it's just for me.

**Comment by gjaekel** [comment]
You well know: Most of this Jitsi parameters and options are not documented even at all. I just want to ease the way to decide if it's worth to start "the machine" to work out a new feature.

As an example I read something about a "notice" message that seems to appear on the clients. But where and when? I want to test it. Maybe it's stays in the middle of the screen and is unusable ... ;)

**Comment by deleolajide** [comment]
> Editing `custom_config.js` in vito is OK for mangleling with the `config.js`. But the `interface_config.js` is played out by the Servlet and I have to compile and replace a class.

I modify both config and interface_config objects from custom_config.js. Edit in a text editor and just refresh browser to see the effect. As we are dealing with JavaScript code here, we have to cautious of introducing vulnerabilities. The PR will need more work to make it safer.

**Comment by gjaekel** [comment]
> I modify both config and interface_config objects from custom_config.js
I miss this. I have to study your example more carefully.
