### ISSUE TITLE
Error: offocus 1.1.3 plugin Could not find or load main class

### ISSUE THREAD

**Issue by gptev** [igniterealtime/openfire-pade-plugin#139]
Hi, Deploying offocus.jar 1.1.3 to my openfire on windows server 2012. 
User focus is created, with admin role automatically. But i see no focus user session in Client sessions.
In logs i see next:

2020.12.09 10:41:22 INFO [Thread-28]: org.jivesoftware.openfire.plugin.ofmeet.FocusPlugin - starting jitsiJicofoWrapper

2020.12.09 10:41:22 INFO [Thread-28]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - Initializing Jitsi Focus Component (jicofo)...

2020.12.09 10:41:22 INFO [Thread-28]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - Successfully initialized Jitsi Focus Component (jicofo).
c:\program files\openfire\jre\bin\java.exe -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=C:\Program Files\Openfire\plugins\offocus\classes\jicofo -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=config -Djava.util.logging.config.file=./logging.properties -Djdk.tls.ephemeralDHKeySize=2048 -cp C:\Program Files\Openfire\plugins\offocus\classes\jicofo/jicofo-1.1-SNAPSHOT.jar;C:\Program Files\Openfire\plugins\offocus\classes\jicofo/jicofo-1.1-SNAPSHOT-jar-with-dependencies.jar org.jitsi.jicofo.Main --host=msgsrv.teploenergia.local --port=5275 --domain=teploenergia.local --secret=1uq0QACJ4gks4PF7AuHsJ4dEAxlqeKSrmLCE5a6k --user_domain=teploenergia.local --user_name=focus --user_password=sHJ7WUWL1eVJmpmO5fvXEcUrGrV8GltC2DlIRGFv

2020.12.09 10:41:23 INFO [Thread-34]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - Error: Could not find or load main class Files\Openfire\plugins\offocus\classes\jicofo

2020.12.09 10:41:23 INFO [Thread-35]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - onProcessQuit 1

**Comment by ayushbhat** [comment]
Please make sure, 8080 and 5275 ports are open.

**Comment by gptev** [comment]
Telnet to 5275 succeed
Telnet to 8080 failed. What for this port? Where can i configure it. Firewall on server is disabled.

**Comment by gptev** [comment]
Want to add some tech info:
My openfire server is Openfire 4.6.0 with bundled Java: | 1.8.0_202 Oracle Corporation -- Java HotSpot(TM) 64-Bit Server VM

**Comment by deleolajide** [comment]
> Files\Openfire\plugins\offocus\classes\jicofo

Thanks for reporting. In general avoid instaling Openfire in "Program Files" folder. The problem is space in the file path name. I will add quotes to the file path.

**Comment by gptev** [comment]
BTW it was the SAME error in plugin ofmeet.jar

**Comment by gjaekel** [comment]
@gptev Thank you for your hint, @deleolajide already changed corresponding JVM starters, see [ 81a6da3](https://github.com/igniterealtime/openfire-pade-plugin/commit/81a6da3e9b2311405620a9162088f97ea11a1739):
```
ofmeet/src/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJicofoWrapper.java
ofmeet/src/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJigasiWrapper.java
ofmeet/src/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJvbWrapper.java
```
