### ISSUE TITLE
cyrillic with some variables

### ISSUE THREAD

**Issue by Triskele69** [igniterealtime/openfire-pade-plugin#14]
Variables in User Interface like "Application Name", "Default Remote Display Name", "Default Speaker User Name" and "Local Display Name" don't work with cyrillic. All you got is "????".
Btw russian localization is ok.

**Comment by deleolajide** [comment]
Missing translation. Any volunteers?

**Comment by Triskele69** [comment]
I mean this.
<img width="458" alt="ofmeet" src="https://user-images.githubusercontent.com/64135034/80240415-78d37200-866a-11ea-9875-0af2077bfd99.png">

**Comment by gptev** [comment]
Same here

**Comment by gptev** [comment]
in v1.3.1 cyrillic symbols seems to be ok.
