### ISSUE TITLE
Enhancement: add several options to meeting settings

### ISSUE THREAD

**Issue by gptev** [igniterealtime/openfire-pade-plugin#144]
1. Is there any way to mute sound of every new occupant joins including starter. If isn't add this option
2. Add an option not to hide down panel (with Mute, Leave, Camera buttons...)
3. Add an option to remove "Change personal avatar button"

**Comment by gjaekel** [comment]
Meta: First at all it's better to open separate issues for each question. 

_... continued._

**Comment by gptev** [comment]
1. Added property org.jitsi.videobridge.ofmeet.startwithaudiomuted | true. No effect.
2. Raised both timeouts to 90000000000. No effect.

**Comment by gjaekel** [comment]
1.:) That's not the way. It's an Jitsi property and OFmeet have first to be enhanced to handle and pass it.
2.:) Intenaly, that an _integer_ typed variable. Just don't use a value above 2147483647, which is about 24days :)

**Comment by gptev** [comment]
2. - Solved. Big thanks :1st_place_medal: 
Waiting for solve 1. and 3.

**Comment by deleolajide** [comment]
> * Waiting for solve 1. and 3.

![image](https://user-images.githubusercontent.com/110731/101781233-73d70c00-3aef-11eb-81ff-ad91d95a614a.png)

**Comment by gjaekel** [comment]
@deleolajide I thought this will prevent Audio/Video-transmission at all ?!?

**Comment by deleolajide** [comment]
> @deleolajide I thought this will prevent Audio/Video-transmission at all ?!?

No. It auto-mutes the audio of every joining participant after 0 participants. Apart from webinar mode, there is only one other setting that disables all media (audio/video) transmitted and received. I can't remember the name right now. It is not used in ofmeet.

**Comment by deleolajide** [comment]
There is already a setting for controlling file uploading. I will re-use it for controlling avatar upload as well.

![image](https://user-images.githubusercontent.com/110731/101783758-8c94f100-3af2-11eb-9ce6-88ef5f8a8671.png)

**Comment by gjaekel** [comment]
There are `startWithFooMuted`. And maybe it interferes a little bit with the `startAudioOnly` I introduced recently, because adding 'config.startWithAudioMuted = true;`  in `config_custom.js` don't seems to have an effect.
```
    // Start the conference in audio only mode (no video is being received nor
    // sent).
    // startAudioOnly: false,

    // Every participant after the Nth will start audio muted.
    // startAudioMuted: 10,

    // Start calls with audio muted. Unlike the option above, this one is only
    // applied locally. FIXME: having these 2 options is confusing.
    // startWithAudioMuted: false,

    // Enabling it (with #params) will disable local audio output of remote
    // participants and to enable it back a reload is needed.
    // startSilent: false

[...]

    // Every participant after the Nth will start video muted.
    // startVideoMuted: 10,

    // Start calls with video muted. Unlike the option above, this one is only
    // applied locally. FIXME: having these 2 options is confusing.
    // startWithVideoMuted: false,
```

**Comment by gjaekel** [comment]
Just for the Logbook:
By applying the `startSilent` option on a specific client (using `https://$URL#config.startSilent=true`), it will started with muted Audio *Output*. This is quite useful if a conference presenter will use a second windows to screen-share slides or similar because it will prevent audio loopbacks.

**Comment by gptev** [comment]
@deleolajide
Thanks for answers,
But of course i tried option "Mute audio of new occupants when meeting exceeds" set to 0.
And it was no effect at all. Is it only my issue?

**Comment by gptev** [comment]
Addition: "Mute audio of new occupants when meeting exceeds" set to 0 - audio mutes, when second participant joins. When room is created and only one member - no effect.

**Comment by gjaekel** [comment]
That's exactly what I fear. This "after n" feature is thought to limit bandwitdth for bigger conferences.
Please verify if `https://$URL#config.startWithAudioMuted=true` is working in priniciple. I'll then may start to build it in.

**Comment by deleolajide** [comment]
> When room is created and only one member - no effect.

What is the purpose of muting yourself if there is no one else in the room to hear you. Please note that startAudioMuted is set by first participant and remains effective for the duration of the conference. New participants cannot override it.

startWithAudioMuted is personal preference that can be set and changed by each participant and only affects them.

What business requirement are you trying to achieve?

**Comment by gptev** [comment]
@deleolajide In generally it suits for me if mic mutes after second participant joins

**Comment by gjaekel** [comment]
> startWithAudioMuted is personal preference that can be set and changed by each participant and only affects them.

I think, that's what he want. For me, he don't seem to understand the implcations of `startAudioMuted`. I'll try to send in a pull request about later this day.

**Comment by gptev** [comment]
> 
> 
> That's exactly what I fear. This "after n" feature is thought to limit bandwitdth for bigger conferences.
> Please verify if `https://$URL#config.startWithAudioMuted=true` is working in priniciple. I'll then may start to build it in.

I missed this! Works like charm!!!
