### ISSUE TITLE
Enhancement: add option tile view by default

### ISSUE THREAD

**Issue by gptev** [igniterealtime/openfire-pade-plugin#146]
Is it possible to set "Tile view" by default - without need to press corresponding button

**Comment by deleolajide** [comment]
Not at the moment. The button does not even appear until there are at least 2 people in the conference.

**Comment by gjaekel** [comment]
One may implement a kind of watchdog that will switch one time to tile view when the conference starts "really" with the join of the 2nd participant.

**Comment by gjaekel** [comment]
@gptev By the way: Thank you for your feature requests. May I contact you via email?

**Comment by gptev** [comment]
@gjaekel 
Sure! I would like to communicate!!!

**Comment by gptev** [comment]
Sad that it's still not possible...

**Comment by gjaekel** [comment]
Thank you for the bump! That's a small community and a lot of open issues. Maybe I should try to code out my idea of this watchdog. Or @cool0707 may help out and take a look at `web/src/main/webapp/libs/app.bundle.min.js`.

**Comment by cool0707** [comment]
I think it can be realized by changing `n < 3` to `n < 2` in the following line of `app.bundle.min.js` around line 39604.
`return !Boolean((null === (t = e["features/etherpad"]) || void 0 === t ? void 0 : t.editing) || Object(r.x)(e) || n < 3 || (s = e, Boolean(Object(r.w)(s).find(e => e.isFakeParticipant && e.name === a.a))) || o)`

**Comment by gjaekel** [comment]
In the meaning, that `n` here is the current number of participants and with the current `n < 3 ::= n <= 2`, the lower limit is two participants, but with `n < 2 ::= n <= 1 ::= false`, this will start with the Tile view?

**Comment by cool0707** [comment]
I don't think it needs to be a tiled view for 1 participant, as you commented above, but if you delete `if (n < 2) return !1;` a few lines up and replace `n < 3` with `n < 1` or delete it, it might be a tiled view for 1 participant. (Unconfirmed)

**Comment by gjaekel** [comment]
@gptev Are you able to verify the suggested change by yourself?

**Comment by gjaekel** [comment]
I confirm: Because the case `n < 2` is tested before, you may kick out the term `n < 3` below
```
    function l(e = {}) {
        var t;
        const n = Object(r.s)(e);
        if (n < 2) return !1;     // <<-- return false, if less than 2 participants
        const {
            tileViewEnabled: i
        } = e["features/video-layout"];
        if (void 0 !== i) return i;    // return false, if TildeView is disabled
        const {
            iAmRecorder: o
        } = e["features/base/config"];
        var s;
        // return !Boolean((null === (t = e["features/etherpad"]) || void 0 === t ? void 0 : t.editing) || Object(r.x)(e) || n < 3 || (s = e, Boolean(Object(r.w)(s).find(e => e.isFakeParticipant && e.name === a.a))) || o)  // return false,  if ... and n => 3
        return !Boolean((null === (t = e["features/etherpad"]) || void 0 === t ? void 0 : t.editing) || Object(r.x)(e) || (s = e, Boolean(Object(r.w)(s).find(e => e.isFakeParticipant && e.name === a.a))) || o) // return false, if ...
    }
```

But as others, the feature "always start in Tile View mode, even with less then 3 participants" should probably made be config option at the Admin UI.

**Comment by gptev** [comment]
@gjaekel i can test it, but i need clear instruction ))
And as you said - "should probably made be config option at the Admin UI"

**Comment by gjaekel** [comment]
You need to locate and edit the line commented out (by `//`) in the listing above. It's in the file `.../openfire/plugins/pade/classes/jitsi-meet/libs/app.bundle.min.js`. Make a backup copy of this file and edit it. Beware of this a real huge text file. You may also copy it, commend it out and delete the term `|| n < 3` in the copy.

If you had make a mistake, the Webclient will crash at usage (and is going to reconnect). In this case, just restore the file from your backup.

**Comment by gptev** [comment]
Deleted || n < 3, refreshed browser, no changes with 1 participant.
btw after reload plugin pade - all changes removed. Will test later with more than 1 participant

**Comment by gjaekel** [comment]
> btw after reload plugin pade - all changes removed.

Yea, quite clear :)  If you need to do this quite often (but you should), you may "inject" the edited file into the `.../openfire/pade.jar`. This is the downloaded plugin archive.

A JAR is technical just a ZIP file: Make a backup with (with an extension different to `.jar`to avoid to make OpenFire recognize to load it). Then, with an appropriate tool, browse the `pade.jar` and replace the `app.bundle.min.js` at it's path inside the archive. You may temporary change the extension to `.zip` if needed.

**Comment by gptev** [comment]
Tested with 2 participants, tile view worked!!! Awesome!

**Comment by gjaekel** [comment]
OK, thank you for verifying this. Now it's worth to take the effort to define a transported config parameter to pass this option in, let the server side deliver it as the client configuration and add a section to configure it to the Admin UI.

**Comment by gptev** [comment]
Or make "tile view" option enabled by default ))

**Comment by gjaekel** [comment]
Oh, that's not in the spirit of good Open Source software. We have to offer the freedom of choice and the torture to decide.

**Comment by deleolajide** [comment]
> Or make "tile view" option enabled by default ))

Some people prefer a one-to-one video call to show the other person full screen and self as a small tile somewhere. Tiles becomes useful when there is a group conversation.

**Comment by gptev** [comment]
Several updates ago this instruction to edit app.bundle.min.js not working because of changed code.
And no options mentioned in "Local Feature Configuration Panel" topic implemented (((

**Comment by gjaekel** [comment]
The function currently is located at L32275ff.:
```
    function u(e = {}) {
        var t;
        const n = Object(r.s)(e),
            i = Object(a.i)(e, a.f, !0),
            {
                disableTileView: s
            } = e["features/base/config"];
        if (s || !i) return !1;
        const {
            tileViewEnabled: l
        } = e["features/video-layout"];
        if (void 0 !== l) return l;
        const {
            iAmRecorder: c
        } = e["features/base/config"];
        return !Boolean((null === (t = e["features/etherpad"]) || void 0 === t ? void 0 : t.editing) || Object(r.x)(e) || n < 3 || Object(o.c)(e) || c)
    }
```
There now seems to be a feature parameter `disableTileView`, but this will probably disable Tile View at all and is the opposite of your usecase.

But I guess you may kick out the term `|| n<3` in the last line like before.

**Comment by gptev** [comment]
Works like charm. Thank you ))
