### ISSUE TITLE
LiveStream of rooms to YOUTUBE not working

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#148]
Hello,

I did a try to do some livestream to youtube. It does work on ofmeet Jitsi but works at meet.jit.si
Is there any setting to do to perform Livestreaming with Jitsi ofmeet

These steps works @ jitsi,

With ofmeet 1.1.3 i have this message when i try same steps

![screenshot6](https://user-images.githubusercontent.com/29485972/101796528-49924800-3b09-11eb-98a3-8ab3ae63f8e9.png)

![screenshot7](https://user-images.githubusercontent.com/29485972/101796582-557e0a00-3b09-11eb-8496-bd9fd5e76d8c.png)

**Comment by gjaekel** [comment]
May you share me your stream key via email to investigate?

**Comment by gjaekel** [comment]
Is it enabled by default? Try to append `#config.liveStreamingEnabled=true` to the URL.

**Comment by deleolajide** [comment]
Live streaming requires [Jitsi Jibri](https://github.com/jitsi/jibri) service that converts webrtc media into RTMP required by YouTube

**Comment by ClaudeStabile** [comment]
@deleolajide Thanks, i was quite sure somethin was missing to get an rtmp output.
Is it possible to have Jibri on Openfire ?

**Comment by deleolajide** [comment]
> Is it possible to have Jibri on Openfire ?

No. But you can run i in Docker. See https://hub.docker.com/r/jitsi/jibri
