### ISSUE TITLE
Regression: Remove "stay on page" on leaving a conference

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#149]
On leaving an established conference, the browser ask for confirmation. Unfortunately, this is a regression of #4.

Please remove this to ease re-connect or return to the welcome page.

**Comment by gjaekel** [comment]
This behavior is not observed as long the conference is not established by the join of a 2nd participant.

**Comment by deleolajide** [comment]
If you are referring to this

![image](https://user-images.githubusercontent.com/110731/101798289-d38ae280-3b02-11eb-8979-d1dd3ee5ccb7.png)

It can only be removed if there is no active recording

**Comment by gjaekel** [comment]
There *is* no active recording. Actually, I disabled it from the GUI to follow privacy policies. And to allow the "light" at the cam to switch off if Video is disabled.

**Comment by deleolajide** [comment]
The code is currently not doing that, but I have modified it to only block page closing when an active recording is being saved to file.

**Comment by gjaekel** [comment]
Approved to work!
