### ISSUE TITLE
error with 3 participants or more in a room

### ISSUE THREAD

**Issue by dieghostz** [igniterealtime/openfire-pade-plugin#151]
Hi,
I update to the last version 1.2.0 and when testing a room with 3 or more participants , the room fails.
this did not happen with version 1.1.1, 
in the logs files shows this:

2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - Jicofo 2020-12-11 10:53:20.664 GRAVE: [205] org.jitsi.jicofo.AbstractChannelAllocator.log() ofmeet@conference.sacssbb.cl/jvb - failed to allocate channels, will consider the bridge faulty: XMPP error: <iq to='focus@sacssbb.cl/focus2158651022476726' from='ofmeet@conference.sacssbb.cl/jvb' id='GJKYt-818' type='error'><error type='cancel'><internal-server-error xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas' xml:lang='en'>minPort (-1) and maxPort (-1) should be integers between 1024 and 65535.</text></error></iq>
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - org.jitsi.protocol.xmpp.colibri.exception.ColibriException: XMPP error: <iq to='focus@sacssbb.cl/focus2158651022476726' from='ofmeet@conference.sacssbb.cl/jvb' id='GJKYt-818' type='error'><error type='cancel'><internal-server-error xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas' xml:lang='en'>minPort (-1) and maxPort (-1) should be integers between 1024 and 65535.</text></error></iq>
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - at org.jitsi.impl.protocol.xmpp.colibri.ColibriConferenceImpl.maybeThrowOperationFailed(ColibriConferenceImpl.java:378)
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - at org.jitsi.impl.protocol.xmpp.colibri.ColibriConferenceImpl.createColibriChannels(ColibriConferenceImpl.java:282)
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - at org.jitsi.protocol.xmpp.colibri.ColibriConference.createColibriChannels(ColibriConference.java:112)
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - at org.jitsi.jicofo.ParticipantChannelAllocator.doAllocateChannels(ParticipantChannelAllocator.java:111)
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - at org.jitsi.jicofo.AbstractChannelAllocator.allocateChannels(AbstractChannelAllocator.java:271)
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - at org.jitsi.jicofo.AbstractChannelAllocator.doRun(AbstractChannelAllocator.java:190)
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - at org.jitsi.jicofo.AbstractChannelAllocator.run(AbstractChannelAllocator.java:150)
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
2020.12.11 10:53:20 INFO [Thread-80]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - at java.lang.Thread.run(Thread.java:748)

I see that the jigasi user not connected 

![image](https://user-images.githubusercontent.com/74977972/101912267-49915700-3ba0-11eb-9a3d-8b9dc6f17ba3.png)

![image](https://user-images.githubusercontent.com/74977972/101912301-5615af80-3ba0-11eb-8708-90bbd536b2b1.png)

Thanks for support.

**Comment by gjaekel** [comment]
There is a closed issue dealing with it (#113).

**Comment by deleolajide** [comment]
> GRAVE: [205] org.jitsi.jicofo.AbstractChannelAllocator.log() [ofmeet@conference.sacssbb.cl](mailto:ofmeet@conference.sacssbb.cl)/jvb - failed to allocate channels, will consider the bridge faulty: XMPP error: minPort (-1) and maxPort (-1) should be integers between 1024 and 65535.

make sure this is disabled

![image](https://user-images.githubusercontent.com/110731/101915152-21642100-3bbd-11eb-9443-4da8c26a7493.png)

**Comment by deleolajide** [comment]
> I see that the jigasi user not connected

Jigasi wont show connect until a user is created in openfire, it is enabled and the SIP connection is working
