### ISSUE TITLE
The application name is garbled when it contains multibyte characters.

### ISSUE THREAD

**Issue by cool0707** [igniterealtime/openfire-pade-plugin#152]
I am going to use Openfire Meetings in Japanese.
I am currently using Openfire 4.6.0 and openfire-pade-plugin 1.2.0 on Windows Server 2016.
When I set Japanese characters for Application Name, Default Remote Display Name, Welcome Page Title, etc. in the Openfire Admin Console,  the Japanese characters are displayed as ???? on Openfire Meetings welcome page.

I think you need to do HTML escaping (e.g. Apache Commons StringEscapeUtils.escapeHtml4) before using JiveGlobals.setProperty or convert character encoding after using JiveGlobals.getProperty.

**Comment by gjaekel** [comment]
Hi (Lucifer?),
are you able to figure it out, e.g. by local changes to the code and send in a pull request?

**Comment by gjaekel** [comment]
Also fixes #26 .
