### ISSUE TITLE
Meta-Bug: unknown local path in POM for Pade

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#153]
https://github.com/igniterealtime/openfire-pade-plugin/blob/163c92a411e3a179e152301dc64fd7272c66fe0b/pade/pom.xml#L103

**Comment by deleolajide** [comment]
fixed by merge of ofmeet into pade (issue #154). maven build pulls pade client from https://github.com/igniterealtime/pade/blob/master/docs.zip during build
