### ISSUE TITLE
Start Order of Plugins OFMeet and Pade

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#154]
As told I'm struggling with the startup order of plugins because I'm using the ROOT context for the OFMeet plugin.

I had have a look on the OpenFire Plugin Manager, there's already some arragements to ensure the startup order for certain things: It wil be ensured that the Admin Plugin will loaded first

https://github.com/igniterealtime/Openfire/blob/0d1fd96318c6d68dfa20ba58430f5466d9822c16/xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMonitor.java#L354

                        // Sort the list of directories so that the "admin" plugin is always first in the list, and 'parent'
                        // plugins always precede their children.
                        final Deque<List<Path>> dirs = sortPluginDirs( ds, devPlugins );

https://github.com/igniterealtime/Openfire/blob/0d1fd96318c6d68dfa20ba58430f5466d9822c16/xmppserver/src/main/java/org/jivesoftware/openfire/container/PluginMonitor.java#L507

        /**
         * Returns all plugin directories, in a deque of lists with these characteristics:
         * <ol>
         * <li>Every list is a hierarchy of parent/child plugins (or is a list of one element).</li>
         * <li>Every list is ordered to ensure that all parent plugins have a lower index than their children.</li>
         * <li>The first element of every list will be a plugin that has no 'parent' plugin.</li>
         * <li>the first element of the first list will be the 'admin' plugin.</li>
         * </ol>
         *
         * Plugins within the provided argument that refer to non-existing parent plugins will not be part of the returned
         * collection.
         *
In reference to the [Plugin Development Guide](https://download.igniterealtime.org/openfire/docs/latest/documentation/plugin-dev-guide.html), I add the element `<parentPlugin>pade</parentPlugin>` to `ofmeet/plugin.xml`. In the one hand, this will start Pade before OFMeet. In the other hand, it require that the Pade is installed - if not, one get as expected:

    20201212-123226.512 WARN  [pool-6-thread-1] [o.j.o.c.PluginMonitor] Unable to load plugin 'ofmeet' as its defined parent plugin 'pade' is not installed.

It's also written that the parent's class loader is used - I don't overlook the consequences of this.

I suggest to introduce a similar tag that will influence the start order in a "weak" way: The openrc init framework e.g. provides the keyword `after foo` for a service that must be started after another if the other one is installed. As an imitation, the XML tag may be named `afterPlugin`.

Should I rise an issue at OpenFire?

**Comment by gjaekel** [comment]
> because I'm using the ROOT context for the OFMeet plugin.

Meta: This is because I want to support use of the Smartphone Apps. They expect at least `config.js` to be requestable at the root directory of a domain and I don't know how to configure something like redirections or mapping that I need to run the OFmeet Plugin at some not-ROOT context path like `/ofmeet`.

**Comment by deleolajide** [comment]
I use mobile with pade.chat and I am NOT using root. I use default /ofmeet

**Comment by deleolajide** [comment]
![image](https://user-images.githubusercontent.com/110731/101986426-ad418000-3c85-11eb-9e8d-4ad4af852eaf.png)

**Comment by gjaekel** [comment]
> I use mobile with pade.chat and I am NOT using root. I use default /ofmeet

Quite clear that this will work. But for me it's a *must have* to provide an URL that is a pure hostname.

In March, I had no success with rewriting on my reverse proxy. But I will re-investigate, because now I have set up three stages and may play around with Evaluation without disturbing anybody.

**Comment by gjaekel** [comment]
Got a simple but effective idea: I renamed the plugin JAR to `z_ofmeet.jar`.

**Comment by deleolajide** [comment]
The more I think I about, the more I think I should just merge ofmeet into pade and just create a single plugin

**Comment by deleolajide** [comment]
> Got a simple but effective solution: I renamed the plugin JAR to `z_ofmeet.jar`.

watch out for some admin sceens that search for the plugin by name. confirm the name change does not affect them

**Comment by gjaekel** [comment]
You're right, I observed the log only :(  At the Admin console, an disfunctional `tab plugin.title` appear ... :(

**Comment by gjaekel** [comment]
> In March, I had no success with rewriting on my reverse proxy.

Now, I seems I got the rewriting rules running for using internal the default plugin context `/ofmeet`, but still let the Smartphone App let connect at the domain. Especially it offer `my.site.com/config.js` but the scheme for the HTML client is still  `http://my.site.com/raum/foo` for conference rooms, `http://my.site.com/raum` for the OFMeet welcome page and `http://my.site.com` for our site welcome page.

**Comment by deleolajide** [comment]
I have done it. Both plugins are now merged into a single plugin called pade.  Now you can use root context without startup order issues. Plugin loads the ofmeet module last.

![image](https://user-images.githubusercontent.com/110731/103100189-664e7580-4609-11eb-80fb-5174b541ad2c.png)
