### ISSUE TITLE
About app.bundle.min.js customization

### ISSUE THREAD

**Issue by cool0707** [igniterealtime/openfire-pade-plugin#156]
I would like to modify app.bundle.min.js for some customization.
The repository doesn't seem to contain the (React?) source code before the bundle, is this because it is the same file as Jitsi's?

**Comment by gjaekel** [comment]
I'm curious what you want to change or add. May you tell about?

**Comment by deleolajide** [comment]
> is this because it is the same file as Jitsi's?

No, It is because I modify the minified files directly. My mods can be identified with the // BAO tag

I suggest you clone the Jitsi Meet project, modify the React source and build your own  app.bundle.min.js. If you copy it to the src folder, maven will replace the Jitsi version with yours.
