### ISSUE TITLE
"Enable lobby" does not work correctly.

### ISSUE THREAD

**Issue by cool0707** [igniterealtime/openfire-pade-plugin#159]
Lobby cannot be enabled in the Security Options dialog of the Meeting screen when "Enable Pre-Join Page" is disabled in the admin console.
It can be checked on the display, but it is not actually enabled.
It is also not possible to return the enabled display to disabled.

**Comment by deleolajide** [comment]
Unfortunately, lobby feature needs more work done server-side in Openfire to keep in step with the Prosody version used by Jitsi Meet. It currently does not work properly with Openfire persistent chat room.

**Comment by gjaekel** [comment]
This doubles #66
