### ISSUE TITLE
no video

### ISSUE THREAD

**Issue by telvideo** [igniterealtime/openfire-pade-plugin#161]
hi
how to fix ?
![Screenshot_2020-12-16_17-46-01](https://user-images.githubusercontent.com/75522693/102362406-95416780-3fc9-11eb-8947-786edd414aed.png)
![Screenshot_2020-12-16_18-07-58](https://user-images.githubusercontent.com/75522693/102362452-a68a7400-3fc9-11eb-9107-2327711bdb05.png)

**Comment by gjaekel** [comment]
Get the _Video Bridge_ running, status is "down".

**Comment by telvideo** [comment]
jvb is online

**Comment by telvideo** [comment]
![Screenshot_2020-12-16_18-47-54](https://user-images.githubusercontent.com/75522693/102367638-3da5fa80-3fcf-11eb-9051-3c126e06c95b.png)
![Screenshot_2020-12-16_18-47-08](https://user-images.githubusercontent.com/75522693/102367656-41398180-3fcf-11eb-836f-e45910486782.png)

**Comment by telvideo** [comment]
I changed the WebSockets Data Channel option from Disabled to Enabled. This change solved the video problem.

thanks

**Comment by gjaekel** [comment]
In your first pic, it was offline. Congratulations for solving this; your'e the next one dealing with problems concerning the _WebSockets_ mode for Data Channel. That's why @deleolajide was pleased to make it switchable.

**Comment by telvideo** [comment]
yes

My problem was solved
