### ISSUE TITLE
 Feature Request: Rtmp Live Streaming 

### ISSUE THREAD

**Issue by telvideo** [igniterealtime/openfire-pade-plugin#162]
I want to stream a video conference to my rtmp server instead of streaming to YouTube
Thank you for your help

**Comment by gjaekel** [comment]
An interesting project. Sorry, I'm busy next hours.

**Comment by naive924** [comment]
Hi, Could you tell me.

1. "Record Meeting" has the problem that recording is stopped if the user joins later.
2. "Record Desktop App" is difficult to operate because it is necessary to let the user select the Chrome tab properly.

Can these be solved?

![image](https://user-images.githubusercontent.com/6185430/102451663-49032f80-407c-11eb-9753-926019f48401.png)

**Comment by ClaudeStabile** [comment]
For large audiences it is the best way to deliver vidconf as a stream. Currently it requires an external JIBRI instance. If rtmp streaming could be bundle with the package it will be a very great addon to ofmeet. 
I fully support this very needed powerfull feature

**Comment by deleolajide** [comment]
https://mux.com/blog/the-state-of-going-live-from-a-browser/

The Video over WebSockets option might be a good use case to implement with Openfire/Jetty/ffmpeg

**Comment by JoshWho** [comment]
I would love to see a custom rtmp setting for this rather than the Youtube one. Custom can use Youtube if people still want it but you can also stream to multiple platforms if you have restreaming services and can't do that with just Youtube being the only option.

**Comment by deleolajide** [comment]
Made a first pass at this using https://github.com/chuabingquan/pxy

![image](https://user-images.githubusercontent.com/110731/109730533-88d4b000-7bb1-11eb-9417-16b931f5b3ab.png)

Only works with localhost. I still need to implement a websocket proxy wss <==> ws

**Comment by gjaekel** [comment]
As pxy is implemented in Go, do you plan to distribute prebuild binaries for Linux and Windows within the plugin package?

**Comment by ClaudeStabile** [comment]
@dele rtmp Live streaming : That's really SUPER SUPER COOL !!! many new doors opened Yesss...
I follow that one, i receive some usage cases for rtmp.

++

**Comment by gjaekel** [comment]
I expect that this e.g. offer the possibility to provide a "propper" source to be used with OBS, which seem to be "the" key product to manage (semi-) professional broadcasts of sessions.

**Comment by ClaudeStabile** [comment]
@gjaekel  Of course we will face some tech/quality issues to adress but rtmp is really a very big PLUS on this solution. Thanks to @deleolajide and your contribs + my midleware impl and testing and experimentations, we will quickly have something consistant on that side YESSSS !

**Comment by deleolajide** [comment]
> As pxy is implemented in Go, do you plan to distribute prebuild binaries for Linux and Windows within the plugin package?

The binaries are fetched and extracted from a zip file on demand when streaming is enabled for the first time.

The next step is to port the code in pxy to java and run ffmpeg directly from Pade. It will remove the need for an extra port and using a websocket proxy for TLS. It will also keep the implemementation simpler and more efficient.

**Comment by deleolajide** [comment]
> I expect that this e.g. offer the possibility to provide a "propper" source to be used with OBS, which seem to be "the" key product to manage (semi-) professional broadcasts of sessions.

OBS is the client side of streaming. You use it as a streaimg client to layout and combine multiple audio/video sources into a composite media stream that is published by a streaimg service. It should be possible to use OBS right now to publish a Jitsi Meet conference to any proffesional quality streaming service. It uses binary code on the client to implement virtual media devices (webcams, mics and speakers).

The use case for Pade streaming is to provide a simple publishing solution without installing any binary code on the client and using the power of the browser to create a single media stream that is sent to an ffmpeg process on the server that converts the media from webrtc to rtmp.

**Comment by akbarazimifar** [comment]
> Made a first pass at this using https://github.com/chuabingquan/pxy
> 
> ![image](https://user-images.githubusercontent.com/110731/109730533-88d4b000-7bb1-11eb-9417-16b931f5b3ab.png)
> 
> Only works with localhost. I still need to implement a websocket proxy wss <==> ws

Hello . that's great .
Can you explain how to install?

**Comment by deleolajide** [comment]
>The next step is to port the code in pxy to java and run ffmpeg directly from Pade

It now works directly with ffmpeg. No need for pxy. The video is H264 and copied through and works well. Audio is recoded from opus to mp3 and it is not as good. It needs some more work.

![image](https://user-images.githubusercontent.com/110731/109848005-b79d6580-7c47-11eb-8b4e-e9b9d86bfb24.png)

**Comment by deleolajide** [comment]
place holder for screen-shots used in wiki

![image](https://user-images.githubusercontent.com/110731/109880854-55585b00-7c6f-11eb-95a4-cd0d6b0db83d.png)
