### ISSUE TITLE
Support VP9 codec

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#163]
See https://community.jitsi.org/t/vp9-with-bridge-support-soon-cometh-do-a-happy-dance/87806

**Comment by naive924** [comment]
I tried, but the Codec was still VP8. Is my procedure wrong?

The procedure is as follows:
(https://community.jitsi.org/t/vp9-with-bridge-support-soon-cometh-do-a-happy-dance/87806/4)

1. build jitsi-media-transform
```
git clone https://github.com/JonathanLennox/jitsi-media-transform.git
cd jitsi-media-transform
git checkout vp9-support
mvn install
```

2. build jitsi-videobridge
```
git clone https://github.com/JonathanLennox/jitsi-videobridge.git
cd jitsi-videobridge
git checkout vp9-support
mvn install -P buildFatJar -Dmaven.test.skip=true
```
 * `maven.test.skip=true` to avoid test code errors


3. copy jar
```
cd jitsi-videobridge
cp jvb\target\jitsi-videobridge-2.1-SNAPSHOT.jar  openfire-pade-plugin\ofmeet\classes\jvb\jitsi-videobridge-2.1-SNAPSHOT.jar
cp jvb\target\jitsi-videobridge-2.1-SNAPSHOT.jar  openfire-pade-plugin\ofmeet\classes\jvb\jitsi-videobridge-2.1-SNAPSHOT-jar-with-dependencies.jar
```

4. edit org.jitsi.jicofo.ENABLE_VP9=true
```
openfire-pade-plugin\ofmeet\classes\jicofo\logging.properties
org.jitsi.jicofo.ENABLE_H264=false
org.jitsi.jicofo.ENABLE_VP8=false
org.jitsi.jicofo.ENABLE_VP9=true
```

5. build.cmd & deploy
```
cd openfire-pade-plugin
build.cmd

rmdir /s /q C:\openfire_4_6_0\plugins\ofmeet
C:\openfire_4_6_0\bin\openfire.bat
```

6. Check with Chrome
![image](https://user-images.githubusercontent.com/6185430/103090393-41bbc300-4634-11eb-8867-190e825c2ad5.png)

**Comment by deleolajide** [comment]
> I tried, but the Codec was still VP8. Is my procedure wrong?

I think jitsi-videobridge-2.1-SNAPSHOT-jar-with-dependencies.jar will contain the old jitsi-media-transform. You would have to modify the maven build process (pom.xml) file to point at the new build

**Comment by naive924** [comment]
Thank you! I may have made progress by using systemPath..
pom.xml
```
             <dependency>
-                <groupId>${project.groupId}</groupId>
+                <groupId>jitsi-media-transform</groupId>
                 <artifactId>jitsi-media-transform</artifactId>
                 <version>1.0-SNAPSHOT</version>
+               <scope>system</scope>
+               <systemPath>${basedir}/jitsi-media-transform-1.0-SNAPSHOT.jar</systemPath>
             </dependency>
```
But a new problem is coming out and I'm investigating ...
```
JitsiConfig.<clinit>#68: Initialized legacyConfig: sip communicator props (no description prov
JitsiConfig$Companion.reloadNewConfig#94: Reloading the Typesafe config source (previously rel
Exception in thread "main" java.lang.NoClassDefFoundError: org/jitsi/nlj/stats/DelayStats
       at org.jitsi.videobridge.xmpp.XmppConnection.<clinit>(XmppConnection.kt:224)
       at org.jitsi.videobridge.MainKt.main(Main.kt:79)
Caused by: java.lang.ClassNotFoundException: org.jitsi.nlj.stats.DelayStats
       at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
       at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
       at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
       ... 2 more
```

**Comment by naive924** [comment]
>Thank you! I may have made progress by using systemPath..

Since buildFatJar is generated from m2 cash, pom.xml seems to be OK as it is
Maybe it will be VP9 from the third person connection!
![image](https://user-images.githubusercontent.com/6185430/103113653-13bf9880-469f-11eb-8ebf-46c0e512a7ba.png)

**Comment by gjaekel** [comment]
Dear Saturo,
Great work! For a quick test at my Eval stage, may you provide me the JVB2 JARs to replace (or -- if easier -- the whole ` pade.jar`)?

**Comment by naive924** [comment]
@gjaekel 
I will share ofmeet.jar later.
In the case of a webcam, the resolution is reduced and it is not visible. However, the effect of VP9 is remarkable in screen sharing.
![image](https://user-images.githubusercontent.com/6185430/103135438-ad1c9800-46fb-11eb-9099-f629c67a85f5.png)

**Comment by gjaekel** [comment]
At the first try, I get a picture from one PC, but at a laptop, there's an error about the provided resolutions.

```
2020-12-26T09:02:27.497Z [modules/RTC/RTCUtils.js] <X.<anonymous>>:  Got media constraints:  {"video":{"width":{"ideal":1280,"min":853,"max":1920},"aspectRatio":1.7777777777777777,"height":{"ideal":720,"min":480,"max":1080},"facingMode":"user"},"audio":false}

lib-jitsi-meet.min.js:9825 2020-12-26T08:59:25.481Z [modules/RTC/RTCUtils.js] Failed to get access to local media. [object OverconstrainedError] {"video":{"width":{"ideal":1280,"min":853,"max":1920},"aspectRatio":1.7777777777777777,"height":{"ideal":720,"min":480,"max":1080},"facingMode":"user"},"audio":false}
```

**Comment by gjaekel** [comment]
Setting `org.jitsi.videobridge.ofmeet.constraints.video.width.min` to `320`solve the issue. The value of `853` is suspect to me, should be maybe `800`. Maybe it needs to apply some "down-rounding" at
https://github.com/igniterealtime/openfire-pade-plugin/blob/4f32ff2c8fdf98b319b285298cb9996d70a45395/web/src/main/java/org/jivesoftware/openfire/plugin/ofmeet/ConfigServlet.java#L116-L119

**Comment by gjaekel** [comment]
In fact, the output of  `v4l2-ctl --list-formats-ext` for the laptop webcam show that one of the formats is `800x448` (not x450) or `864*480` (not 800x).
For this reason, defining **480** as min height at the Admin UI isn't a as I did before good choice ....

**Comment by gjaekel** [comment]
I verified and it seems to me that V8 is ("still"?) preferred over V9 if both enabled, i.e. along with V9 enabled, V8 have to be disabled.
```
org.jitsi.jicofo.ENABLE_VP8=false
org.jitsi.jicofo.ENABLE_VP9=true
```
Thus, for OFmeet and the GUI we should introduce a "use V9 instead of V8" toggle option.

**Comment by gjaekel** [comment]
Dear Saturo,
do you know https://github.com/Syonyk/lib-jitsi-meet/pull/2 ? Seems to be a key-ready patch to add a ` preferVP9` to be signaled by the clients and to be processed by JiCoFo.

**Comment by naive924** [comment]
>do you know Syonyk/lib-jitsi-meet#2 ? Seems to be a key-ready patch to add a preferVP9 to be signaled by the clients and to be processed by JiCoFo.

I don't know the details, but it seems that Jonathan_Lennox needed to fix JBV2 in [this discussion](https://community.jitsi.org/t/flagship-vp9-support-notes-and-discussion/33921/9).
Since then, [preferredCodec](https://github.com/jitsi/jitsi-meet/blame/33e4324f6de7b4360182d39669b8095bd0dff43a/config.js#L256
) has also been added, so I'm still watching.

Also, if my verification is correct, there was no problem with the latest iOS. I'm still investigating this point, but I feel that VP9 alone is fine.

**Comment by deleolajide** [comment]
@gjaekel @naive924 Thinking about adding this to 1.3.0. What do you think? Is ready for production?

Do you have the JVB jar files uploaded somewhere for me for me to download?

**Comment by gjaekel** [comment]
I don't think it ready: To my knowledge, a client will prefer VP8 over VP9 and must be forced to use VP9. Because of the force, there will be no fallback to VP8. There is a "prefer VP9 over VP8" patch (see above) that might solve this.

And if the client device is not capable to de-/encode VP9 with hardware support, but support this for VP8, the "user experience" might be point into the wrong direction.

You/we may test Saturo's work at my Evaluation Stage.

**Comment by gjaekel** [comment]
You may add an checkbox option "Experimental: Use VP9 instead of VP8" as FORCE_VP9 and let the config build with
```
org.jitsi.jicofo.ENABLE_VP8=${not FORCE_VP9}
org.jitsi.jicofo.ENABLE_VP9=${FORCE_VP9}
```

**Comment by deleolajide** [comment]
>I don't think it's ready for the community:

Thanks for the feedback and response to my question. I am going with just adding the setting of parameters for those who know what they are doing using stable Jitsi jar files.
```
org.jitsi.jicofo.ENABLE_H264=false
org.jitsi.jicofo.ENABLE_VP8=false
org.jitsi.jicofo.ENABLE_VP9=true
```
![image](https://user-images.githubusercontent.com/110731/103385065-dae55080-4af0-11eb-8945-cf0924102f54.png)

![image](https://user-images.githubusercontent.com/110731/103384957-437ffd80-4af0-11eb-8df6-2f1ac74d878d.png)

**Comment by naive924** [comment]
@deleolajide 
I tried "Force VP9 Cdeoc" in 1.3.0. VP9 is selected correctly.
![image](https://user-images.githubusercontent.com/6185430/103390549-59290d80-4b58-11eb-8318-fb89f3e36924.png)


I'm wondering, according to [jitsi community](https://community.jitsi.org/t/vp9-with-bridge-support-soon-cometh-do-a-happy-dance/87806/4), that JonathanLennox's github needs to replace the jitsi-videobridge jar.
As a result I seemed unnecessary to update JVB2.

* The newly added `Vp9Packet.class` is not included

```
jar -tvf C:\openfire_4_6_0\plugins\pade\classes\jvb\jitsi-videobridge-2.1-SNAPSHOT-jar-with-dependencies.jar  | findstr vp9/Vp9Packet
 none
```

**Comment by deleolajide** [comment]
>As a result I seemed unnecessary to update JVB2.

If all participants are using VP9 compatible browsers, then you don't need to patch JVB2

**Comment by gjaekel** [comment]
Will the patch do a conversion between VP9 and VP8?

**Comment by gjaekel** [comment]
According to https://community.jitsi.org/t/flagship-vp9-support-notes-and-discussion/33921/123, VP9 support of a recent upstream snapshot (build 5142 (jitsi-videobridge stable 2.1-376-g9f12bfe2-1) is comparable good.
