### ISSUE TITLE
Avatar still shows broken in list

### ISSUE THREAD

**Issue by droobah** [igniterealtime/openfire-pade-plugin#168]
Since I can't re-open #115 , I had to create a new one.  I've attached a screenshot of what I see.   What logging do you need for this?  I'm not showing any 404 error from either Firefox or Chrome when the page loads and hitting /ofmeet/images/avatar.png pulls up the avatar properly.

![screenshot_29](https://user-images.githubusercontent.com/34214975/102831854-6274e600-43b2-11eb-808e-fa37701b3e7f.png)

**Comment by gjaekel** [comment]
Do you use LDAP? If yes, may you please deactivate by commenting out using `//`
https://github.com/igniterealtime/openfire-pade-plugin/blob/7078ca06c6f8b1e4d73d96d82e919d758e312284/web/src/main/webapp/custom_ofmeet.js#L576-L579
In you installation, you'll find this file at `.../plugins/ofmeet/classes/jtsi-meet/custom_ofmeet.js`

**Comment by deleolajide** [comment]
> @deleolajide If this helps, there seems to be a problem of returned image type from the vCard.

ofmeet uses whatever is stored as a base64 string in the vCard. You can use Pade, Spark or any xmpp client that supports vCards to check the quality of the image or debug the issue.

![image](https://user-images.githubusercontent.com/110731/102880513-59802500-4443-11eb-8186-7c76f64e0a74.png)

![image](https://user-images.githubusercontent.com/110731/102880537-64d35080-4443-11eb-8676-747f50a16bae.png)

This is an Openfire vCard configuration issue and not ofmeet.

**Comment by gjaekel** [comment]
I added
```
[...]
  <PHOTO>
    <TYPE>image/jpeg</TYPE> 
    <BINVAL>{jpegPhoto}</BINVAL>
  </PHOTO> 
[..]
```
to `ldap.vcard-mapping` to support avatar pictures stored at the WinAD.

I traced it down last minutes: The problem is that the `BINVAL` used at the code is empty leading to a syntactical wrong line image. I'll add a pull request...
