### ISSUE TITLE
Windows NTLM Authentication does not work.

### ISSUE THREAD

**Issue by cool0707** [igniterealtime/openfire-pade-plugin#171]
Even if I enable Windows NTLM Authentication, it does not work properly.
In lib-jitsi-meet.min.js, it seems to access "/sso/password", but when I access it with a browser, it returns a 404 error.

**Comment by deleolajide** [comment]
You also need the pade plugin installed to use NTLM authentication

**Comment by cool0707** [comment]
Pade pluginis already installed.
I found out that it works when the Context Path is set to "/ofmeet", but not when the Context Path is set to "/".
Is there any way to enable NTLM authentication with the Context Path set to "/"?

**Comment by gjaekel** [comment]
I struggled with the same thing. To resolve this poses a challenge: The mechanisms of servlets require that the shortest context path is registered after the longer. But a the moment, there's no support for a defined order at the OpenFire module loader.

In fact, there already **is** support for a submodule relationship, but this will **require** the parent module (as a **must**, but not as a **depend**)

What's the core reason that **you** want to have OFMeet at the root context but not at "/ofmeet" or something like that? I have solved this task at my reverse proxy and I may share a set of rewrite rules (Apache, but you may translate for NGinx by need).

**Comment by deleolajide** [comment]
Looks like we have yet one more reason to merge ofmeet plugin into the pade plugin and create a single unified plugin that controls the loading order of all components (jvb, jicofo, jigasi, freeswitch and pade web services)

**Comment by gjaekel** [comment]
Or we enhance the OFMeet plugin loader to support hints like "after foo" or "before bar" in `plugin.xml` .

**Comment by deleolajide** [comment]
> The benefits of unification are a bit shortened by the fact that you have to implement some "privat subcomponent manager", because IMHO on should be able to disable unneeded components.

That is already in place. The jvb, jicofo and pade webservices will be mandatory. jigasi and freeswitch are optional and have enable/disable properties

**Comment by deleolajide** [comment]
> Or we enhance the OFMeet plugin loader to support hints like "after foo" or "before bar" in `plugin.xml`.

This is a a bit of work to the plugin manager in Openfire core. It has been discussed several times before, but nobody has the appetite to do this task.

**Comment by cool0707** [comment]
I understand that the problem is due to the loading order of the plugins.
Since I am using Openfire only for Pade Meetings (Openfire Meetings?), Root context would have been preferred, but I will consider using a context like "ofmeet".
Thanks.

**Comment by gjaekel** [comment]
Me too, because that's the URL to be used as "server" in the smartphone app _Jitsi Meet_. No reverse proxy in front?

**Comment by cool0707** [comment]
We do not have a reverse proxy because we plan to use it only within the company.

**Comment by deleolajide** [comment]
This should be fixed with version 1.3.0 - https://github.com/igniterealtime/openfire-pade-plugin/issues/154#issuecomment-750927857
