### ISSUE TITLE
Maximum participants limit reached

### ISSUE THREAD

**Issue by naive924** [igniterealtime/openfire-pade-plugin#177]
The [following error](https://community.jitsi.org/t/how-to-limit-no-of-participant-for-meeting/74351
) seems to occur when 30 users participate.

It seems that it can be expanded with "Maximum Room Occupants" of Openfire, but it seems that changing it does not solve it.
Also, the ofmeet setting itself is not saved, and it will return to 30 when Openfire is restarted.

* Openfire can create chat rooms with more than 30 users.
* Env： OS : Windows / Openfire 4.6.0 / openfire-pade-plugin :1.3.0

![image](https://user-images.githubusercontent.com/6185430/103199558-74b0d000-492e-11eb-935f-75b4376dad11.png)
![image](https://user-images.githubusercontent.com/6185430/103199657-a32eab00-492e-11eb-8658-a593f3a520fd.png)

**Comment by gjaekel** [comment]
There's a default for rooms - wait...

**Comment by deleolajide** [comment]
> Also, the ofmeet setting itself is not saved, and it will return to 30 when Openfire is restarted.

The MUC room max participants is an XMPP setting stored in Openfire's DB. It is possible that Jicofo is caching it and you make have to refresh the plugin if you change that value. I also suggest leaving it blank for unlimited participants

**Comment by deleolajide** [comment]
This issue has come up before and back then the problem was that Openfire's admin would not let you modify the value. If I recall correctly, that was fixed and tested OK for more than the default 30 participants. Unfortunately, I can't seem to find the issue.

**Comment by gjaekel** [comment]
For a dynamical created room, IMHO the settings are cloned form the Default Room Settings. One have to pin a room to make individual settings persistent.

**Comment by naive924** [comment]
@deleolajide @gjaekel 
Thank you for your advice.
It was confirmed that the number of participants can be increased by changing the value of dynamical created room.
But restarting Openfire seems to remove the dynamical created room 😿
![image](https://user-images.githubusercontent.com/6185430/103215943-23b5d180-4958-11eb-8493-ebfb531bb0a6.png)

**Comment by gjaekel** [comment]
Have you changed the value at the _Default Room Settings_ as described?

**Comment by naive924** [comment]
This is it. I'll try!
![image](https://user-images.githubusercontent.com/6185430/103216627-dc304500-4959-11eb-8be5-d5087e0460b0.png)

**Comment by gjaekel** [comment]
I'm very sorry! *I* confirm that this isn't working anymore as before!

**Comment by naive924** [comment]
I changed the `Default Room Settings` and it was persistent! Great! !!
![image](https://user-images.githubusercontent.com/6185430/103216757-23b6d100-495a-11eb-8afc-9a124a095f09.png)

**Comment by gjaekel** [comment]
???

**Comment by naive924** [comment]
it seems that the following entry is recorded in `embedded-db/openfire.script` and is persisted.

e.g.)  When `Default Room Settings` is 100
`INSERT INTO OFMUCSERVICEPROP VALUES(1,'room.maxUsers','100')`

**Comment by gjaekel** [comment]
Wow - I (re)got it! **First** set the number in Default Room Settings (e.g. to nothing for unlimited) for _conference_. **Then** change the value for _ofmeet_ and or _ofgasi_
