### ISSUE TITLE
Remove webinar mode

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#178]
Support for webinar mode in ofmeet needs to happen upstream in Jitsi. From current discussions, it looks like it may not happen in favor of a [new product for large conferences](https://community.jitsi.org/t/webinar-solution-for-jitsi/16449/2?u=deleolajide).

The current implementation is broken and difficult to maintain. As I am currently working on a new openfire plugin using the [Galène videoconferencing server](https://galene.org/) which is designed to this user-case, I am removing webinar mode from ofmeet

**Comment by gjaekel** [comment]
What a pity. I was offering this feature - but I don't know if it was really used, yet. 

* May the paricipants use the Jitsi Meet frontends to connect ot a  Galène server/bridge?
* Do you want to make Galène a participant of a Jitsi Conference (like a recorder) and use it for broadcast? 
* Will Galène replace Jitisi even at all?

**Comment by deleolajide** [comment]
> * What is broken, please? From a quick test, it seems to work for me like before.

It is a pain to apply the changes to jitsi-meet every time there is a new release because they change their code every time

>May the paricipants use the Jitsi Meet frontends to connect ot a Galène server/bridge?

I have not got there yet. In theory yes, but I may not need to go there as the Galene web app has the controls for admin, presenter and participant and much easier and flexible to work with. It is static web pages with JavaScript, CSS and HTML. No React or any other annoying web framework.

>Do you want to make Galène a participant of a Jitsi Conference (like a recorder) and use it for broadcast?

No plans to do that right now, but as both JVB and Galene are (selective forwarding units) SFUs, it is possible. Galene however is much simpler as it consumes SDP generated from the web browser. No transformation into Jingle and then Colibri as Jitsi does. Also there is no focus user in the middle. 

I am already working on a generic broadcast plugin using the [video over websockets](https://mux.com/blog/the-state-of-going-live-from-a-browser/) from the client to a server process running ffmpeg and then broadcast to an RTMP, HLS, Dash endpoint or whatever ffmpeg supports.

>Will Galène replace Jitisi even at all?
Probably not. I need a webinar solution that will be easy to maintain. The Galene web client and server does offer me an alternative to fighting with Jitsi Meet

You can try it out from my server - https://pade.chat:5443/galene

For lobby and public rooms use admin/admin as username/password to be admin
For lecture room use teach/teach as username/password to be a presenter
Anything else will make you a participant

Use /help in chat to see what commands are available for your role.

**Comment by gjaekel** [comment]
Just get noticed of https://github.com/GRVYDEV/Project-Lightspeed . This have three components
* a module that gets FTL (from OBS) convert to RTC
* a Web-RTC broadcaster module
* a "module" that generates a static webpage to be used at the client browsers to watch the Web-RTC stream.

Maybe the middle one may be used to provide a webinar broadcaster and the third one as (a starting point for) a user-frontend.

**Comment by gjaekel** [comment]
>It is using the same PION webrtc media stack in Golang as Galene does.

oh! :eyes: 

>I don't need OBS. 

I know.
