### ISSUE TITLE
Feature Request: Allow access to JVB REST-API via private http interface

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#182]
Allow access to the JVB REST-API, e.g. to pull stats for a monitoring system (see https://github.com/jitsi/jitsi-videobridge/blob/master/doc/statistics.md). 

This is done by enabling the `private` interface of the JVB.

Will introduce the properties 
* `ofmeet.videobridge.rest.address` with default `localhost`, if no public IP defined and the local IP elsewhere.
* `ofmeet.videobridge.rest.port` with default `8188`

**Comment by gjaekel** [comment]
I also remove a leftover concerning passing the TLS keystore path to the JVB.

**Comment by gjaekel** [comment]
Should we rename `ofmeet.websockets.plainport`  to `ofmeet.videobridge.plainport` for clarification?
https://github.com/igniterealtime/openfire-pade-plugin/blob/a5b1a64ef0bb379409136e23752e9f59c0860acd/ofmeet/src/main/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJvbWrapper.java#L78

**Comment by deleolajide** [comment]
>Bind to all interfaces if a public_ip is in use, because then there must be some external NAT and it should be save to allow access from the local net

The internal http port (8080) should be treated like a internal database port and should always be LOCALHOST. It does not have any security or authentication, It is a plain port (which poses a risk) and on servers with multiple Openfire tenant instances that are bound to different IPs, it will will create privacy issues. 

You JSP should be making server-side HTTP requests to localhost just as I do with the summary page.

**Comment by deleolajide** [comment]
Exposing the private port also causes JVB dominant speaker to stop working. See https://github.com/igniterealtime/openfire-pade-plugin/pull/164/files

**Comment by gjaekel** [comment]
Thank you for the revision!

> The internal http port (8080) should be treated like a internal database port and should always be LOCALHOST. It does not have any security or authentication, It is a plain port (which poses a risk) and on servers with multiple Openfire tenant instances that are bound to different IPs, it will will create privacy issues.

I agree to you that this may cause a security problem . I will drop this "host" setting; the default behavior without is  to bind to "localhost".

> You JSP should be making server-side HTTP requests to localhost just as I do with the summary page.
Which JSP? I want to "http get" this data by a monitoring system (Zabbix). I may set up a revere proxy with authentification or restiction to the status URL by my own.

> Exposing the private port also causes JVB dominant speaker to stop working.
That's a wrong interpretation, IMHO. The problem was caused by using wrong ports and a problem with the wss to ws proxy. Of corse, I don't want to use `8080`; I suggest to use `8188`

I test this by editing the `application.conf` and made it read-only for the OpenFire user. I don't see the "focus problem", the colibri websocket service is working, but i'll recheck it. At my site, the "public" port `8180` is **not** opened to the internet.

I'll rewrite the pull request and test, again.

**Comment by deleolajide** [comment]
>Which JSP?

First, you write a Plain Old Java Object (POJO) method to perform the REST request. See https://github.com/igniterealtime/openfire-pade-plugin/blob/1bcbae070c9083e5ffbe865b1a57005dd7f8be12/ofmeet/src/main/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJvbWrapper.java#L348

Next, you access the method from your JSP and format your data. See  https://github.com/igniterealtime/openfire-pade-plugin/blob/1bcbae070c9083e5ffbe865b1a57005dd7f8be12/pade/src/web/ofmeet-summary.jsp#L37

**Comment by deleolajide** [comment]
>The problem was caused by using wrong ports and a problem with the wss to ws proxy

The problem with the wss to ws proxy was that it could not connect to the colibri-ws service anymore if the private http port is exposed in the conf file. That is what caused the one-way traffic from client to server and blocked server to client. I spent a few days unraveling this.

![image](https://user-images.githubusercontent.com/110731/103346645-8314fe00-4a8c-11eb-886f-68134b7dbb03.png)

The issue could something deeper or even a bug in JVB upstream. Until someone else can spend time uncovering that, I have to keep the code the way it is for Windows users

**Comment by gjaekel** [comment]
> The problem with the wss to ws proxy was that it could not connect to the colibri-ws service anymore if the private http port is exposed in the conf file. That is what caused the one-way traffic from client to server and blocked server to client. I spent a few days unraveling this.

I'll  re-test this ASAP! I don't observed this and I memorized that you had have forgot some code for backchannel. But this might be wrong!

> I have to keep the code the way it is for Windows users.
Absolute no problem to hold it back because as a workaround I may use a read-only `application.conf`.

**Comment by deleolajide** [comment]
> BTW: At the moment, the colibri stats are pushed by the bridge via XMPP to OpenFire, right?

No. The colibri stats are requested using REST with a Java HTTPClient. There is no XMPP involved. Look again at https://github.com/igniterealtime/openfire-pade-plugin/blob/1bcbae070c9083e5ffbe865b1a57005dd7f8be12/ofmeet/src/main/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJvbWrapper.java#L348

**Comment by gjaekel** [comment]
Sorry - I'm a good way confused. I thought that `8080` was occupied by the Jetty server and we shift (the default) to `8180` for that! Notice: I also forget to change the existing property at first try.

Therefore, IMHO, the fixed port in
https://github.com/igniterealtime/openfire-pade-plugin/blob/1bcbae070c9083e5ffbe865b1a57005dd7f8be12/ofmeet/src/main/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJvbWrapper.java#L354
is wrong, now!

**Comment by gjaekel** [comment]
````root@apprfire0 ~  # for PID in $(jps -q); do ps ww -o pid,command -p $PID; lsof -Pani -sTCP:listen -p $PID; done
  PID COMMAND
  PID COMMAND
21769 /opt/openjdk-bin-8.275_p01/jre/bin/java -XX:+UseG1GC -Xms64m -Xmx256m -XX:MaxMetaspaceSize=128M -XX:MaxDirectMemorySize=64M -XX:MaxGCPauseMillis=50 -XX:ConcGCThreads=5 -XX:+ParallelRefProcEnabled -XX:ParallelGCThreads=5 -XX:ActiveProcessorCount=20 -XX:+UseStringDeduplication -Djava.io.tmpdir=/var/tmp -Djava.net.preferIPv4Stack=true -Dsun.net.inetaddr.ttl=60 -Djdk.nio.maxCachedBufferSize=262144 -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/opt/openfire.4_6_1_20201020-171600/plugins/ofmeet/classes/jicofo -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=config -Djava.util.logging.config.file=./logging.properties -Djdk.tls.ephemeralDHKeySize=2048 -cp ./jicofo-1.1-SNAPSHOT.jar:./jicofo-1.1-SNAPSHOT-jar-with-dependencies.jar org.jitsi.jicofo.Main --host=appr.xmpp.dnb.de --port=5275 --domain=appr.xmpp.dnb.de --secret=DQ4BjDcR604jPQLFUJB9bCp1gxLUgjdSEYkhXOSX --user_domain=appr.xmpp.dnb.de --user_name=focus --user_password=ofVCPass1
COMMAND   PID      USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
java    21769 openfireA   18u  inet 1391014851      0t0  TCP *:8888 (LISTEN)
  PID COMMAND
21725 /opt/openjdk-bin-8.275_p01/jre/bin/java -XX:+UseG1GC -Xms256m -Xmx3G -XX:MaxMetaspaceSize=128M -XX:MaxDirectMemorySize=512M -XX:MaxGCPauseMillis=50 -XX:ConcGCThreads=5 -XX:+ParallelRefProcEnabled -XX:ParallelGCThreads=5 -XX:ActiveProcessorCount=20 -XX:+UseStringDeduplication -Djava.io.tmpdir=/var/tmp -Djava.net.preferIPv4Stack=true -Dsun.net.inetaddr.ttl=60 -Djdk.nio.maxCachedBufferSize=262144 -Dconfig.file=/opt/openfire.4_6_1_20201020-171600/plugins/ofmeet/classes/jvb/application.conf -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/opt/openfire.4_6_1_20201020-171600/plugins/ofmeet/classes/jvb -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=config -Djava.util.logging.config.file=./logging.properties -Djdk.tls.ephemeralDHKeySize=2048 -cp ./jitsi-videobridge-2.1-SNAPSHOT.jar:./jitsi-videobridge-2.1-SNAPSHOT-jar-with-dependencies.jar org.jitsi.videobridge.MainKt  --apis=rest
COMMAND   PID      USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
java    21725 openfireA   19u  inet 1391061933      0t0  TCP *:8180 (LISTEN)
java    21725 openfireA   51u  inet 1391092621      0t0  TCP 127.0.0.1:8188 (LISTEN)
  PID COMMAND
21631 /opt/openjdk-bin-8.275_p01/bin/java -server -XX:+UseG1GC -Xms256m -Xmx512m -XX:MaxMetaspaceSize=128M -XX:MaxDirectMemorySize=512M -XX:MaxGCPauseMillis=50 -XX:ConcGCThreads=5 -XX:+ParallelRefProcEnabled -XX:ParallelGCThreads=5 -XX:ActiveProcessorCount=20 -XX:+UseStringDeduplication -XX:+PrintGCApplicationStoppedTime -Djava.io.tmpdir=/var/tmp -Djava.net.preferIPv4Stack=true -Dsun.net.inetaddr.ttl=60 -Djdk.nio.maxCachedBufferSize=262144 -Dcom.sun.management.jmxremote.port=11099 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.access.file=/opt/jmxremote/jmxremote.access -Dcom.sun.management.jmxremote.password.file=/opt/jmxremote/jmxremote.password.openfireA -DopenfireHome=/home/openfireA/openfire -Dopenfire.lib.dir=/home/openfireA/openfire/lib -Dlog4j.configurationFile=/home/openfireA/openfire/conf/log4j2.xml -classpath /home/openfireA/openfire/lib/bcpg-jdk15on.jar:/home/openfireA/openfire/lib/bcpkix-jdk15on.jar:/home/openfireA/openfire/lib/bcprov-jdk15on.jar:/home/openfireA/openfire/lib/bctls-jdk15on.jar:/home/openfireA/openfire/lib/hsqldb.jar:/home/openfireA/openfire/lib/javax.websocket-api.jar:/home/openfireA/openfire/lib/jtds.jar:/home/openfireA/openfire/lib/mail.jar:/home/openfireA/openfire/lib/mysql.jar:/home/openfireA/openfire/lib/npn-boot.jar:/home/openfireA/openfire/lib/openfire.jar:/home/openfireA/openfire/lib/postgres.jar:/home/openfireA/openfire/lib/slf5j-log4j12.jar:/home/openfireA/openfire/lib/startup.jar org.jivesoftware.openfire.starter.ServerStarter false false /dev/stderr /dev/stdout true true false  true true 0 0  20 20 Arial 0,0,0 8 500 version 4.0.2 20 40 Arial 0,0,0 8 500 -1
COMMAND   PID      USER   FD   TYPE     DEVICE SIZE/OFF NODE NAME
java    21631 openfireA   20u  inet 1391085460      0t0  TCP *:41151 (LISTEN)
java    21631 openfireA   21u  inet 1391085461      0t0  TCP *:11099 (LISTEN)
java    21631 openfireA   22u  inet 1391085462      0t0  TCP *:39111 (LISTEN)
java    21631 openfireA  146u  inet 1391014835      0t0  TCP *:7777 (LISTEN)
java    21631 openfireA  148u  inet 1391084033      0t0  TCP *:5229 (LISTEN)
java    21631 openfireA  151u  inet 1391106141      0t0  TCP *:9090 (LISTEN)
java    21631 openfireA  158u  inet 1391106147      0t0  TCP *:9091 (LISTEN)
java    21631 openfireA  437u  inet 1391093078      0t0  TCP *:5222 (LISTEN)
java    21631 openfireA  501u  inet 1391086990      0t0  TCP *:5223 (LISTEN)
java    21631 openfireA  565u  inet 1391050631      0t0  TCP *:5275 (LISTEN)
java    21631 openfireA  629u  inet 1391076194      0t0  TCP *:5263 (LISTEN)
java    21631 openfireA  641u  inet 1391106236      0t0  TCP *:7070 (LISTEN)
java    21631 openfireA  672u  inet 1391106247      0t0  TCP *:7443 (LISTEN)
```

**Comment by deleolajide** [comment]
>Note, that there's no listener at 8080

Yes. because 8188 is now the private http port. However, the colibri-ws proxy will fail to connect to 8188

**Comment by gjaekel** [comment]
The colibri-ws-proxy have to connect to the public if, I think. For me, IMHO, focus change working:
```
20201230-145608.764 INFO  [Jetty-QTP-BOSH-340] [o.j.o.p.o.OfMeetPlugin] JvbSocketCreator /colibri-ws/ofmeet/c626eee88259184b/d95906af?pwd=3gr9f4sjmbvtuk1619lhtf4i8k pwd=3gr9f4sjmbvtuk1619lhtf4i8k
20201230-145608.764 INFO  [Jetty-QTP-BOSH-340] [ProxyConnection] ProxyConnection ws://localhost:8180/colibri-ws/ofmeet/c626eee88259184b/d95906af?pwd=3gr9f4sjmbvtuk1619lhtf4i8k []
```
![image](https://user-images.githubusercontent.com/19855721/103355865-ac935100-4aaf-11eb-99da-7a2357c42625.png)

**Comment by gjaekel** [comment]
https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest.md:
Jitsi-videobridge supports two HTTP(S) interfaces, a public and a private one. The two interfaces use different ports. The private interface exposes HTTP endpoints which are not meant to be publicly accessible (but might be used by other components of the infrastructure, e.g. a signaling server), such as:

    The COLIBRI control interface (/colibri/)
    The health-check interface (/about/health)
    The version interface (/about/version)

The public interface is used for Colibri Web Sockets that clients connect to.

https://github.com/jitsi/jitsi-videobridge/blob/master/doc/statistics.md:
The statistics are available through the `/colibri/stats` endpoint on the private REST interface (if it has been enabled) in JSON format:

**Comment by gjaekel** [comment]
The path `/about/...` is not working, but this seems to be an upstream bug because it never worked for me even at the time as the proxy wasn't ready.
```
root@apprfire0 ~# wget -qSO- localhost:8188/about/health; echo
  HTTP/1.1 500 Internal Server Error
  Date: Wed, 30 Dec 2020 14:36:23 GMT
  Content-Type: application/json
  Content-Length: 73
  Server: Jetty(9.4.z-SNAPSHOT)

root@apprfire0 ~ # wget -qSO- localhost:8180/about/version; echo
  HTTP/1.1 404 Not Found
  Date: Wed, 30 Dec 2020 14:33:28 GMT
  Cache-Control: must-revalidate,no-cache,no-store
  Content-Type: text/html;charset=iso-8859-1
  Content-Length: 328
  Server: Jetty(9.4.z-SNAPSHOT)
```

But the `/colibri/...` path is functional.
```
root@apprfire0 ~ # wget -qSO- localhost:8188/colibri/conferences; echo
  HTTP/1.1 200 OK
  Date: Wed, 30 Dec 2020 14:18:22 GMT
  Content-Type: application/json
  Content-Length: 27
  Server: Jetty(9.4.z-SNAPSHOT)
[{"id":"c626eee88259184b"}]

root@apprfire0 ~ # wget -qSO- localhost:8188/colibri/conferences/c626eee88259184b; echo
  HTTP/1.1 200 OK
  Date: Wed, 30 Dec 2020 14:18:32 GMT
  Content-Type: application/json
  Content-Length: 1463
  Server: Jetty(9.4.z-SNAPSHOT)
{"contents":[{"channels":[{"endpoint":"46258311","channel-bundle-id":"46258311","sources":[2124585532],"rtp-level-relay-type":"translator","initiator":true,"ssrcs":[1712858121],"id":"5150b843ea8306ac","receive-simulcast-layer":null,"direction":"sendrecv","last-n":-1},{"endpoint":"d95906af","channel-bundle-id":"d95906af","sources":[2124585532],"rtp-level-relay-type":"translator","initiator":true,"ssrcs":[43590818],"id":"cd098595dd1dab92","receive-simulcast-layer":null,"direction":"sendrecv","last-n":-1}],"name":"audio"},{"channels":[{"endpoint":"d95906af","channel-bundle-id":"d95906af","sources":[2634147485],"rtp-level-relay-type":"translator","initiator":true,"ssrcs":[2160211154,2815518774,4268864540],"id":"6831ab849cf1b1c9","receive-simulcast-layer":null,"ssrc-groups":[{"sources":[2815518774,4268864540,2160211154],"semantics":"SIM"}],"direction":"sendrecv","last-n":-1},{"endpoint":"46258311","channel-bundle-id":"46258311","sources":[2634147485],"rtp-level-relay-type":"translator","initiator":true,"ssrcs":[1399072816,226279894,1584386412,2699487924,3388867352,2467089272],"id":"eeff04f9ce07c43f","receive-simulcast-layer":null,"ssrc-groups":[{"sources":[1399072816,226279894],"semantics":"FID"},{"sources":[1584386412,3388867352],"semantics":"FID"},{"sources":[2699487924,2467089272],"semantics":"FID"},{"sources":[1399072816,1584386412,2699487924],"semantics":"SIM"}],"direction":"sendrecv","last-n":-1}],"name":"video"}],"id":"c626eee88259184b"}  
```

**Comment by deleolajide** [comment]
@gjaekel For my sanity, could you please repeat this using 8080 instead of 8188 as your private http port and confirm colibri-ws is working with 8180. Thanks

**Comment by gjaekel** [comment]
I did so as good as possible because I'm just one person dancing between a PC, a Laptop and a Smartphone. It seems to work, see the screen shot before.

But we / you may check it a my Approval Stage, if you like!

**Comment by deleolajide** [comment]
>The colibri-wss-to-ws-proxy have to forward to the public interface, I think

You are quite correct. I got that wrong. Looks like something else was responsible for the colibri-ws proxy not working before. I am happy withe changes and keeping the private http limited to localhost. Need to make the system secure from the jitsi-meet hackers when they arrive ;-)
