### ISSUE TITLE
Custom branding.js file to be preserved

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#193]
For Padé : Add possibility to keep or upload a custom branding.js file so when plugin is upgraded settings are kepts

**Comment by deleolajide** [comment]
I have added a new tab for Pade Converse branding. It reads the actual branding.js file and stores the branding data as Openfire properties with prefix **pade.branding.** 

The branding.js file is now a servlet in Openfire which reads the stored properties and sends that as a JavaScript data.  You can enable/disable and set the default value of any setting defined in the actual branding.js file. You can't add or remove. To do that you must modify the actual branding.js file.

![image](https://user-images.githubusercontent.com/110731/103480973-c2668600-4dcf-11eb-9320-c900c40f2ac9.png)

**Comment by gjaekel** [comment]
I want to introduce P in the upcoming time. I was just "fighting" with the mapping between the Options page in the client and the internal names. This a *real* helpful  one!

I think the checkbox represents the "show/hide at client options page" functionality. In my eyes, this is a very important, but not obvious feature. And here, the meaning of the checkbox might be not self-explanatory, too!

You should add an short explanation at the head of the table, please.

**Comment by gjaekel** [comment]
Just for the logs: The following dirty trick of mine to ease the staging will not work any longer. But I don't claim to support this for obvious reasons :smile:
```
20210103-193148.481 ERROR [pool-7-thread-4] [o.j.o.p.o.OfMeetPlugin] [{}] Unexpected branding.js!
const xmpphost = "appr.xmpp.dnb.de"
var branding = {
    enableBeeKeeper         : {disable: true, value: false},
    beeKeeperTitle          : {disable: true},
    beeKeeperTopic          : {disable: true},
[...]
    domain                  : {disable: true , value: xmpphost },
    boshUri                 : {disable: true , value: "https://" + xmpphost + "/http-bind" },
    websocketUri            : {disable: true , value: "wss://" + xmpphost + "/ws" },
    ofmeetUrl               : {disable: true , value: "https://" + location.host + "/raum/" },
    useWebsocket            : {disable: true , value: true },
```

**Comment by gjaekel** [comment]
The migration from `options/branding.js` to the `pade.branding.*` properties is done at every startup of the plugin. But in the current plugin artifact, there's a such a file with some "enabled" (i.e. uncomented) tag-value pairs.

If the plugin is restarted via the plugin manager or replaced by hand (e.g. to install a new version), this artifact-provided version of the file is unpacked and will overwrite the current (probably changed) values.

**Comment by deleolajide** [comment]
> this artifact-provided version of the file is unpacked and will overwrite the current (probably changed) values.

That is a bug. We should NOT update when Openfire has a stored value

**Comment by ClaudeStabile** [comment]
Hello

I have modified my branding.js and set up homepage + OfmeetURL. Both settings are not set in Padé Options, other parameters like showToolbarIcons and  enableDirectorySearch are correctly set from branding.js within jar file
I am now using latest 1.3.0 with variables.

_enableHomePage      : {disable: false, value: true},
homePage            : {disable: false, value: "https://www.crossperience.ch/test02"},
           showToolbarIcons : {disable: false, value: true},
ofmeetUrl               : {disable: false, value: "https://talk.crossperience.ch/"},
        enableRingtone : {disable: false, value: true},
         conversePlaySounds : {disable: false, value: true},
        converseEmbedOfMeet : {disable: false, value: false},
enableDirectorySearch   : {disable: true, value: false},
        showToolbarIcons    : {disable: false, value: true},_

Homepage still unticked after refreshing all caches and settings


![screenshot79](https://user-images.githubusercontent.com/29485972/103689214-49b02700-4f93-11eb-8ed0-77a06beb3c0a.png)

Thanks a lot for the move. It will enable an easier customisation of the package :)
