### ISSUE TITLE
Room "In Progress..." does not show up on Android

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#195]
Hello,

I am now using room in progress, works nicely on computers but does not show progress room list on Mobile, Nice to have :)
Another Nice addon : Possibility to change via console "In progress.." by whatever we like

Congrats for this magic enhancement :)

**Comment by gjaekel** [comment]
As we deliver a Web-App-client and not an Android or iOS-App, this feature is not available on this.

**Comment by cool0707** [comment]
I have not checked if Pade Meetings works on Android, but if you modify `@media only screen and (max-width:500px)` part of all.css, it may show up.

**Comment by gjaekel** [comment]
Yes; narrowing my desktop browsers window, it seems to be effectively
```
@media only screen and (max-width:500px){
    .welcome .welcome-tabs{
        display:none
    }
}
```
which might by overriden by appending this with `display:unset` to `customer_ofmeet.css`.
