### ISSUE TITLE
Keeps asking for media permission with every click of an object like Cam or Screen share Mic

### ISSUE THREAD

**Issue by JoshWho** [igniterealtime/openfire-pade-plugin#198]
The meeting window once it pops up asks for same permission over and over again. How to make that auto click yes or bypass it?

![mediaaccess](https://user-images.githubusercontent.com/39392449/103574400-73832400-4e95-11eb-83fa-d1bef861374d.png)

**Comment by deleolajide** [comment]
This is not the normal behavior in supported browsers. Can you please provide more information about your browser and desktop from where this was run.

**Comment by JoshWho** [comment]
This is the built in browser that the Pade meetings uses.  Not my computer browser. I have no control or access to whatever browser the spark messenger is using to open a window.

![15](https://user-images.githubusercontent.com/39392449/103643782-d9fe5580-4f1a-11eb-91fd-0f0826473e00.png)

**Comment by deleolajide** [comment]
> This is the built in browser that the Pade meetings uses.

Pade does not have a built-in browser. It uses the default browser on the device being used. Android, Windows, Mac or Linux.

From your screenshot, you are using Spark Meet plugin which is using Electron browser. Electron does not save user browser settings. This means Electron will always ask for permissions to access camera, microphone or desktop

**Comment by JoshWho** [comment]
That is a bummer. No work around for Electron?

**Comment by JoshWho** [comment]
I see something about being able to disable security in it here https://stackoverflow.com/questions/35852684/electron-chromium-disable-web-security

**Comment by deleolajide** [comment]
I think you need to raise an issue on Spark and not Pade for that

**Comment by JoshWho** [comment]
I c. Will do that. Thank you.
