### ISSUE TITLE
Migrated from Meetings 0.95 to Pade version 0.98

### ISSUE THREAD

**Issue by renatohtpc** [igniterealtime/openfire-pade-plugin#2]
I have unistalled version 0.95 of the Openfire Meetings and replaced it with Dale’s 2 plugins (offocus.jar ofmeet.jar version 0.98)

I have restarted OF and went to the Meetings -> User Interface page.

On this page I see several entries with leading and trailing “???”

> 

Mute / Unmute
--
Start / Stop camera
???ofmeet.toolbar.button.closedcaptions.description???
Start / Stop screen sharing
View / Exit full screen
Device Selection
Leave
Edit your profile
Get access info about the meeting
Open / Close chat
???ofmeet.toolbar.button.recording.description???
???ofmeet.toolbar.button.livestreaming.description???
Open / Close shared document
Share a YouTube video
Settings
Raise / Lower your hand
Manage call quality
???ofmeet.toolbar.button.filmstrip.description???
Share the link of the Meet
Leave Feedback
Show speaker statistics
View keyboard shortcuts
Tile View
???ofmeet.toolbar.button.videobackgroundblur.description???
???ofmeet.toolbar.button.download.description???
???ofmeet.toolbar.button.help.description???
???ofmeet.toolbar.button.mute-everyone.description???

How do I remove those entries?

Thanks

Renato

**Comment by deleolajide** [comment]
Thanks for reporting this. I have to update the Description data for the new UI settings in latest Jitsi code
