### ISSUE TITLE
Anybody can create a room

### ISSUE THREAD

**Issue by rcampion** [igniterealtime/openfire-pade-plugin#20]
I have updated ofmeet plugin from 0.9.8 to 0.9.9

Openfire 4.5.1

Anybody can create a room.

Room Creation Permissions are set to Only specific users/groups can create a chat room.

**Comment by deleolajide** [comment]
Video conference rooms are created by focus bot user which has admin permissions.

**Comment by gjaekel** [comment]
> I have updated ofmeet plugin from 0.9.8 to 0.9.9
> Anybody can create a room.
I wonder if this have changed, are you sure about this relationship?

**Comment by rcampion** [comment]
The workaround is to set Default Room Settings to members only.    
Focus user will still create the room but users trying to enter the room will get a connection failure.
