### ISSUE TITLE
Redirect to https

### ISSUE THREAD

**Issue by cool0707** [igniterealtime/openfire-pade-plugin#208]
I would like to redirect http connections to https, since Chrome and Chromiun Edge cannot use the camera and microphone for http connections.
I tried the method of writing security-constraint in web.xml, but it did not work.
Instead, I am using Java Script in index.html to redirect, but I think it is smarter to use HSTS.
Is there any way to do this?

**Comment by deleolajide** [comment]
I am using a reverse proxy in front of pade.chat to forward http to https. [Chrome is going to make https the default very soon](https://9to5google.com/2021/01/11/google-chrome-address-bar-may-soon-default-to-https/), so I don't see the point of making any other changes.

You can try [HSTS Preloading](https://https.cio.gov/hsts/#configuration-for-common-web-servers)

**Comment by ayushbhat** [comment]
@cool0707 Nginx Reverse Proxy works quite well for this too.

**Comment by gjaekel** [comment]
You may even set up a minimal "redirect-to-https" webservice using `socat`.

**Comment by cool0707** [comment]
I understand that Openfire itself doesn't seem to have a redirection feature.
Since I have Openfire installed on a Windows server, I decided to use IIS HTTP redirection.

**Comment by gjaekel** [comment]
> I understand that Openfire itself doesn't seem to have a redirection feature.

Correct. But it should be a job of minutes for somebody who is familiar with Jetty to add a general, canonical `http://any.site/anypath?anyquery -> https://any.site/anypath?anyquery` relocation feature.
