### ISSUE TITLE
pàdé-Register missed in Openfire-admin-console

### ISSUE THREAD

**Issue by Maggus1977** [igniterealtime/openfire-pade-plugin#209]
First of all to the community: You are doing a good an great work with openfire/pàdé.
Since ~05/2020 I have a look to the project. Since ~10/2020 I´m using the soucecode to compile it on my local Opensuse 42.2 and upload the targets and I try to learn how it works. (Usually it works great, if artifacs aren't move.)
Three days ago I had deleted /opt/openfire on my vserver (centos) to set up a complete new instance of OF.
Setting up the new openfire (dailybuid and offical 4.6.1) worked again in a fast way.
But there is a problem to set up pade at OF-Adminconsole in all newest versions (sourcecodebuild / official 1.3 / old 1.22).
I can call the setuppages by the directlink (ex. https://xxxxxxxxx.de:9091/plugins/pade/ofmeet-summary.jsp) and I can use it, but I have to know the right adress. I deleted all caches, I restarted OF, I used two different browser - no more Idea. Can someone confirm the problem?
It shows working focus, working jvb  - but there is no register with "pade".
Well, the restore worked well, but I would like to setup a completely new without old mysql-database.
Do you need more information? - There is no useful log entry.

**Comment by gjaekel** [comment]
It's a good hint that you may access the pages "by hand". There's something ringing a bell, but it don't jump out, yet.... Which language do you use for the Admin UI? Is there any (empty) tab starb?

May you provide a cleand log beginning with the startup?

**Comment by deleolajide** [comment]
Openfire 4.6.1 has changed some MUC APIs that is causing loading issue in Pade. Please stay on 4.6.0 for now

**Comment by gjaekel** [comment]
@Dele: But ...
![image](https://user-images.githubusercontent.com/19855721/104817806-ebe9cd80-5823-11eb-8148-449501d0e1a3.png)

**Comment by Maggus1977** [comment]
Hello @gjaekel and @deleolajide 
last attempt I used english. Its a good Idea with an empty tab: I had a look into html-code.
There's in jive-nav / jive-nav-left:
"/index.jsp" "/user-summary.jsp" "/session-summary.jsp" "/muc-room-summary.jsp" "/plugins/fastpath/workgroup-summary.jsp" "/plugin-admin.jsp"
In "jive-subnav"
"/index.jsp" "/profile-settings.jsp" "/security-certificate-store-management.jsp" "/media-proxy.jsp" "/pubsub-service-summary.jsp" "/plugins/bookmarks/groupchat-bookmarks.jsp" "/plugins/clientcontrol/client-features.jsp".

Well, before dropping my working installation I used newest OF-Code.
Theres a problem with a new installation. So will I try out 4.6.0.

**Comment by deleolajide** [comment]
> But I'm already installed `4.6.1-GA` at Eval stage, and there's the Pàdé tab

It is missing on mine

![image](https://user-images.githubusercontent.com/110731/104817893-32d3c500-581c-11eb-8825-3016dbd99ce9.png)

**Comment by gjaekel** [comment]
That's a real mystery!

**Comment by gjaekel** [comment]
Long, long time ago, I had have trouble with left-overs in `\var\tmp\jetty*`
```
root@evalfire0 # ll -d /var/tmp/jetty-0_0_0_0-*
drwx------ 3 openfireE openfireE 4.0K Jan 15 20:32 /var/tmp/jetty-0_0_0_0-7070-classes-_httpfileupload-any-1263712392543453883/
drwx------ 3 openfireE openfireE 4.0K Jan 15 20:32 /var/tmp/jetty-0_0_0_0-7070-classes-_monitoring-any-3100332496255574874/
drwx------ 3 openfireE openfireE 4.0K Jan 15 20:32 /var/tmp/jetty-0_0_0_0-7070-docs-_pade-any-8694790645268709297/
drwx------ 3 openfireE openfireE 4.0K Jan 15 20:32 /var/tmp/jetty-0_0_0_0-7070-jitsi-meet-_ofmeet-any-6512035829765147914/
drwx------ 3 openfireE openfireE 4.0K Jan 15 20:32 /var/tmp/jetty-0_0_0_0-7070-private-_dashboard-any-4655484248090329260/
drwx------ 3 openfireE openfireE 4.0K Jan 15 20:32 /var/tmp/jetty-0_0_0_0-7070-spank-_-any-3227763763568712329/
drwx------ 3 openfireE openfireE 4.0K Jan 15 20:32 /var/tmp/jetty-0_0_0_0-7070-well-known-__well-known-any-5951855696421221152/
drwx------ 3 openfireE openfireE 4.0K Jan 15 20:32 /var/tmp/jetty-0_0_0_0-7070-win-sso-_sso-any-5586787225471167119/
drwx------ 3 openfireE openfireE 4.0K Jan 10 17:05 /var/tmp/jetty-0_0_0_0-9090-webapp-_-any-4172082992630649369/
drwx------ 3 openfireE openfireE 4.0K Jan 10 20:32 /var/tmp/jetty-0_0_0_0-9091-webapp-_-any-5389116576303811391/      
```
This days, I had have to stop OpenFire, `rm -r` this and start again. Just as an desperate hint .. ;)

**Comment by Maggus1977** [comment]
Well, now it works with nightbuild from today.
I downgraded openfire to 4.6.0-1.
system daemon-reload 
systemcrtl restart openfire
Than I upgraded to 4.6.1-1 and than to nightbuild.
It works. Realy a mystery.  Hope that help some others.
You are a great team!  Be health in 2021!

**Comment by gjaekel** [comment]
My Congratulations! But I's not satisfactory not to know the core reason ...

**Comment by gjaekel** [comment]
@Markus: Ich bin weiterhin an einem direkten Austausch interessiert.

**Comment by Maggus1977** [comment]
Gerne. Ich werde auch nicht plötzlich verschwunden sein.
Ihr tauscht Euch nur auf einem hohen Level aus, da überlege ich mir 20 mal, was ich noch ausprobieren kann.
Gut, so ist ein Hinweis denen gegeben, die vielleicht auch auf openfire / pade neugierig geworden sind.
Und tatsächlich sollten wir auf Fehlersuche gehen. Ich setze evtl. morgen eine virtuelle maschine auf und bin neugierig, ob ich etwas entdecke. Allerdings sind meine Kenntnisse eher schwach...

**Comment by gjaekel** [comment]
Ich meinte per email, about you and what's the purpose you're using OpenFire. Because it's not related to the Issue and we should use English here.

**Comment by gjaekel** [comment]
I lost the track, what's the **current** state: 
* Need Pàdé-1.3.1 an Openfire-4.6.1 to work on?
* Will the current head already work with OpenFire-4.6.2?

**Comment by deleolajide** [comment]
1.3.1 works with OF 4.6.1+ There are some breaking MUC changes that mostly affect the lobby feature and requires work to the code. Apart from that everything else works. My production is still at 4.5.1
