### ISSUE TITLE
All participants are moderators

### ISSUE THREAD

**Issue by rcampion** [igniterealtime/openfire-pade-plugin#21]
Steps to reproduce
Login with first user/password on one machine
Login with second user/password on another machine

Environment details
CentOS7
Openfire 4.5.1
Ofmeet 0.9.9
Jitsi Meet / master branch 04/30/2020

**Comment by rcampion** [comment]
Steps to reproduce
Login with first user/password on one machine
Login with second user/password on another machine

Environment details
CentOS7
Openfire 4.5.1
Ofmeet 0.9.10
Jitsi Meet / master branch 05/17/2020

**Comment by deleolajide** [comment]
Could you check your openfire MUC settings and make sure both users are not moderators of the chatroom

**Comment by rcampion** [comment]
In the MUC room, all room occupants are moderators.

I tried to attach a pic but it didn't work.

**Comment by rcampion** [comment]
I think I see my problem.  Somehow the second user was a Room Owner.  I deleted that user from Room Owners and now it is fine.  Thanks.
