### ISSUE TITLE
APP.conference.addConferenceListener has been removed

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#210]
Refactor custom_ofmeet.js to work with Jitsi-Meet latest code that has removed [APP.conference.addConferenceListener](https://github.com/igniterealtime/openfire-pade-plugin/blob/29afe1ec6b1a583d4f9fc443ba9e84b5f30efd2b/web/src/main/webapp/custom_ofmeet.js#L181)

https://github.com/igniterealtime/openfire-pade-plugin/blob/29afe1ec6b1a583d4f9fc443ba9e84b5f30efd2b/web/src/main/webapp/custom_ofmeet.js#L181

**Comment by cool0707** [comment]
It's not a good idea because it seems to be deprecated, but in the interim, I think we could try changing `APP.conference.addConferenceListener` to `APP.conference._room.on`.

**Comment by deleolajide** [comment]
> I think we could try changing `APP.conference.addConferenceListener` to `APP.conference._room.on`

Thank you. That worked 👍

**Comment by cool0707** [comment]
Maybe the conference object should be get like this instead of `APP.conference._room`
```
var conference = APP.store.getState()['features/base/conference'].conference;
conference.on(JitsiConferenceEvents.SOME_EVENT, callback);
```

**Comment by deleolajide** [comment]
> Maybe the conference object should be get like this instead of `APP.conference._room`

Agreed.  Using _room could break anytime as it is probably an object with private scope
