### ISSUE TITLE
Feature Request: Localize original features of Pade Meetings

### ISSUE THREAD

**Issue by cool0707** [igniterealtime/openfire-pade-plugin#216]
I would like to localize the custom features of Pade Meetings (Break Room, Conference Captions/Subtitles, etc.).
I will post a pull request to localize the tooltips and other icons in the meeting screen.

In addition, I tried to make the tooltips similar to those of Jitsi Meetings.

**Comment by gjaekel** [comment]
We may rise another Issue for that, but it's related: As I'm a "commandline guy" and prefer to work with keyboard over the mouse, It would be a pleasure for me to add **hotkeys** to the custom features as well!

**Comment by cool0707** [comment]
If you want to add keyboard shortcuts, you can do it by calling APP.keywordshortcut.registerShortcut() after the block that adds each function in `custom_ofmeet.js`.
For example, for the Confetti function, you can add the following after L2292.
https://github.com/igniterealtime/openfire-pade-plugin/blob/30c4f11463cbe1317ab91c58a84a23b0cbfff10d/web/src/main/webapp/custom_ofmeet.js#L2288-L2293

```
 APP.keyboardshortcut.registerShortcut('E', null, () => {
    APP.conference.commands.sendCommandOnce("CONFETTI", {value: !0})
}, i18n('toolbar.shareSomeConfetti'));
```

The `i18n('toolbar.shareSomeConfetti')` is part of my PR, so if you haven't applied the PR, please change it to some text.
This is the description that comes up with shortcut key "?".

**Comment by gjaekel** [comment]
Thank you a lot. At my current level, the code snippet exactly serve my need. I deal >30 with electronics and computing. I'm able to read and understand the code at the second. But as I'm not acting as a developer, I don't "speak" any computing language and all of it's frameworks and libraries fluently.

But also, thank you a lot for the additional description. This will avoid to miss something on the conceptual level.

Maybe you get the time to take a look at #146, too. It would be better to solve it at the roots as to add some crude event listener as a fix.

**Comment by deleolajide** [comment]
Please be aware that [latest Jitsi Meet stable code has broken custom_ofmeet.js](https://github.com/igniterealtime/openfire-pade-plugin/issues/210). I don't know the full scope yet. I also had issues trying to make the // BAO changes to the minified files. We might have to look at cloning/forking Jitsi Meet and applying changes at source before creating our own minified build files

**Comment by gjaekel** [comment]
Thank you for the warning alert! May you set up a branch?

**Comment by deleolajide** [comment]
> What's BAO standing for?

The initials of my full name **B**andele **A**yinde **O**lajide :-)

**Comment by deleolajide** [comment]
> Thank you for the warning alert! May you set up a branch?

I think you should chat with @akrherz or @guusdk about  upgrading your community/team GitHub permissions

**Comment by akrherz** [comment]
> I think you should chat with @akrherz about upgrading your community/team GitHub permissions

Should be done now.

**Comment by gjaekel** [comment]
@akrherz Thank you and the team for your confidence, I feel honored!
