### ISSUE TITLE
Feature: Auto-hide mouse pointer

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#218]
The mouse pointer is always visible, which may e.g. "select" and therefore gray-shade appearing participant windows in Tile view. In addition, the mouse pointer of other participants are also visible in a screen share mode, which may confuse oneself.

Make the mouse point hidden after a while.

**Comment by deleolajide** [comment]
Hiding the mouse pointer is in conflict with shared cursors which I use when doing a shared screen session with labeled shared cursors.  In addition, both my local and remote cursors in screen at the same time gives me an indication of latency.

To make this PR acceptable, we have to make this feature configurable from Admin UI settings web page with **always show** as default behavior.

**Comment by gjaekel** [comment]
> Hiding the mouse pointer is in conflict with shared cursors
I understand. I expect that there's a state flag, which might be used.

> make this feature configurable from Admin UI settings web page
You define the guidelines! And I agree that this is in line with the configurable timout of the toolbar. May I use this (timeout values or even time) for simply (of the UI, not for the effort to implement)?

**Comment by deleolajide** [comment]
> Make it a separate configure option to let the user the freedom of choice, right?

Shared cursors does not yet have UI setting. We should create one for it and use it to hide/show mouse pointer.

**Comment by gjaekel** [comment]
> Shared cursors does not yet have UI setting. We should create one for it 

Ey!, and it's a incomplete beta feature yet.

> and use it to hide/show mouse pointer.

This I don't understand. To toggle of auto-hide while the share-the-mouse-pointer is on is the one thing. But having a config entry for the idle timeout at the UI is a second, well?

**Comment by deleolajide** [comment]
I just want the choice of having my cursor visible. In order to support that, we need to make this choice configurable. We don't have to make the timeout  configurable. 

I think I will just accept the change and do the work of configuring it myself. It will be much easier.

**Comment by gjaekel** [comment]
> I just want the choice of having my cursor visible. In order to support that, we need to make this choice configurable. 

For a concrete participant or global, for all by the administrator?

> We don't have to make the timeout configurable.

**If** in the Admin UI, **then** instead of a checkbox I vote to add a timeout item with a ms value.

By the way: For me it's the common expected behaviouor that the mouse cursor will disappear after a while in an "video player" application.

**Comment by gjaekel** [comment]
@deleolajide @cool0707
I have enabled the shared mouse pointer tool. And I also have **disabled** the check
https://github.com/igniterealtime/openfire-pade-plugin/blob/9fe7dc84fa8aa28d769fb1f9487e6c876d9186e6/web/src/main/webapp/custom_ofmeet.js#L115
for every new version since merging the _autohide mouse pointer_ feature in (by inserting `true || ...`)

I can't see any problems with this and also, no problem was reported by our users. I want to ask for your confirmation to remove this dependency.

@deleolajide 
>I just want the choice of having my cursor visible. In order to support that, we need to make this choice configurable. We don't have to make the timeout configurable.
This is an outstanding ToDo, isn't it? 
* I would place it at the section UI Setting|Toolbar Configuration below the Toolbar timeout settings.
* We may define and use `interfaceConfig.OFMEET_CURSOR_AUTOHIDE_TIMEOUT` with the special value zero as infinity, i.e. disabled and an default of 10000ms
