### ISSUE TITLE
Make offocus ignoring non-ofmeet members of a room.

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#22]
When using a room that is "shared" with an XMPP text chat, the focus user will be aware of room members associated to other (e.g. "conventional" text-only chat) clients.

A problem resulting from this that "focus" will not leave the room at end of an ofmeet conference because it see still members that not leave.

Please make "focus" eyeless against such non-ofmeet members. Maybe this might be eased by prepend some prefix to the generated user names. If not possible, a heuristic match of the user name pattern might be enough (by length, consisting of hex chars, maybe with an plausible mix of digits and letters)

**Comment by deleolajide** [comment]
This issue was debated at ignite-realtime and the conclusion was to agree that we do not use the same room for persistent chat and meetings.  In other words, don't share room between chat and meetings.

That is why the Pade client generates meeting room names using the current chat room name as a prefix.

**Comment by gjaekel** [comment]
This may hold for many (or most) use cases, but not for all.

Our users *want* to use the same room names. Because after a couple of weeks there pinned rooms for a lot of groups and some special groups use (fixed) room passwords. And some even use the text chat from clients (including the chat history) to re-read or access textual informations like posted URLs.

**Comment by deleolajide** [comment]
I think you may have raise this issue with the Jitsi Team to modify the Jifco component.

**Comment by gjaekel** [comment]
May you point me to a person or location to contact?

**Comment by deleolajide** [comment]
> May you point me to a person or location to contact?

https://community.jitsi.org/

**Comment by deleolajide** [comment]
>This may hold for many (or most) use cases, but not for all.

Agreed, but this use case is no more on the road-map for Pade. As I said before, we discussed this at length at ignite-real-time and even experimented with making the open_chat public chat room available for meetings before making this decision. I am therefore closing this issue.
