### ISSUE TITLE
Possible Enhancement: Support width constrains for the video stream

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#224]
Found a definition for a Webclient's `config.js` that contain a section that also declare the **witdh** of a video
```
    constraints: {
        video: {
            height: {
                ideal: 720,
                max: 720,
                min: 180
            },
            width: {
                ideal: 1280,
                max: 1280,
                min: 320
            }
        }
```

First step would be to gather more information about the semantics and to play around with this using different video sources like different models of webcams.

Maybe this will help to avoid a "mourning border" effect that some of your participants see since the update to JVB2: The video constrains may be sometimes negotiated in a way that leads to a 4:3 picture surrounded with black borders to fill to 9:16. Toggling the video stream after a conference is established helps out in most cases (, but not in all).

**Comment by deleolajide** [comment]
It is already supported

https://github.com/igniterealtime/openfire-pade-plugin/blob/9d7635bd05358fa86de1dea395a3d01560e724cd/web/src/main/java/org/jivesoftware/openfire/plugin/ofmeet/ConfigServlet.java#L115

**Comment by gjaekel** [comment]
I'll try to play with this together with some co-workers.
And integrating this in Admin UI is one more ToDo for the backlog :)

**Comment by gjaekel** [comment]
@deleolajide I have prepared the Admin UI integration. What do you think about?

![image](https://user-images.githubusercontent.com/19855721/106395111-bf77a900-6400-11eb-88fc-e10add288931.png)

There were also some "comment-bugs"

**Comment by deleolajide** [comment]
> I cant find the older `org.jitsi.videobridge.ofmeet.resolution` in the Admin GUI. Has this been already kicked out?

I think so. Jitsi config settings have changed so much over the years. I have lost track

**Comment by gjaekel** [comment]
I still have no IDE available. But if @okuhn is in the mood and have spare time, we may do some global refactoring and cleanup.

E.G. the prefix-combination `org.jitsi.videobridge.ofmeet` is somewhat unneccesary, one may use `org.jitsi.videobridge.` for upstream provided and plain `ofmeet.` for add-ons of the project.
