### ISSUE TITLE
breakout room feature work very unreliable

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#23]
The breakout room feature don't work for us:
- The icon for invoking the breakout control panel don't appear in a reliable way. Sometime, it takes about 2s after joining the room, in many cases it don't appear.
- The list of members in the panel may not complete, also.

During our last test with ten people, the icon first don't appear for the moderator but after re-joining. Then, just one other person was visible at the panel - this was visible to all by screen-casting the moderators browser window.
At least, the moderator was able to "transport" this person in a separate room.

**Comment by deleolajide** [comment]
Thanks for testing it. I have only used in testing so any feedback is very useful to improve it

> The icon for invoking the breakout control panel don't appear in a reliable way

It only appears if the user is a moderator. For temporary rooms, this means the first user who creates the room. For permanent rooms, make sure you assign the role to right people.

>Sometime, it takes about 2s.

Jitsi have not provided an API to modify their UI. I am doing this by checking every second for the creation of HTML elements.

>The list of members in the panel may not complete, also.

There could be other issues preventing that from happening. Next time it happens, please open the dev tools panel (chrome) and take a log. Any errors you find will be useful to narrow down the issues.

>the icon first don't appear for the moderator but after re-joining.

Someone else became moderator

>Then, just one other person was visible at the panel

That is the issue I have track done and fix asap.

**Comment by gjaekel** [comment]
>>  the icon first don't appear for the moderator but after re-joining.

> Someone else became moderator

I misworded this. The first joined person was the moderator (with star). Others join, and after some time, me too. I asked him and the moderator don't had have the icon. He leave (the second person become moderator), rejoin (he also become moderator, again) and get the icon.

> There could be other issues preventing that from happening. Next time it happens, please open the dev tools panel (chrome) and take a log. Any errors you find will be useful to narrow down the issues.

The most of the users will be completely overcharged with this. Therefore, you have to wait if someone capable (e.g. our devs at their your fixe) will have time to support here.

Do you think it's a "real" scenario if I try to simulate a couple of people using several browser tabs and the same account?

**Comment by deleolajide** [comment]
> Do you think it's a "real" scenario if I try to simulate a couple of people using several browser tabs and the same account?

That is how I tested it. Many tabs :-)

**Comment by deleolajide** [comment]
> Maybe there's a race condition with this?

Most likely. I need to adjust the intervals and timeouts based on real life use.

**Comment by deleolajide** [comment]
There is a new commit- https://github.com/igniterealtime/openfire-pade-plugin/commit/67292cc4af514571093c4cae19a854a5d66471e1 that does a disco items discovery to get all the participants in a room as a backup to tracking the join/leave rooms events.

If you want to try it out, download both updated jar files for 0.9.9 at https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v0.9.9

**Comment by deleolajide** [comment]
Increased timeout to 5 secs
