### ISSUE TITLE
Feature: Log audit event when a meeting finishes

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#235]
Log audit event when a meeting finishes and use a snapshot of JVB stats as the comment.

**Comment by deleolajide** [comment]
![image](https://user-images.githubusercontent.com/110731/106208290-0b391100-61bb-11eb-8d2c-643be5afca13.png)

**Comment by gjaekel** [comment]
Good Idea, but in my eyes some of this information are to raw or superfluous, because they are not related to the concrete meeting but to the global state at end of the meeting. 

* time: superfluous - it's the timestamp of the JVB JVM for the pulled statet - this should be the same as the timestame of the audit log entry
* uptime: "raw". I want to reformat it in a human readable format at Admin UI's Pàdé Overview. And it's a bit of useless here for my eyes.
* failed, completed, ... global stats - not related to the meeting.

But one may add the list of the participants like in the InProgressServlet!

I would like to see here some technical data like transfer volume. The JVB1 wrote it down to the log. JVB2 don't; the techincal info about *ongoing* conferences is available via the debug interface. But I fear that it's "just to late" if we get notice of this.

**Comment by gjaekel** [comment]
Here an live example about technical conference stats
```
root@prodfire0 ~ # /usr/bin/wget -qO- localhost:8188/colibri/conferences | json_pp
[
   {
      "id" : "d5cf8b4e864d2234"
   },
   {
      "id" : "8db75a53da57602"
   },
   {
      "id" : "44a8fd92e5de9682"
   }
]                                                                                                                                                                                                                                                                      20210129-080548
root@prodfire0 ~ # /usr/bin/wget -qO- localhost:8188/colibri/conferences/d5cf8b4e864d2234 | json_pp
{
   "contents" : [
      {
         "name" : "data",
         "sctpconnections" : [
            {
               "channel-bundle-id" : "4103ff9d",
               "endpoint" : "4103ff9d",
               "id" : "f1301d54e3c4bee7",
               "initiator" : true,
               "port" : 5000
            },
            {
               "channel-bundle-id" : "52951d46",
               "endpoint" : "52951d46",
               "id" : "9adbbcd7a70593a7",
               "initiator" : true,
               "port" : 5000
            }
         ]
      },
      {
         "channels" : [
            {
               "channel-bundle-id" : "4103ff9d",
               "direction" : "sendrecv",
               "endpoint" : "4103ff9d",
               "id" : "8fef0d82b7a0503a",
               "initiator" : true,
               "last-n" : -1,
               "receive-simulcast-layer" : null,
               "rtp-level-relay-type" : "translator",
               "sources" : [
                  2047628407
               ],
               "ssrc-groups" : [
                  {
                     "semantics" : "FID",
                     "sources" : [
                        1630014349,
                        3555861865
                     ]
                  },
                  {
                     "semantics" : "FID",
                     "sources" : [
                        139113857,
                        1391580691
                     ]
                  },
                  {
                     "semantics" : "FID",
                     "sources" : [
                        1394779360,
                        1946096356
                     ]
                  },
                  {
                     "semantics" : "SIM",
                     "sources" : [
                        1630014349,
                        139113857,
                        1394779360
                     ]
                  }
               ],
               "ssrcs" : [
                  1630014349,
                  3555861865,
                  139113857,
                  1394779360,
                  1391580691,
                  1946096356
               ]
            },
            {
               "channel-bundle-id" : "52951d46",
               "direction" : "sendrecv",
               "endpoint" : "52951d46",
               "id" : "29146aefe99f26e0",
               "initiator" : true,
               "last-n" : -1,
               "receive-simulcast-layer" : null,
               "rtp-level-relay-type" : "translator",
               "sources" : [
                  2047628407
               ],
               "ssrc-groups" : [
                  {
                     "semantics" : "SIM",
                     "sources" : [
                        2130667292,
                        3815543262,
                        2051021776
                     ]
                  },
                  {
                     "semantics" : "FID",
                     "sources" : [
                        2130667292,
                        3351266494
                     ]
                  },
                  {
                     "semantics" : "FID",
                     "sources" : [
                        3815543262,
                        2847148072
                     ]
                  },
                  {
                     "semantics" : "FID",
                     "sources" : [
                        2051021776,
                        1441173623
                     ]
                  }
               ],
               "ssrcs" : [
                  2130667292,
                  3815543262,
                  2051021776,
                  3351266494,
                  2847148072,
                  1441173623
               ]
            }
         ],
         "name" : "video"
      },
      {
         "channels" : [
            {
               "channel-bundle-id" : "52951d46",
               "direction" : "sendrecv",
               "endpoint" : "52951d46",
               "id" : "3b07e901686a6303",
               "initiator" : true,
               "last-n" : -1,
               "receive-simulcast-layer" : null,
               "rtp-level-relay-type" : "translator",
               "sources" : [
                  3570891984
               ],
               "ssrcs" : [
                  1183965017
               ]
            },
            {
               "channel-bundle-id" : "4103ff9d",
               "direction" : "sendrecv",
               "endpoint" : "4103ff9d",
               "id" : "c9a1a38902cc2fc3",
               "initiator" : true,
               "last-n" : -1,
               "receive-simulcast-layer" : null,
               "rtp-level-relay-type" : "translator",
               "sources" : [
                  3570891984
               ],
               "ssrcs" : [
                  1394861382
               ]
            }
         ],
         "name" : "audio"
      }
   ],
   "id" : "d5cf8b4e864d2234"
}                               
```

**Comment by gjaekel** [comment]
What's about (a Java8 supported)
```
public static String humanReadableFormat(Duration duration) {
    return duration.toString()
            .substring(2)
            .replaceAll("(\\d[HMS])(?!$)", "$1 ") // simply remove this line to get rid of the spaces between sections in output
            .toLowerCase();
}
```
to format the runtime of the bridge?

**Comment by GregDThomas** [comment]
https://github.com/igniterealtime/Openfire/blob/master/xmppserver/src/main/java/org/jivesoftware/util/StringUtils.java#L902

will do something like "4 days, 12 hours, 3 minutes and 45 seconds"

**Comment by gjaekel** [comment]
... a complex implementation. But of course, it's **much better** to use this first! And maybe refactor it in future, if any need for this at all.

**Comment by deleolajide** [comment]
Thanks @GregDThomas  for the StringUtils tip and @gjaekel for the duration idea. 

![image](https://user-images.githubusercontent.com/110731/106354118-53555200-62e7-11eb-89d3-301cc798e663.png)

For now, I am happy with audit logging matching the summary as a snapshot.

![image](https://user-images.githubusercontent.com/110731/106354172-91527600-62e7-11eb-8e53-43de83ab1fc1.png)

**Comment by gjaekel** [comment]
> For now, I am happy with audit logging matching the summary as a snapshot.

Me too! No problem to take this as already useful and working result of a first sprint. As written before, I want to visualize some more aspects of the JVB status data to get a impression of the current state and load. I can't estimate at the moment if this gets production quality within the few remaining hours till next release.

**Comment by deleolajide** [comment]
>As written before, I want to visualize some more aspects of the JVB status data to get a impression of the current state and load.

There is the jmx plugin that we can use to do this. All you need is to create some jmx beans and the plugin will do the rest of the work. Might be worth doing that in 1.4.x

https://discourse.igniterealtime.org/t/openfire-jmx-web-console/68735
https://github.com/igniterealtime/openfire-jmxweb-plugin

![image](https://user-images.githubusercontent.com/110731/106354496-20608d80-62ea-11eb-9527-0fbb3f5eb4ff.png)

**Comment by gjaekel** [comment]
> and @gjaekel for the duration idea.

I know about one of the "problems" at developer domain: Less insight of practical usage. Tell me within 3s: Is this bridge running for a long time? You're probably either no able to or a mastermind that will not work as an Openfire admin. :)
![image](https://user-images.githubusercontent.com/19855721/106354377-b6e47d00-62f1-11eb-9364-ef169bf5e563.png)

**Comment by gjaekel** [comment]
> There is the jmx plugin that we can use to do this.

I already do so! But most the target audience of OpenFire/OpenMeet/Pade will not. I don't tend to implement something "big", but just a better "visualisation" of the ongoing conferences, the conference size distribution, the number of audio and video channesl, the JVB stress and maybe the RX/TX rate. Not as graph with history, but just as easy perceptible numbers.

**Comment by deleolajide** [comment]
>Not as graph with history, but just as easy perceptible numbers.

Then expose those numbers as jmx beans so that advanced/admin users like you can see them in a dashboard like hawt.io and  we can also show them in simple tables or graphs directly from pade plugin.
