### ISSUE TITLE
Cannot create a new user via Padé Login

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#240]
Versions OF 4.6.1 + Padé 1.3.1

I already had this issue on previous version that what fix with enabling websocket for Padé. I try again but no succes
Cannot retrieve form

![screenshot159](https://user-images.githubusercontent.com/29485972/106824670-9d418d80-6683-11eb-9041-e9cd617af4a9.png)

Any hint ?

Site https://www.free-solutions.org is now with Padé 1.3.1 , feel free to use & test

Congrats @deleolajide @gjaekel @guusdk  and all other performers, contributors, users to this project I use and run it since 7 years now. Every one is bringing a lot contributing here. Theses apps are extremely useful in the current pandemic situation. I just hope we will drain more attention funding and projects

**Comment by deleolajide** [comment]
There is an outstanding issue when trying to use XMPP in-band user registration with Converse and Openfire when websockets is enabled. Use BOSH until the issue is fixed.
