### ISSUE TITLE
Bug: Volume Control slider in Participant Window disappears

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#244]
Inside the three-dots-menu of a participant windows, there's a slider to control the individual audio volume of a participant.

If it is pulled left at to the zero position, the volume control widget disapper. There's no other way to get it back (and to listen to the corresponding participant again) as to reload.

To my memories, this is an regression bug.

**Comment by gjaekel** [comment]
I wonder if this is a double use of the volume value and the visible state (`enable := (vol >0)`.

@cool0707 Are you able to locate this inside `application_bundle.min.js`? Then, we may push it upstream with a fix.

**Comment by gjaekel** [comment]
Also raised upstream as https://github.com/jitsi/jitsi-meet/issues/8577

Component is https://github.com/jitsi/jitsi-meet/blob/master/react/features/remote-video-menu/components/web/VolumeSlider.js

Maybe this is due to a change in the render library.

**Comment by gjaekel** [comment]
Has been fixed upstream by https://github.com/jitsi/jitsi-meet/pull/8587

**Comment by gjaekel** [comment]
Should we cherry-pick this patch before next upstream pull of sources for Jitsi Meet?

**Comment by deleolajide** [comment]
At the monent, I don't have the time to patch Jitsi-Meet frequently. I wait for stable release notifications.
