### ISSUE TITLE
Local Session Duration vanished

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#245]
I recently noticed that the display of the duration since start of join to a meeting has vanished? It was located at the bottom-left area of the screen.

Did I just miss an option to enable it or is this an regression-issue?

**Comment by deleolajide** [comment]
Only shows when local recording is enabled

![image](https://user-images.githubusercontent.com/110731/107149704-09591580-6952-11eb-83c9-b0a1536d3dd3.png)

**Comment by gjaekel** [comment]
I see! I had disabled that feature to follow privacy policies. Maybe there's a way to decouple this.

**Comment by gjaekel** [comment]
OK to close. Will put this on my to-do list.
