### ISSUE TITLE
Some date-time languages are missing

### ISSUE THREAD

**Issue by cool0707** [igniterealtime/openfire-pade-plugin#256]
The localization of some of the date time languages that we added to `app.bundle.min.js` before is missing (probably due to the merging process when we upgraded Jiti Meet).
I'm trying to submit a PR to upstream, but it's going to be hard to get it approved and merged, so I'll submit the PR here for now.

**Comment by gjaekel** [comment]
> I'm trying to submit a PR to upstream, but it's going to be hard to get it approved and merged, so I'll submit the PR here for now.

I'm already approved. In the early months of 2020, I fail to push something upstream. This seems to be happen just because the whole project team was overloaded. But recently, I did it again and it was processed within a few days (by "the"  @damencho).

I may handle the pull request for you, if you like.

**Comment by cool0707** [comment]
I thought the PR of upsteram would simply be to add unsupported languages, but I needed to make Moment.js the latest version to add Moldovan.
However, when I update Moment.js to the latest version, the size of the build webpack exceeds the size and an error occurs.
In order to reduce the size, I need to introduce a plugin that removes languages not used by Moment.js from webpack, but for this, I need to build and test environment to work on it.
I don't have a lot of time right now, so I will make these changes when I have more time and then submit the PR again.

Please give me a review when you do.

**Comment by gjaekel** [comment]
I wonder if this size is just and arbitrary limit that is defined somewhere.
