### ISSUE TITLE
Some cameras seem to appear black on the left and right.

### ISSUE THREAD

**Issue by naive924** [igniterealtime/openfire-pade-plugin#260]
The code [here](https://github.com/igniterealtime/openfire-pade-plugin/blob/master/web/src/main/webapp/custom_ofmeet.js#L528) in custom_ofmeet.js seems to be the cause.
This problem can be avoided by moving mediaDevices.getUserMedia just before it is executed (startMeetingRecorder / startDesktopRecorder).

Steps to reproduce:
	1. Join meeting with config.startWithVideoMuted=true.
	2. Turn on the camera later.

![image](https://user-images.githubusercontent.com/6185430/109405718-bbff1f80-79b6-11eb-8698-532e650c9d30.png)

**Comment by gjaekel** [comment]
I strongly can confirm the issue, because at our institute we use `config.startWithVideoMuted=true` and in most of the cases, there video stream is initialized with a 4:3 format. Turning video off and on again helps in most cases.

**Comment by naive924** [comment]
Hi @deleolajide 
Thank you for quick response! I confirmed that it has been resolved.
![image](https://user-images.githubusercontent.com/6185430/109421514-02866580-7a1b-11eb-9bfc-eaffdeecac8b.png)
