### ISSUE TITLE
Video mute switching does not work correctly in Version 1.3.2

### ISSUE THREAD

**Issue by cool0707** [igniterealtime/openfire-pade-plugin#263]
In version 1.3.2 on Windows, when I try to mute the video, the screen only goes black and the avatar does not appear.
Also, the camera icon does not switch.
This problem did not occur in version 1.3.0.

**Comment by deleolajide** [comment]
![image](https://user-images.githubusercontent.com/110731/110200727-374d4f00-7e57-11eb-9432-ecf89dfbf2d7.png)

**Comment by deleolajide** [comment]
Only happens when recording is enabled. It was cause by me moving the getMedia code to the button press event to fix [the issue withe starting the meeting muted](https://github.com/igniterealtime/openfire-pade-plugin/issues/260). Sorry about that.
