### ISSUE TITLE
Regression: Count of Raised Hand broken

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#264]
IMHO, the counter for raised hand is broken: Instead of the expected behavior, currently I observe the following:
* If the hand is raised, **each** toggling of audio mute count up the sum of raised hands
* If the hand is lowered, **each** toggling of audio mute count it down

From that the calculated "sum" and "percentage" is far way from expectation.

Note: To my knowledge, a designed actual behavior is that a raised hand is automatically lowered by unmuting, if it was raised while audio was muted. Maybe this was a change and is related to the issue here.

**Comment by cool0707** [comment]
Try changing the way you count the hands raised.
For now I'll send a PR.
