### ISSUE TITLE
Breakout Rooms: Two UI bugs and Double-Join of Breakout Room

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#266]
On the event of returning from breakout rooms the participants displayed at the origin room panel may have a wrong identity, i.e. appear as the wrong participant

Before breakout:
![image](https://user-images.githubusercontent.com/19855721/110246917-e37f5a80-7f69-11eb-8702-b3b93d01bb4c.png)

After rejoin:
![image](https://user-images.githubusercontent.com/19855721/110246813-6bb13000-7f69-11eb-911e-b6f3c8999f88.png)

In addition, on the breakout event, each participant is joined **twice times** to the breakout room. One may only get notice of this, if there no auto-login with stored credentials! After first join, a popup will tell that you will be joined to the breaktout room withing 10secs. This will happens as annouced.

**Comment by gjaekel** [comment]
I also want to rise a feature request: With the action of sending the distributed participans to the allocated breakout rooms, they should not disappear from the panel but become "greyed out" to have a reference of the distribution during the ongoing breakout period.

**Comment by cool0707** [comment]
This bug is not reproduced in my environment.
Do the participants who have the same name use the same user ID in Openfire?

**Comment by gjaekel** [comment]
Thank you for support!
I was using three different accounts (my own, _foo_ and _bar_) and three tabs on the same client.
_I'll do a fresh re-check_

**Comment by gjaekel** [comment]
Just discovered a different **bug**: I pressed [Breakout] by accident without populating the _Room1_ again. The state changed to a greyed-out [Reassemble]. It's unrecoverable, even by close and re-open.
![image](https://user-images.githubusercontent.com/19855721/112433500-a45f5080-8d42-11eb-9b6f-47034da92972.png)

**Comment by gjaekel** [comment]
A **2nd bug**: No by the scroll buttons, but one may *enter* a value of 0 (or even negative) as the number of rooms. If it's null, an "ghost room" will appear "before" the current (named _Meeting Participants_) and the internal logic will get screwed.

![image](https://user-images.githubusercontent.com/19855721/112435691-5c8df880-8d45-11eb-815c-9abe0bf22028.png)

**Comment by gjaekel** [comment]
The double-login isn't notable if the password is stored. Maybe it's not a real re-join but just a re-trigger of authorisation.
