### ISSUE TITLE
Server Side Meeting Recording.

### ISSUE THREAD

**Issue by 0bhat** [igniterealtime/openfire-pade-plugin#271]
Is there any way we can achieve server side meeting recording apart from the front-end recording we have right now.
The goal is save all the meeting recordings at the server.

**Comment by deleolajide** [comment]
Yes. [Using ffmpeg as I did for live streaming to you-tube](https://github.com/igniterealtime/openfire-pade-plugin/discussions/262).  Instead of sending the stream to an RTMP server, it is written directly to disk as FLV or MP4 file.

**Comment by deleolajide** [comment]
You can test it without modification to create FLV file. Just put a file path name in the RTMP URL and a subfolder name in the stream key

![image](https://user-images.githubusercontent.com/110731/110972553-050a8880-8354-11eb-9948-9d48a5c16412.png)

**Comment by 0bhat** [comment]
any way to turn it on by default for all the meetings?

**Comment by deleolajide** [comment]
Not that I aware of
