### ISSUE TITLE
Media traffic over TCP 

### ISSUE THREAD

**Issue by riess82** [igniterealtime/openfire-pade-plugin#273]
The 2 port settings "Port Number" and "Mapped Port Number" are stored in the config, but not read back correctly.
The fields always display 4443 instead of the values from the config.

**Comment by deleolajide** [comment]
Thank you for reporting this 👍

**Comment by gjaekel** [comment]
@deleolajide We lost this while fighting with the different meaning of _public_ and _private_ in the domain of OpenFire and the Jitsi Video bridge: The JVB uses this unfortunately for the WebRTC and the REST-API.
