### ISSUE TITLE
no log out choice

### ISSUE THREAD

**Issue by swbus** [igniterealtime/openfire-pade-plugin#29]
great project!
but, there no logout button

**Comment by deleolajide** [comment]
Logout happens automatically when you close the web page and break the XMPP connection.

**Comment by swbus** [comment]
mmm...
How to log in with another account?

**Comment by deleolajide** [comment]
You can't. It is not a web site. It is a communication application for users of the same domain (organisation).  You can only have one account for each desktop in the same domain. You are auto-logged in when you start your desktop and remain logged in until you shut-down.

**Comment by swbus** [comment]
It's not a good idea

**Comment by deleolajide** [comment]
> It's not a good idea

I am sorry it is not a good idea for you.
