### ISSUE TITLE
The video / audio conference cannot be cancelled

### ISSUE THREAD

**Issue by swbus** [igniterealtime/openfire-pade-plugin#30]
The video / audio conference cannot be cancelled.
If you create a conference, how to end the conference before entering the username and password?

**Comment by gjaekel** [comment]
"conference rooms" will be managed by the technical user named "focus". They will be usually created on request an released if the last person will leave the room. A room might be "pinned" by help of XMPP features, e.g. by the XMPP administrator. This will be useful to persist the optional additional room password.

**Comment by swbus** [comment]
Select a contact, click the video and audio conference, and then prompt me whether to create, select OK, switch to the video window, wait for the user name and password, if you do not want to continue the meeting at this time? Can't return to the previous text conversation page.
How to do?
