### ISSUE TITLE
Config for showing Dial-In numbers on the frontend.

### ISSUE THREAD

**Issue by 0bhat** [igniterealtime/openfire-pade-plugin#307]
Reading this guide on how to get dial in numbers and PIN shown on the frontend.
https://community.jitsi.org/t/working-configuration-for-jitsi-jigasi-with-asterisk-sip/53039

How can we add the following two keys to the config?
1) "dialInNumbersUrl"
2) "dialInConfCodeUrl"

**Comment by deleolajide** [comment]
Can you please stop asking questions in issues section instead of the discussion section.
