### ISSUE TITLE
JVB user can't login if using LDAP with GSSAPI enabled

### ISSUE THREAD

**Issue by billroland** [igniterealtime/openfire-pade-plugin#308]
This is a continuation of issue #112 that was closed.

https://github.com/igniterealtime/openfire-pade-plugin/issues/112#issuecomment-736875650 

It took a while but I got around to troubleshooting this some more and I can confirm the above user's observations.  If I disable GSSAPI on Openfire, the JVB user can login immediately.  If I re-enable it, the JVB user is once again unable to login (but stays logged in if already logged in).  

I use GSSAPI for Spark clients in my environment so this is a killer.  The workaround works but certainly not ideal.

**Comment by deleolajide** [comment]
> It took a while but I got around to troubleshooting this some more and I can confirm the above user's observations

Thank you for the effort and information. 

![image](https://user-images.githubusercontent.com/110731/114299457-4016ed80-9ab3-11eb-8039-3cd6831d02c0.png)


Adding suuport for SSO (single sign on) with Kerberos V5 authentication using GSSAPI has to be done upstream to Jicofo by the JItsi team and wont be a trivial task. I will take a look to see if there are any configuration options.

**Comment by deleolajide** [comment]
This should be fixed in new version of Jicofo

https://github.com/jitsi/jicofo/blob/87b2ec600faa9d3795a5a9d1bc2a266d306f8ae7/src/main/java/org/jitsi/impl/protocol/xmpp/XmppProviderImpl.java#L155

**Comment by Sotneo** [comment]
Is it already merged to plugin? Still experiencing this issue
