### ISSUE TITLE
IP Address Mapping display disagrees with configuration

### ISSUE THREAD

**Issue by lochner** [igniterealtime/openfire-pade-plugin#310]
With version 1.3.3, the _Pade > Networking > IP Address Mapping_ display no longer agrees with the configured setting.&nbsp; It always shows _Automatic_, even with the org.jitsi.videobridge.media.AWS_HARVESTER system property set to "disabled".

Inspection points to the apparent cause:

In /src/java/org/jitsi/videobridge/openfire/PluginImpl.java,
&nbsp;&nbsp;&nbsp;&nbsp;org.jitsi.videobridge.media.AWS_HARVESTER
is mapped to these properties:
&nbsp;&nbsp;&nbsp;&nbsp;org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER
&nbsp;&nbsp;&nbsp;&nbsp;org.ice4j.ice.harvest.FORCE_AWS_HARVESTER

However, in /src/web/jitsi-videobridge.jsp, the associated radio button states are mapped
via /src/java/org/jitsi/videobridge/openfire/RuntimeConfiguration.java from these properties:
&nbsp;&nbsp;&nbsp;&nbsp;org.jitsi.videobridge.DISABLE_AWS_HARVESTER
&nbsp;&nbsp;&nbsp;&nbsp;org.jitsi.videobridge.FORCE_AWS_HARVESTER

**Comment by deleolajide** [comment]
Thanks for spotting this 👍

**Comment by gjaekel** [comment]
Seems to be appear wrong just one time:
```
root@evalfire0 .../git/openfire-pade-plugin-master # grep "DISABLE_AWS_HARVESTER" -r * | grep -v "org\.ice4j\.ice\.harvest"
src/java/org/jitsi/videobridge/openfire/RuntimeConfiguration.java:        final boolean disabled = StackProperties.getBoolean( "org.jitsi.videobridge.DISABLE_AWS_HARVESTER", false );
```

**Comment by gjaekel** [comment]
@lochner If it's urgent for you, we may provide a snapshot build.

**Comment by deleolajide** [comment]
> @lochner If it's urgent for you, we may provide a snapshot build.

The latestest snapshots are automatically built by GitHub Actions and can be found at http://igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=pade

**Comment by deleolajide** [comment]
The snapshot build after this fix is http://igniterealtime.org/projects/openfire/plugins/1.3.4-SNAPSHOT/pade.jar?snapshot=20210413.075814-13
