### ISSUE TITLE
Jitsi Web Client Upstream Stable Release 2.0.5765

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#313]
@cool0707 @deleolajide: Here a screenshot of the new UI, taken from http://meet.jit.si

![image](https://user-images.githubusercontent.com/19855721/115041157-7fd63e80-9ed2-11eb-9b8f-9de5f5a2d9c6.png)

* The button bar have changed a lot. We have to re-design our additions.
* There's an audio level animation around the avatar circle. 
* In the participants window 3-dot menu, there's a new disable own and all others Cam like for the Mic before
* In the own 3-dot menu, there's now a entry to toggle the local-X-Flip feature by GUI. (This is great if you use an external virtual cam to provide something with text. Because the local video is X-flipped by default to provide the used view into a mirror. If you stamp in some text into your own video, you can't read it without disabling the X-flip :smile: )

Most other of the UI seems unchanged.

A big new thing not visible here: There's a build-in auto-background-screening! This feature is selectable on the prejoin page, but I can't find a control inside the conference yet,

**Comment by deleolajide** [comment]
> * The button bar have changed a lot. We have to re-design our additions.

That is why I don't like making modifications to the UI unless I have no choice ;-)

**Comment by Gauravclaytech** [comment]
> A big new thing not visible here: There's a build-in auto-background-screening! This feature is selectable on the prejoin page, but I can't find a control inside the conference yet,

![image](https://user-images.githubusercontent.com/44634254/115052175-4239db80-9efb-11eb-9cdc-f5e8c80bb094.png)

I think background change option is visible inside the meeting when your cam is turned on.

**Comment by 0bhat** [comment]
> A big new thing not visible here: There's a build-in auto-background-screening! This feature is selectable on the prejoin page, but I can't find a control inside the conference yet,

![image](https://user-images.githubusercontent.com/10598279/115052363-7ad9b500-9efb-11eb-92dc-adec1346c2c3.png)

The change-background option is enabled only when your cam is turned on.

>That is why I don't like making modifications to the UI unless I have no choice ;-)
I think if we stuff all the buttons in the 3-dot menu it will be too big now.

**Comment by gjaekel** [comment]
> I think if we stuff all the buttons in the 3-dot menu it will be too big now.
Of course! I think we should add-in our feature icons leftside the three dots menue.

**Comment by deleolajide** [comment]
I have created branch 1.3.4 which will be released at the end of the month unless 1.4.0 (master) is ready.  Feel free to start working on PRs to master for Jitsi Stable Release 2.0.5765

**Comment by gjaekel** [comment]
... and the build finished with green lights :smile:

BTW: There some snapshots tagged by mistake.with "1.4.0" in the Plugin archive (https://igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=pade). May your remove this?

**Comment by deleolajide** [comment]
> May your remove this?

I don't know how to do this. May be @akrherz knows 👍

**Comment by akrherz** [comment]
> May be @akrherz knows

Sure, I removed the 1.4.0-SNAPSHOT artifacts from disk and that appeared to work.

**Comment by cool0707** [comment]
> * In the own 3-dot menu, there's now a entry to toggle the local-X-Flip feature by GUI.

You can flip local video by right-clicking on it in the current version.
![image](https://user-images.githubusercontent.com/3506430/115131632-8381d680-a034-11eb-9486-2941ef2c937f.png)

**Comment by gjaekel** [comment]
> You can flip local video by right-clicking on it in the current version.

Another hidden :gem: :smile:

**Comment by deleolajide** [comment]
[First attempt](https://github.com/igniterealtime/openfire-pade-plugin/commit/219ddb5c312432773402fa57ade3fba148a6d4b7) at upgrade

Upgrading jvb to Stable Release 2.0.5765 is ok

Upgrading Jicofo to Stable Release 2.0.5765 is going to require a bit of work as [focus component has been replaced](https://github.com/jitsi/jitsi-meet/commit/b6f7f8fba7ba81c5a0ab5477a1d103b7279bf38f#diff-34657c6f2aadb153c5601cb654648eddd5b9629f6c833661b981e2f6159ef54f) with the [Prosody client_proxy module](https://modules.prosody.im/mod_client_proxy.html)

We would have to implement the same in Java for Openfire. Until that can be done, we will stay with the current release/version

Upgrading Jitsi to Meet Stable Release 2.0.5765 has been done, but I willl need @cool0707 assistance to modify addToolbarItem to work with the new UI and confirm that my modifications to lib-jitsi-meet.min.js and app.bundle.min.js are ok

![image](https://user-images.githubusercontent.com/110731/115972051-1befed80-a544-11eb-92f0-39e042124db5.png)

**Comment by gjaekel** [comment]
You're looking good! Where is the location in the background?

**Comment by gjaekel** [comment]
> We would have to implement the same in Java for Openfire. Until that can be done, we will stay with the current release/version.

Are there any functional gaps as the result of holding back the new version?

**Comment by deleolajide** [comment]
>Are there any functional gaps as the result of holding back the new version?

we will find out out soon enough ;-)

**Comment by deleolajide** [comment]
We are looking very good. @cool0707 thank you so much for all the bug fixes and making ofmeet compatible with new Jitsi UI.

![image](https://user-images.githubusercontent.com/110731/116073588-8742d800-a688-11eb-88ec-45104d05f02f.png)

**Comment by gjaekel** [comment]
First screenshot from evaluation stage.
![image](https://user-images.githubusercontent.com/19855721/116118967-2df59b80-a6be-11eb-9d35-ab7f204c47c4.png)
