### ISSUE TITLE
"Cache user password" does not work in chrome / electron app

### ISSUE THREAD

**Issue by stylefish** [igniterealtime/openfire-pade-plugin#314]
Hi,

first of all: thanks for a great jitsi plugin, i really love pade! :)

i'm having an issue where the user password does not get stored anymore, it always asks for username and password, when `xmpp_password_override` and `xmpp_username_override` are not already present in the localstorage (e.g. a new user or clearing site data).

problem is: i dont know since when because most of the time the users cache does not get deleted.

this is reproducible with chrome! any suggestion would be appreciated! :)

greetings & thanks

**Comment by gjaekel** [comment]
Password storage have move to the browsers credentials API. You have to allow to store the password for the site. In Crome, you may use a key icon on the right end or the URL entry slot. Via this dialog, you also may reach the Password Manager. Here, you have to allow to "Offer to save passwords" and also "Auto Sign-in", if you like.

**Comment by gjaekel** [comment]
Sorry, do you use V1.3.3 final release? There was a bug concerning the use of both storages. It is already fixed in the branch v1.3.4 (see #305), you may use a 1.3.4-SNAPSHOT build from https://igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=pade

**Comment by stylefish** [comment]
Great! Thanks for the quick answers! I will try the snapshot thing tomorrow and report back :)

**Comment by stylefish** [comment]
ok, i just updated to 1.3.4-SNAPSHOT and the issue is fixed, thanks a lot! :)

**Comment by stylefish** [comment]
ok, i works when i save my password in chrome and enable the "auto-login" in chrome.
we use it in an electron app (rocket.chat) though where i can't enable this, so i talked to @gjaekel about this and he came up with a solution, i will create a PR for his solution :)
