### ISSUE TITLE
Upgrading Jicofo to Stable Release 2.0.5765

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#317]
Upgrading Jicofo to Stable Release 2.0.5765 is going to require a bit of work as [focus component has been replaced](https://github.com/jitsi/jitsi-meet/commit/b6f7f8fba7ba81c5a0ab5477a1d103b7279bf38f#diff-34657c6f2aadb153c5601cb654648eddd5b9629f6c833661b981e2f6159ef54f) with the [Prosody client_proxy module](https://modules.prosody.im/mod_client_proxy.html)

**Comment by gjaekel** [comment]
Really replaced? Or is this just some kind of proxy with another type of XMPP negotiation? Or to allow more than one JiCoFo instance to run?

**Comment by deleolajide** [comment]
> Really replaced?

https://github.com/jitsi/jitsi-meet/pull/8381

**Comment by gjaekel** [comment]
Damn! Should we 
* fork JiCoFo and try to implement functional changes in Java based on this?
* run LUA on Java (https://github.com/luaj/luaj ?)

**Comment by deleolajide** [comment]
None of the above 👎 

Jitsi-Meet still thinks it is talking to an XMPP component, so we give it an XMPP component 👍

**Comment by gjaekel** [comment]
> an XMPP component

... written in?

**Comment by damencho** [comment]
You can just use the xmpp user connection full jid and set it in config.js and that should be enough jicofo to receives its messages, maybe you will need to adjust the authorized regexp if you are getting some forbidden messages.

**Comment by deleolajide** [comment]
>You can just use the xmpp user connection full jid and set it in config.js

I did that, but Openfire was sending a service unavailable mesage. Thanks @damencho for the hint  to transform the xmpp stanza 👍

**Comment by deleolajide** [comment]
I suspect Openfire want s full JID with resource. The client does not know this. I may have to provide a dummy component that modifies the stanza destination to the full JID using Openfire server session APIs

**Comment by gjaekel** [comment]
So this is not about JiCoFo but about the "XMPP pseudo user/bot" acting with the name "focus"?

**Comment by damencho** [comment]
> I suspect Openfire wants the full JID with resource. The client does not know this. I may have to provide a dummy component that modifies the stanza destination to the full JID using Openfire server session APIs

Wait, I thought you said you are providing the full jid already as I purposed?

**Comment by damencho** [comment]
Here https://github.com/jitsi/jitsi-meet/blob/f377455069ff7ae41963864a61b87d988f5bd5bf/config.js#L18 instead of focus address, provide jicofo's full jid with resource, is this what you are trying?

**Comment by deleolajide** [comment]
> instead of focus address, provide jicofo's full jid with resource, is this what you are trying?

Yes. However, jicofo user is not on the user roster, so I don't knw the full jicofo JID only the bareJID and that is being rejected by Openfire for IQ set

**Comment by damencho** [comment]
Can't you get the jicofo's full jid programmatically ... ? Another option is to add a config in jicofo to specify a resource, so it's always the same and that's what you put in the config.js ...

**Comment by deleolajide** [comment]
> Another option is to add a config in jicofo to specify a resource, so it's always the same and that's what you put in the config.js

👍

**Comment by deleolajide** [comment]
> Can't you get the jicofo's full jid programmatically

Not without using presence stanzas. Also, in openfire anonymous users are not limited routing permissions. The dummy focus.my_domain component is supposed to perform that function by directly accessing Openfire session APIs to get the jicofo full JID
