### ISSUE TITLE
Jitsi Meet stops working with Openfire 4.6.3

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#319]
See https://discourse.igniterealtime.org/t/openfire-pade-version-1-3-3-released/89946/2

When a 3rd+ user joins a room, it causes all users to disconnect. The end result is all 3+ users resolve to “isolated” rooms where they cannot “see” each other. To reiterate, the plugin does not crash - it just causes all users to disconnect from each other.

I am currently using Openfire 4.6.3

**Comment by gjaekel** [comment]
:1:
