### ISSUE TITLE
Auto-Clear Message Captions of Chat Messages on Main Screen 

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#322]
If Message Captions are enabled, each last chat message stays on main screen until replaced by the next one.

While an ongoing presentation, this might impact the readability of the sheets.

Introduce an configurable (idle) timeout that will auto-clear the "last message overlay" after a while.

**Comment by deleolajide** [comment]
Fixed by this - https://github.com/igniterealtime/openfire-pade-plugin/pull/336
