### ISSUE TITLE
Emoji showing blank spaces

### ISSUE THREAD

**Issue by chagai95** [igniterealtime/openfire-pade-plugin#327]
![image](https://user-images.githubusercontent.com/31655082/116795396-dfd50380-aad4-11eb-898c-44964f716c03.png)

**Comment by deleolajide** [comment]
I can't reproduce this. It could be your browser cache

**Comment by gjaekel** [comment]
@chagai95 faced this issue on my installation. It's probably an UTF-8 issue at my platform, concerning the database or something like that. I'll investigate this by defining the Emoji-Set on the config_custom.js

**Comment by deleolajide** [comment]
I can't reproduce this. Closing for now
