### ISSUE TITLE
Transcription not working anymore properly

### ISSUE THREAD

**Issue by chagai95** [igniterealtime/openfire-pade-plugin#328]
Was working sometimes and that only from one user.

was trying with Chrome where it worked and with Edge where it worked less from another user and from Chrome it did not work at all from another user

**Comment by chagai95** [comment]
![image](https://user-images.githubusercontent.com/31655082/116795550-270fc400-aad6-11eb-826c-ab4a49551266.png)

I think it was not sending the messages as if they came from the user using Chrome even though Chrome was muted the whole time

**Comment by deleolajide** [comment]
I can't reproduce this issue. I think it is fixed. Please re-open if not so

![image](https://user-images.githubusercontent.com/110731/119237803-a83b0380-bb36-11eb-8fab-ca33868bc47a.png)

**Comment by gjaekel** [comment]
It works for some participants, but not for all. It might be related to some local network or browser conditions. Here, it don't work. That's the reason for my recent patch (to prevent continouos retries)

**Comment by deleolajide** [comment]
> I googled something about this Google service requires a API key and if used without, it's also limited in use.

Exactly. It is metered and throttled by domain name. API key needed for a paid premium service
