### ISSUE TITLE
Padé 1.40 Jitsi meet room on android incorrect menu formatting

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#329]
Only on mobile,

New Jitsi menu with chrome on android larger

![scpade140android](https://user-images.githubusercontent.com/29485972/116824778-3e10ed80-ab8c-11eb-8319-d8ba4ae5a5b8.jpg)

**Comment by deleolajide** [comment]
I noticed that. I am hoping @cool0707 may be working on it already 👍

**Comment by ClaudeStabile** [comment]
Cool, @cool0707 , @deleolajide  !!!! Thank you in advance for all these efforts :)

**Comment by deleolajide** [comment]
Can you please re-test. I am unable to reproduce with latest 1.4.1-snapshot

<img width=50% src=https://user-images.githubusercontent.com/110731/119237591-88efa680-bb35-11eb-94b3-f376cc85c446.png>

**Comment by ClaudeStabile** [comment]
@deleolajide Still not OKI on my mobile, i have deployed it on https://www.free-solutions.org so anyone can try out 
I do not find any regression so i let version ON :)

**Comment by gjaekel** [comment]
On my _Xiaomi Redmi 4X_ using _Google Chrome_, it also shows the icons right of "Invite Person" just in Landscape Mode, but not in Portrait Mode. I have to full zoom out in both cases.

**Comment by ClaudeStabile** [comment]
On my android only i have now Chat/Screenshare buttons missing in the bar. When using via a browser on PC i get the bar menu complete
you can try out with android mobile at https://www.free-solutions.org

see this screenshot

![menubarmissingitemsonandroid](https://user-images.githubusercontent.com/29485972/119275855-b4e35880-bc17-11eb-9f9f-e419408a8cb3.jpg)

Can you pls check, still prob with this menu bar

Thx in adv for all efforts done

**Comment by ClaudeStabile** [comment]
@deleolajide 

you can close this one, with latest code compile, menu bar looks fine on my android mobile

++
