### ISSUE TITLE
Padé 1.40 Video double encryption does not work, audio works

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#330]
While testing 1.40,

When enable, no video is received only audio when double encryption is activated with 1.40 version. With chrome latest version. This was OKI with version 1.3x

Hope this helps

**Comment by deleolajide** [comment]
Thank you. It helps. It is because we are not yet using latest Jicofo code. See issue #317

**Comment by deleolajide** [comment]
Can you please re-test with latest 1.4.1-snapshot from here - https://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=pade

**Comment by ClaudeStabile** [comment]
@deleolajide I have deployed it on https://www.free-solutions.org, seem to work fine but i need to do more tests
Thanks a lot for fixing that

**Comment by ClaudeStabile** [comment]
@deleolajide After doing more tests, it does not work, still no video enc/decrypted. I am running 1.4.1 at https://www.free-solutions.org if you want to try out. Hope this helps

++ Excellent WE :)

**Comment by deleolajide** [comment]
@ClaudeStabile Is this still an issue? Can I close?

**Comment by ClaudeStabile** [comment]
@deleolajide  I have tested double encryption, it works fine with chrome and on Android, tested and validated. It does not work with Firefox. That's what i have tested so far. Latest version 1.6.2 worky nicely, so you can close this one
