### ISSUE TITLE
Padé 1.40 Phone Calls from a Jitsi room, cannot call 

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#333]
Hello,

I have found the following issue with version 1.40, this use to work in 1.3.x
SipCall is enabled
![PadéSIPCalls](https://user-images.githubusercontent.com/29485972/117271713-c0363600-ae5a-11eb-976c-ce8028c813c5.png)

You need to have a SIP Gateway configured to do this.

Thanks in advance for help & efforts

Congrats to all dev for Padé v 1.4.0

**Comment by deleolajide** [comment]
Issue is now fixed with latest jicofo code. See https://github.com/igniterealtime/openfire-pade-plugin/issues/317
