### ISSUE TITLE
Implement counting "show of hands"

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#34]
In large meetings with 50+ participants, the grid-view starts to scroll off the screen and it is not possible to see all hands raised.

Implement a simple polling system that counts the hands raised and shows it on screen as a caption/subtitled. Ensure it is also recorded with all other sub-titles/captions when the conference is recorded.

**Comment by gjaekel** [comment]
+1 !
It would be even better to have some additional choices of soundless feedback -- like I have seen in other meeting apps. This might be added to the GUI by an additional popup panel like at the mic/video button.
The other app offer the feedback [yes/positive {green}], [no/negative {red}], [faster], [slower] and the "moods" [happy], [unhappy], [angry], [confused] in a 2x4 table. There, the feedback was cleared by a timer after about 15s. But this was not convenient for elections.

**Comment by gjaekel** [comment]
Did a quick test. Please reopen, because there was a miscounting (counter to high) at the moderators windows - probably I close a participients tab while the hand was raised.

**Comment by gjaekel** [comment]
Implemented by #42.
