### ISSUE TITLE
Make the toolbar on mobile (browser) only have a few options and scrollable/swipable for more

### ISSUE THREAD

**Issue by chagai95** [igniterealtime/openfire-pade-plugin#340]
Feature request
On mobile it's pretty difficult to touch the arrows next to some options so this will allow making everything bigger.

**Comment by gjaekel** [comment]
In the element tree, the corresponding arrow icon is represented by
```
<svg fill="none" height="9" width="9" viewBox="0 0 10 7"><path clip-rule="evenodd" d="M8.411 6.057A.833.833 0 109.65 4.943L5.73.563a.833.833 0 00-1.24 0L.63 4.943a.833.833 0 001.24 1.114l3.24-3.691L8.41 6.057z"></path></svg>
```
If we're able to tune the width and height a bit, the job will be done:
```
<svg fill="none" height="14" width="14" viewBox="0 0 10 7"><path clip-rule="evenodd" d="M8.411 6.057A.833.833 0 109.65 4.943L5.73.563a.833.833 0 00-1.24 0L.63 4.943a.833.833 0 001.24 1.114l3.24-3.691L8.41 6.057z"></path></svg>
```

![image](https://user-images.githubusercontent.com/19855721/117850158-55836100-b285-11eb-8894-77eb7d94e14d.png)

**Comment by gjaekel** [comment]
BTW: Did you consider to use the _Jitsi Meet_ smartphone application instead?

**Comment by gjaekel** [comment]
I'm no Web developert, but to my knowledge it's possible to switch CSS in dependence to devices. Let's work this out.

**Comment by deleolajide** [comment]
For now, toolbar will be not be extended with mobile browser. Feature can only be use via keyboard shortcut

**Comment by chagai95** [comment]
keyboard shortcut on the mobile?
