### ISSUE TITLE
Jitsi voice transcription to text / Enhancement or do we already have an option to enable it from a Jitsi room ?

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#344]
Is there a way to enable transcription on some specific room only. Or better to enable it after joining a jitsi room. And option within the console would also be a great feature.
Currently if my understanding is correct, if we enable transcrption this is done and activated for all Jitsi conf on the OF server. There is a button to disable it within the conf but ideally i would like to have the contrary, enable transcriptions on the Fly
This is a very expected feature as we can transcribe only slice of conferences or whatever we want.

![screenshot3](https://user-images.githubusercontent.com/29485972/119261058-e5a29e00-bbd5-11eb-8b3d-ef64a7f5d83b.png)

**Comment by gjaekel** [comment]
I also discovered this recenty, and the same holds for "Display Message as Captions": There's no difference between enabling the feature and the initial state - if the feature is enabled, its switchable by the user. But the initial state is also _enabled_. 

I also suggest to have a second option with the initial state.

**Comment by ClaudeStabile** [comment]
@gjaekel Initial state could be great. If we can switch on and off from the Jitsi room, it would be a great enhancement. If we can toggle it on with a special shortcut even greater. You may also need to enable language chooser so transcribing from language you are speaking in that room. ++ Thanks a lot in adv for taking the point

**Comment by gjaekel** [comment]
You already may switch both features via  the Conference Captions Dialog. 

I already add Hotkeys and a Message Autohide, compare to Issue #299/PR #336 and #341

**Comment by deleolajide** [comment]
> Is there a way to enable transcription on some specific room only.

At the moment, not yet. However If you install the rawproperties plugin,
![image](https://user-images.githubusercontent.com/110731/119270012-7a1af980-bbf2-11eb-8c3a-71916299f723.png)

You can add new properties to each MUC room
![image](https://user-images.githubusercontent.com/110731/119270028-974fc800-bbf2-11eb-81e3-aa95c3100152.png)

Pade can then look for a property called **ofmeet.voice transcription** and enable transcription  if the value is true

**Comment by ClaudeStabile** [comment]
@gjaekel 

I tried this hint.
I have created a room named voice2text on my server https://www.free-solutions.org/Voice2Text and added property as suggested 
but still no transcription. No emmergency i was just trying out, i am always curious.

If you can add option within the Jitsi room it will be a huge steps ahead :)

**Comment by deleolajide** [comment]
You can now apply interface_config properties to specific rooms by adding them as MUC room properties.
For example, to enable transcriptions, set OFMEET_ENABLE_TRANSCRIPTION to true.

![image](https://user-images.githubusercontent.com/110731/119412591-0ce79100-bce4-11eb-97da-45a9d57c0a36.png)

**Comment by gjaekel** [comment]
> You can now apply interface_config properties to specific rooms by adding them as MUC room properties.

.. in a generic way, i.e. any properties to any room. Is this expandable to the config properties, too?

**Comment by gjaekel** [comment]
But in spite of that, I should going to add a second configurable properity for the initial state - something like startWithCaptionsEnabled` and `startWithTranscriptionEnabled`, right?

**Comment by deleolajide** [comment]
>Is this expandable to the config properties, too?

Only working with OFMEET interface_config properties. It will require more work to use config. You would have to test to see how it behaves for Jitsi properties. I think it will be too late to take effect.

**Comment by gjaekel** [comment]
It's a smart new thing, anyway! It will allow to setup rooms with different characteristics.

**Comment by ClaudeStabile** [comment]
Congrats @deleolajide for this already a big step ahead :)

I will try this out on one of my server. That's really cool as it open new possibility to differentiate room behaviour.
thanks a lot also @gjaekel for pusshing this and interest  

++ Thanks a lot for efforts

**Comment by ClaudeStabile** [comment]
@deleolajide @gjaekel 
I have installed & compiled latest Padé. I have created a permanent room named voice2text with these variables and IT WORKS !!!
https://www.free-solutions.org/voice2text all other rooms are without transcription !!! YES !!!
That's really a nice addon as we can define some apecific rooms where speach is transcribed
That's already an immense step ++ Congrat to both of you for this hack :)

**Comment by gjaekel** [comment]
@ClaudeStabile: Delé have merged in the GUI changes (Meet Client and Admin UI) some minutes before; you may also have a look at this as soon the snapshot has been build.

**Comment by ClaudeStabile** [comment]
@gjaekel @deleolajide  i did a mvn compile & mv package from Github Repo. I am also testing with android, it looks better, menu bar looks perfect now. So issue #329 is closed for me.
You can try out on https://www.free-solutions.org with android. I will probably build another package(i did it at 5PM), let me know when it make sense. I have tried out room params, works fine, nice addon ! My site is free so it is always a good way to validate and have a quick return with these new features and it benefit to the whole OF community. Thx a lot for pushing this !

**Comment by ClaudeStabile** [comment]
@deleolajide 

I did not manage to make this work again. Is there a possible regression in 1.7.1 ?

Thx

**Comment by deleolajide** [comment]
>I did not manage to make this work again. Is there a possible regression in 1.7.1 ?

Yes. It is now fixed in 1.7.2

**Comment by ClaudeStabile** [comment]
That's super cool @deleolajide thanks i will try out again Thanks !
