### ISSUE TITLE
Expose interface config property TILE_VIEW_MAX_COLUMNS

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#35]
Enable this property to be managed as an Openfire system property and editable in the UI setting s web page.  Remove the maximum limitation in Jitsi Meet to 5 columns.

**Comment by gjaekel** [comment]
It takes more than 20min, but then the browser has opened 31 tabs (with 30 in webinar mode). And the new feature works as expected!

![Screenshot from 2020-05-17 23-29-22](https://user-images.githubusercontent.com/19855721/82160970-56173080-9899-11ea-8dc5-c52a1237d6cf.png)
![Screenshot from 2020-05-17 23-39-57](https://user-images.githubusercontent.com/19855721/82160969-557e9a00-9899-11ea-89f9-5b3764894ade.png)
![Screenshot from 2020-05-17 23-49-01](https://user-images.githubusercontent.com/19855721/82160968-54e60380-9899-11ea-9f90-9c41134b5a91.png)
