### ISSUE TITLE
Pace loving page cannot login a user and just indicates connecting. This goes on forever

### ISSUE THREAD

**Issue by Kellykinyama12** [igniterealtime/openfire-pade-plugin#355]
Pace login just indicates connecting. This goes on forverever

**Comment by deleolajide** [comment]
Try creating an account at https://pade.chat/pade and then confirm you can login. If yu ccan, then there is a problem with your Openfire server and Pade plugin configuration

**Comment by Kellykinyama12** [comment]
my url is https://multinettelecom.com:7443/pade
It says nothing even when I enter wrong credentials

**Comment by deleolajide** [comment]
![image](https://user-images.githubusercontent.com/110731/121772629-6b2ec380-cb6e-11eb-8c6b-69e7dfaf57c2.png)

You configured 5443 instead of 7443

**Comment by Kellykinyama12** [comment]
Thanks you very much. I reconfigured to port 7443 and it's now working.

**Comment by Kellykinyama12** [comment]
I reconfigured the port.
