### ISSUE TITLE
Jicofo No Longer Connects - 1.4.1 - Missing SSL Support

### ISSUE THREAD

**Issue by droobah** [igniterealtime/openfire-pade-plugin#358]
When upgrading to version 1.4.1, it apperas Jicofo no longer works when SSL is required by the server on port 5222.

```
org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - Aug 04, 2021 9:53:29 PM org.jitsi.utils.logging2.LoggerImpl log
org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - SEVERE: Failed to connect/login: SSL/TLS required by server but disabled in client
org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper - org.jivesoftware.smack.SmackException$SecurityRequiredByServerException: SSL/TLS required by server but disabled in client
org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -  at org.jivesoftware.smack.tcp.XMPPTCPConnection.afterFeaturesReceived(XMPPTCPConnection.java:948)
org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -  at org.jivesoftware.smack.AbstractXMPPConnection.parseFeatures(AbstractXMPPConnection.java:1514)
org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -  at org.jivesoftware.smack.tcp.XMPPTCPConnection.access$1100(XMPPTCPConnection.java:151)
org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -  at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1066)
org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -  at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -  at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -  at java.lang.Thread.run(Thread.java:748)
org.jivesoftware.openfire.plugin.ofmeet.JitsiJicofoWrapper -
```

**Comment by gjaekel** [comment]
Dear @droobah,
may you please provide a full "clean" log of the whole startup, i.e. after stopping OpenFire, rotate the `all.log`. 

To my knowledge, *JiCoFo* should connect as External Component to OpenFire on Port 5275. Please provide you servers configuration on _Server|Server Settings|External Connections Settings_ setting on `.../External Component Settings `. And compare also to https://github.com/igniterealtime/openfire-pade-plugin/wiki/OFmeet-Network-Scheme .

**Comment by droobah** [comment]
Sure.  I've attached the log requested.  If I have port 5222 set to require TLS, the JiCoFo status never turns 'green'.  As soon as I make it optional, it works properly.  I had upgraded from 1.4.0 to 1.4.1 of the Pade plugin.

[all.log](https://github.com/igniterealtime/openfire-pade-plugin/files/6940176/all.log)

**Comment by gjaekel** [comment]
I confirm this as a bug! The logs tell about a `port=5275` in the commandline of the _JiCoFo_-JVM. But also in my installation, the JVM connects to `5222`! I wasn't aware of this yet, because TLS on 5222 is optional.

```
root@prodfire0  # bzgrep port=5... ~openfireP/logs/all.log.20210716.prodfire0.bz2
/opt/openjdk-bin-8.275_p01/jre/bin/java -XX:+UseG1GC -Xms64m -Xmx256m -XX:MaxMetaspaceSize=128M -XX:MaxDirectMemorySize=64M -XX:MaxGCPauseMillis=50 -XX:ConcGCThreads=5 -XX:+ParallelRefProcEnabled -XX:ParallelGCThreads=5 -XX:ActiveProcessorCount=20 -XX:+UseStringDeduplication -Djava.io.tmpdir=/var/tmp -Djava.net.preferIPv4Stack=true -Dsun.net.inetaddr.ttl=60 -Djdk.nio.maxCachedBufferSize=262144 -Dcom.sun.management.jmxremote.port=32199 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.access.file=/opt/jmxremote/jmxremote.access -Dcom.sun.management.jmxremote.password.file=/opt/jmxremote/jmxremote.password.openfireP -Dconfig.file=/opt/openfire.4_7_0_20210509-001959/plugins/pade/classes/jicofo/application.conf -Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/opt/openfire.4_7_0_20210509-001959/plugins/pade/classes/jicofo -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=config -Djava.util.logging.config.file=./logging.properties -Djdk.tls.ephemeralDHKeySize=2048 -cp ./jicofo-1.1-SNAPSHOT.jar:./jicofo-1.1-SNAPSHOT-jar-with-dependencies.jar org.jitsi.jicofo.Main --host=xmpp.dnb.de --port=5275 --domain=xmpp.dnb.de --secre...

root@prodfire0 # ss -rnp | grep $(jps -lv | grep jicofo | cut -d ' ' -f 1)
u_str    ESTAB    0         0                                  * -1744865041                                                       * 0                           users:(("java",pid=19316,fd=15))                                               
u_str    ESTAB    0         0                                  * -1744873608                                                       * 0                           users:(("java",pid=19316,fd=6))                                                
tcp      ESTAB    0         0              prodfire0-eth1.dnb.de:38186                                         prodfire0-eth1.dnb.de:5222                        users:(("java",pid=19316,fd=22))       
```

BTW: I found the line, but this is not causing the issue.
```
2021.08.05 16:19:42 INFO  [Thread-18]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJvbWrapper - WARNING: [1] CmdLine.parse#112: Skipped invalid cmd line argument: 
```

**Comment by deleolajide** [comment]
> To my knowledge, _JiCoFo_ should connect as External Component to OpenFire on Port 5275

Jicofo does not connect as a component anymore. [See this long discussion about this.](https://github.com/igniterealtime/openfire-pade-plugin/issues/317)

The issue has to be fixed here - https://github.com/igniterealtime/openfire-pade-plugin/blob/2322b7be9561a0cb3b335dc951f0883481314718/src/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJicofoWrapper.java#L128

If TLS is required in openfire admin, then this also should be set to true. 

It has not been an issue for me as well because I use **optional** in my client TLS security settings with Openfire in order to handle plain connection between trusted process running on the same server that connect via *localhost*. It does not make sense to add TLS encryption for that use case.

**Comment by deleolajide** [comment]
# Footnote
Setting jicofo TLS to true created a race condition and ofmeet MUC room is not ready before focus user wants to join. 
Solution was to create the ofmeet room from JitsiJicofoWrapper

**Comment by gjaekel** [comment]
May be also do changes to pass the credentials via environment instead via commandline? I read somewhere about ...

**Comment by deleolajide** [comment]
The code needs a clean out as credentials are no more needed as everything is done via the focus user. I had to create a internal Openfire component and added some extra code to replicate the prosody proxy that Jitsi is using to make an XMPP component appear as a user.

See https://github.com/igniterealtime/openfire-pade-plugin/blob/master/src/java/org/jivesoftware/openfire/plugin/ofmeet/FocusComponent.java
