### ISSUE TITLE
Upgrade to latest Jitsi code

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#359]
[I have made a first pass at upgrading to latest Jitsi code for JVB, Jicofo and JitsiMeet.](https://github.com/igniterealtime/openfire-pade-plugin/commit/2322b7be9561a0cb3b335dc951f0883481314718) 

It is becoming a rather painful exercise and something I am not looking forward to doing anymore. 

The basic stuff is working, but there a few changes to the JitsiMeet APP object that have broken things in custom_ofmeet,js. This issue is to be a place holder for fixing them.

**Comment by deleolajide** [comment]
Updating to latest Jitsi code. In-progress is now broken

**Comment by deleolajide** [comment]
I am going to release 1.5.0 with in-progress disabled for now.

**Comment by gjaekel** [comment]
> Updating to latest Jitsi code. In-progress is now broken.

@deleolajide For release 1.5.3, the corresponding code was missing in `app.bundle.min.js`. Did you weave it into for release V1.6.0?

**Comment by deleolajide** [comment]
> * Did you weave it into for release V1.6.0?

No. It is still broken. We need help from @cool0707 to fix it.

**Comment by deleolajide** [comment]
> * Are more of old Pàdé functionalities still broken?

I don't think so, but I did not test everything

**Comment by gjaekel** [comment]
> No. It is still broken. We need help from @cool0707 to fix it.

I'll try to re-insert the missing code snippets.
