### ISSUE TITLE
live streaming unavailable

### ISSUE THREAD

**Issue by akbarazimifar** [igniterealtime/openfire-pade-plugin#362]
Hi 
I want to make my video conference available to users live.
But when recording the stream key, it gives the wrong key of the stream key.

Also, when I start the live broadcast, it gives the error that the live broadcast is not available

I have enabled live streaming in the settings

Please help me
Thanks
![live1](https://user-images.githubusercontent.com/5562558/130492819-50e5ce04-c6b5-466e-abf6-0df21e3f9862.jpg)
![live2](https://user-images.githubusercontent.com/5562558/130492835-78a46a34-bb3f-4bd0-a58a-889996689795.jpg)

**Comment by akbarazimifar** [comment]
![live3](https://user-images.githubusercontent.com/5562558/130496811-c303d6d8-59b3-4a2b-8db8-bcedfd43f394.jpg)

**Comment by deleolajide** [comment]
I am sorry, but it does not work that way with Pade. You would need to use Jibri on the standard alone version of Jitsi for that.

See https://github.com/igniterealtime/openfire-pade-plugin/wiki/Live-Streaming-to-RTMP-using-ffmpeg for guide on how to do RTMP live streaming with Pade

**Comment by akbarazimifar** [comment]
Thanks . 
But
This feature does not work even with Jibri .


I really need this feature .Please help me fix this.

**Comment by gjaekel** [comment]
I evaluated the live streaming via the server as described at  https://github.com/igniterealtime/openfire-pade-plugin/wiki/Live-Streaming-to-RTMP-using-ffmpeg with success. (As usual for Youtube, the stream is lagged about 30s. The speaker have to know this because this is a bit challenging concerning feedback from the audience.)

Maybe we have to check your `all.log` concerning errors.

**Comment by akbarazimifar** [comment]
Hi .

[all.log](https://github.com/igniterealtime/openfire-pade-plugin/files/7038590/all.log)
Report file from my server

**Comment by gjaekel** [comment]
```
2021.08.24 15:26:06 INFO [Jetty-QTP-BOSH-634]: LiveStreamSocket - ffmpeg staring with /usr/share/openfire/plugins/pade/classes/ffmpeg/ffmpeg -i - -vcodec copy -f flv rtmp://domain.com/stream/**************
```
This don't look like a YouTube streaming URL; Youtube told me something like `rtmps://a.rtmps.youtube.com/live2`

**Comment by akbarazimifar** [comment]
I use a custom url.
The url is set in openfire .

**Comment by gjaekel** [comment]
There's no listener available at  `domain.com:1935` 
```
# nmap domain.com -p 1935
Starting Nmap 7.80 ( https://nmap.org ) at 2021-08-24 13:56 CEST
Nmap scan report for domain.com (18.221.195.49)
Host is up (0.00027s latency).
rDNS record for 18.221.195.49: ec2-18-221-195-49.us-east-2.compute.amazonaws.com

PORT     STATE    SERVICE
1935/tcp filtered rtmp


```

**Comment by akbarazimifar** [comment]
I changed the twitch rtmp url  to rtmp://domain.com/stream/ in all.log .

rtmp://lhr03.contribute.live-video.net/app

----------------------------------------------------------
2021.08.24 17:15:07 ERROR [Jetty-QTP-BOSH-1267]: LiveStreamSocket - LiveStreamSocket onError
java.io.IOException: Stream closed

**Comment by deleolajide** [comment]
I am assuming this issue has either gone away or abandoned
