### ISSUE TITLE
Openfire Pade integration

### ISSUE THREAD

**Issue by nightstryke** [igniterealtime/openfire-pade-plugin#364]
I've noticed there's a single use in the administration of openfire for rtmp live streaming, would it be possible to integrate existing jibri servers that I may have to use with Openfire and Pade?

I'm currently using straight Jitsi with Jibri, I've got an Openfire deployment setup with Pade and I would like to try to integrate one of my jibri servers.

Anyone know how I might do that or if it's even possible?

**Comment by deleolajide** [comment]
>would it be possible to integrate existing jibri servers that I may have to use with Openfire and Pade?

We would appreciate a PR from anyone, however there is no motivation to spend time on this as we already support RTMP live streaming with ffmpeg
