### ISSUE TITLE
How is the download recording implemented?

### ISSUE THREAD

**Issue by chagai95** [igniterealtime/openfire-pade-plugin#365]
Hey, I assume you are using jibri? was just wondering how you got the client to download the files when the recording is stopped...

**Comment by gjaekel** [comment]
No, there's no _JiBri_ at all. to my knowledge this uses local recording of the streams received by the client.

**Comment by chagai95** [comment]
Wow that's pretty cool!

**Comment by chagai95** [comment]
@gjaekel I think there are two recording options what is the difference between them if they are both local? One is using the Chrome screen share option... Could you help me locate the code for this and add it to jitsi upstream as a pull request? I have time and work resources for that (motivation 😉) so it'll be great to get started on some pull requests for upstream

**Comment by chagai95** [comment]
I'd have to speak to my boss about this, the problem is we'd have to set up the backend with open fire and we run everything in Dockers so we'd have to look into that as well... Also the jitsi calls are every two weeks and you get some kind of support from that, but I see your points as well and I'll suggest it again 😎 can you point me to your pull request? I'm curious to check why it was ignored. The idea with the layouts is pretty cool I think we want to have that as well sometime and I'd love to work on it together if you're up to that, right now my focus is on adding local recording....

**Comment by gjaekel** [comment]
OK, let's work on recording. I want to offer it to our users, too. But in the moment, a important thing is missing: A record indicator, visible to all users together with broadcast messages like "recording of session has been started by foo / stopped".

**Comment by chagai95** [comment]
That's true, a recording indicator has to be built in, that's great feedback thanks for making me aware of that! I guess as a first step using the server side recording trigger for that without the backend properly working could work, but I think that'll only work with the upstream setup? I have evaluated the recording on the server side on upstream jitsi and it had a lot of scalability issues but otherwise seems petty stable (if I understood your question correctly...) I'll send you credentials via email 😉

**Comment by gjaekel** [comment]
To my knowledge Jitsi used a component JiViBri for server side recording, but OpenFire/Pàdé is using a "direct attached" ffmpeg at server side.

**Comment by gjaekel** [comment]
For the both recorders, you may start to visit the code starting at `function startRecorder(recorder)` (custom_config.js#L2163) and `function startDesktopRecorder()` (custom_config.js#L2285)
