### ISSUE TITLE
Lobby room, request to enter, no message receive in Jitsi room Padé 1.5.1

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#370]
Hello,

Just found an issue with Lobby. When requesting to enter request does not pop up in Jitsi room to authorize.
It was working fine with previous release.

You can try out on https://www.free-solutions.org Padé 1.5.1 with the problem.

**Comment by deleolajide** [comment]
Lobby room in Pade is now broken. 

Jitsi has added breakout rooms feature which uses the lobby feature and made other changes. The best thing would be to remove the Pade implementation of breakout rooms and support the new lobby code which has breakout rooms.

**Comment by gjaekel** [comment]
Yes - I had have an eagle view on this project all the time. To get **your** feature upstream, it had taken all the time from the Code Hackathon up to now and the work of a full time developer and at least two other people to archive constant pressure. I did my very best to keep the best of our ideas to survive.

I'm very curious to see the results of this.

**Comment by deleolajide** [comment]
I got a fix for fixing lobby without touching breakout rooms. I will raise a feature issue to do that later. 

>I'm very curious to see the results of this.

Good to have you back @gjaekel 👍

**Comment by ClaudeStabile** [comment]
@gjaekel, @deleolajide  Thanks very much for all efforts done to fix this.
@gjaekel Good to see you back with us. Congrats & respect for all your very positive contribs to this project

In these difficult times, all of us need to take care of ourselves, our health, our safety regarding Covid if we want to continue producing good code & contribute to best realtime apps that ever exist on this planet :)

**Comment by gjaekel** [comment]
@ClaudeStabile Thank you. But it will take some time more before I'm able to really contribute, again.

**Comment by deleolajide** [comment]
There is known issue with Lobby mode and persistent rooms.
