### ISSUE TITLE
CC button does not work / Cannot set voice to text properties in room as previously

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#371]
Cannot click on CC within Bottom menu bar In a Jitsi meeting and enable disable CC and Transcription in version 1.5.1

I am also using OF 4.6.4 and i have found that properties is missing for rooms in OF console, so cannot set up Voice to Text for specifics room. This was OKI in version 1.5.0 + OF 4.6.3
![screenshot1](https://user-images.githubusercontent.com/29485972/144411057-af0b85b5-33cc-4a3d-ab3d-663c860d8e8e.png)

**Comment by ClaudeStabile** [comment]
FYI @deleolajide When setting up properties with RawPropertyEditor, works. Only CC button does not work.

++

**Comment by deleolajide** [comment]
Please check latest nightly build and re-open if issue has not been fixed. Thanks.

**Comment by ClaudeStabile** [comment]
I cannot set properties for a chat room in new OF version 4.8.1 of Openfire + RawPropertyEditor plugins.
I get this exception :

![screenshot11](https://github.com/igniterealtime/openfire-pade-plugin/assets/29485972/ead1b25a-445d-48bf-8258-01efd62a03c0)

I am still expecting to set up voice to text on some rooms only.
However to do that with previous OF 4.7.5 versions i had to enable voice to text globally and then set it up when needed.

![screenshot12](https://github.com/igniterealtime/openfire-pade-plugin/assets/29485972/d42a3327-04bc-4386-8349-47d40aad9861)

But doing that is causing Android mobile to produce an annoying beep every 20sec... So i still did not find a proper way to conciliate this.

If there is any option or hint to do to achieve that, it will be a big step ahead for some usages. I know it is not an easy one to fix, but this would greatly help

Works perfectly on computer but not on android :( 
Unsure if "RawPropertyEditor" is working with OF 4.8.1

👏 Thanks a lot for excellent work done on transcriptions, that's really a nice feature in Jitsi Rooms

@deleolajide

**Comment by ClaudeStabile** [comment]
I confirm this issue is now fixed. Plugin works correctly with openfire 4.8.1

Thanks Dele :)
