### ISSUE TITLE
Cannot set audio transcription for a specific room

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#373]
Hello,

I use to set audio transcription for certain Vidcall rooms only. To do so i use RawPropertiesEditor plugin and create 2 variables attached to the room to enable Jitsi voice to text transcription in a specific room like voice2text for example
Simple and extremely powerful.

![screenshot17](https://user-images.githubusercontent.com/29485972/146059390-b0518af2-211d-4865-b64a-8c506fad452c.png)

Since very latest 1.5.2 latest release this does not work, i need to enable voice to text globally and then enable it on demand, that's works. However if i enable voice 2 text globally i have problem on android mobiles, beeping... So i keep it disable globally

![screenshot18](https://user-images.githubusercontent.com/29485972/146059409-c056f30f-ba16-4d85-8b7d-ea74528dfff9.png)

If we can have previous behavior so we can preset rooms with voice2text enable, is a much more flexible and powerful approach

Thanks in advance to Devs & Congrats Padé is really a fun app !!!

**Comment by deleolajide** [comment]
Please note that the correct property name is **OFMEET_ENABLE_CAPTIONS** and not OFMEET_SHOW_CAPTIONS

**Comment by ClaudeStabile** [comment]
@deleolajide 

I have corrected Thx
![screenshot27](https://user-images.githubusercontent.com/29485972/146248295-0850a5ea-15e1-4f80-9210-5c3c94723ba2.png)

Works perfectly, user can activate voice to text transcription on demand within the room

![screenshot28](https://user-images.githubusercontent.com/29485972/146248968-057d2075-a15e-43d5-8642-cd9afd623ab9.png)

Only remaining issue is with Android, Congrats for fixing this :)

**Comment by ClaudeStabile** [comment]
You can try room with voice2text option here https://www.free-solutions.org/voice2text

You need to click on CC button and activate options.

Voluntary activated only in room voice2text

BTW Lobby is working fine also :)

**Comment by ClaudeStabile** [comment]
![screenshot4](https://user-images.githubusercontent.com/29485972/163673051-4a2431cb-0e94-4df8-95a9-b7dfb4f9f748.png)

Hello,

I have tried to enable transcription on certain room only but since 1.6.2 release, i need to enable option via the cnsole. Then on Android, we get anoying beep when we try to use a room with or without voice to text transcription.
So i need to enable voice to text transcription at least to see switch button but in this case, prob when connecting with an android mobile

Thanks a lot for having a look this was orking fine in 1.5.3 version

++

**Comment by gjaekel** [comment]
@deleolajide Might this also fix https://github.com/igniterealtime/openfire-pade-plugin/issues/403#issuecomment-1078714714 ?

**Comment by deleolajide** [comment]
> @deleolajide Might this also fix [#403 (comment)](https://github.com/igniterealtime/openfire-pade-plugin/issues/403#issuecomment-1078714714) ?

I don't think so. It fixes [this commit](https://github.com/igniterealtime/openfire-pade-plugin/commit/c0daaf81d81bf6fccddf65c8274cb119e902d6df) that stops room properties from being sent to the room history when focus joins the room.

**Comment by ClaudeStabile** [comment]
@deleolajide   I am testing and using now Padé 1.7.0 and freshly re-compile 1.7.1, on both i have this issue again, cannot set voice to text for a specific room, so issue seems to be back with 1.7.0

Thanks in advance if you have a hint
