### ISSUE TITLE
Failed autentificated xmpp

### ISSUE THREAD

**Issue by mihalab** [igniterealtime/openfire-pade-plugin#382]
When I configure XMPP Account in Gateway to SIP, I have the next error
`2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 2022-01-14 10:57:23.019 SEVERE: [81] impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin().1003 Failed to connect to XMPP service
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - org.jivesoftware.smack.SmackException: No supported and enabled SASL Mechanism provided by server. Server announced mechanisms: [PLAIN, PADE]. Registered SASL mechanisms with Smack: [SASL Mech: GSSAPI, Prio: 100, SASL Mech: SCRAM-SHA-1-PLUS, Prio: 100, SASL Mech: SCRAM-SHA-1, Prio: 110, SASL Mech: DIGEST-MD5, Prio: 200, SASL Mech: CRAM-MD5, Prio: 300, SASL Mech: PLAIN, Prio: 400, SASL Mech: X-OAUTH2, Prio: 410, SASL Mech: EXTERNAL, Prio: 500, SASL Mech: ANONYMOUS, Prio: 500]. Enabled SASL mechanisms for this connection: [ANONYMOUS]. Blacklisted SASL mechanisms: [SCRAM-SHA-1-PLUS].
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 	at org.jivesoftware.smack.SASLAuthentication.selectMechanism(SASLAuthentication.java:361)
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 	at org.jivesoftware.smack.SASLAuthentication.authenticate(SASLAuthentication.java:192)
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 	at org.jivesoftware.smack.tcp.XMPPTCPConnection.loginInternal(XMPPTCPConnection.java:387)
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 	at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:491)
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 	at org.jivesoftware.smack.AbstractXMPPConnection.login(AbstractXMPPConnection.java:448)
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 	at net.java.sip.communicator.impl.protocol.jabber.AnonymousLoginStrategy.login(AnonymousLoginStrategy.java:84)
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:1371)
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.connectAndLogin(ProtocolProviderServiceJabberImpl.java:970)
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.initializeConnectAndLogin(ProtocolProviderServiceJabberImpl.java:795)
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 	at net.java.sip.communicator.impl.protocol.jabber.ProtocolProviderServiceJabberImpl.register(ProtocolProviderServiceJabberImpl.java:500)
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 	at org.jitsi.jigasi.util.RegisterThread.run(RegisterThread.java:59)
2022.01.14 10:57:23 INFO  [Thread-21]: org.jivesoftware.openfire.plugin.ofmeet.JitsiJigasiWrapper - 2022-01-14 10:57:23.035 SEVERE: [81] org.jitsi.jigasi.JvbConference.registrationStateChanged().645 [ctx=1642147041797514903356] XMPP Connection failed.`

I tried set xmpp.auth.anonymous to true, and gateway works ok. How I can set xmpp.auth.anonymous to false?
I think that need change org.jitsi.jigasi.xmpp.acc.ANONYMOUS_AUTH=false at sip-communicator.properties file, but i cann't to do this. This file generate and overwrite evere time, after restart Openfire server

**Comment by deleolajide** [comment]
The anonymous setting for the jigasi user is hardcode true, because Pade does not support a registered XMPP user at the moment for SIP meeting participant. See my screenshot. I am going to leave the issue open as a reminder to use an Openfire property instead of a hard-coded value.

![image](https://user-images.githubusercontent.com/110731/149564815-bcb094d2-52d4-4f1f-8fc4-d0664cc65347.png)

**Comment by mihalab** [comment]
I would like add more information about this situation. The default value of xmpp.auth.anonymous is false, and i spent a lot of time for understand why jigasi registered on PBX, but don't answer call. I am not found information about this in Readme file of Pade

**Comment by gjaekel** [comment]
@mihalab :
>  This file generate and overwrite evere time, after restart Openfire server

You may work around this in a crude way by changing the access rights of the config file to r/o. Of course, this file is also lost on every fresh install of the plugin. You may work around by moving you private config "out of the tree" and use a symbolic link to "restore" it.

**Comment by deleolajide** [comment]
> The default value of xmpp.auth.anonymous is false

There is no default value. It is hard-coded to true.  Look at the code 
https://github.com/igniterealtime/openfire-pade-plugin/blob/607252aa67c950b07d038d117f7385cf6bf80858/src/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJigasiWrapper.java#L68

You have to allow anonymous connections into Openfire in order to use jigasi for now.
![image](https://user-images.githubusercontent.com/110731/149616816-4c44fa4a-d7b9-46ed-b4f3-321d30ff2363.png)

**Comment by mihalab** [comment]
@gjaekel If I set r/o acсess for sip-communicator.properties, Pade is not working correct
@deleolajide I meant that xmpp.auth.anonymous default value is false in Openfire server, not Pade

**Comment by deleolajide** [comment]
I am leaving org.jitsi.jigasi.xmpp.acc.ANONYMOUS_AUTH hardcoded at TRUE for now. If any one wants authenticated telephone participants in a call, I am happy to accept a PR
