### ISSUE TITLE
Static ICE mapping no longer offered to clients

### ISSUE THREAD

**Issue by lochner** [igniterealtime/openfire-pade-plugin#385]
### Symptom

For an Azure based deployment, after upgrading to Pàdé plug-in version 1.6.0, both occupants enter a perpetual disconnect/reconnect cycle about 18 seconds after the second one joins a room, with the following message displayed each time:

> Call restarted because of a connection issue.
&nbsp;&nbsp;Restart initiated because of a bridge failure
&nbsp;&nbsp;Dismiss

Running JVB in a console, the following two lines appear for working version 1.5.3-SNAPSHOT of 2021-12-15, but not for problematic version 1.6.0, where the masked address agrees with the public address configured under _Pade > Networking > IP Address Mapping_:

> INFO: [10] org.ice4j.ice.harvest.MappingCandidateHarvesters.initialize: Adding a static mapping: StaticMapping(localAddress=10.0.2.4, publicAddress=xxx.xxx.xxx.xxx, localPort=null, publicPort=null, name=null)
INFO: [10] org.ice4j.ice.harvest.MappingCandidateHarvesters.initialize: Using org.ice4j.ice.harvest.StaticMappingCandidateHarvester(face=10.0.2.4:9/udp, mask=xxx.xxx.xxx.xxx:9/udp)

It thus seems that the configured ICE mapping is no longer added and therefore not offered to clients.

### Possible cause

The only other significant difference in the console output looks like this (127.0.0.1 now, vs. 0.0.0.0 before):

Version 1.5.3-SNAPSHOT of 2021-12-15
> INFO: [1] org.eclipse.jetty.server.AbstractConnector.doStart: Started ServerConnector@ecde95{HTTP/1.1, (http/1.1)}{0.0.0.0:8180}

Version 1.6.0
> INFO: [1] org.eclipse.jetty.server.AbstractConnector.doStart: Started ServerConnector@dff0b7{HTTP/1.1, (http/1.1)}{127.0.0.1:8180}

Perhaps the static mapping is dropped because no binding exists for its local address?

The problem might be caused by d1b964fcfb7f6a1f8f530cf2448a2592a4779ba6, but was not investigated further.

### Work-around

Specify a STUN server under _Pade > Networking > IP Address Mapping_.

**Comment by deleolajide** [comment]
> The problem might be caused by [d1b964f](https://github.com/igniterealtime/openfire-pade-plugin/commit/d1b964fcfb7f6a1f8f530cf2448a2592a4779ba6), but was not investigated further.

Most likely caused by tis change which I added in order to test clustering using two network interfaces on the same hardware. I needed each openfire instance to bind to separate network interfaces. Looks like that messed up ICE mapping.

I will try and fix it, otherwise revert back to omitting host specification and binding to all interfaces with 0.0.0.0 instead

**Comment by deleolajide** [comment]
I am hoping this fixes it. Otherwise, please re-open this issue

**Comment by lochner** [comment]
The changes in 661e9f6790581e46a1a069ce97a1e5402d73e2e2, as reflected in version 1.6.1-SNAPSHOT of 2022-01-24, did unfortunately not fix the problem, with the two lines about the static mapping candidate, referred to above, still missing in the console log.

The other difference between the logs of the last working version and the current version has changed a bit more (as could be expected):

Version 1.5.3-SNAPSHOT of 2021-12-15

> INFO: [1] org.eclipse.jetty.server.AbstractConnector.doStart: Started ServerConnector@ecde95{HTTP/1.1, (http/1.1)}{0.0.0.0:8180}
INFO: [1] org.eclipse.jetty.server.AbstractConnector.doStart: Started ServerConnector@23134f{HTTP/1.1, (http/1.1)}{127.0.0.1:8188}

Version 1.6.1-SNAPSHOT of 2022-01-24

> INFO: [1] org.eclipse.jetty.server.AbstractConnector.doStart: Started ServerConnector@dff0b7{HTTP/1.1, (http/1.1)}{10.0.2.4:8180}
INFO: [1] org.eclipse.jetty.server.AbstractConnector.doStart: Started ServerConnector@1bf4cbd{HTTP/1.1, (http/1.1)}{10.0.2.4:8188}

I'm out of ideas at this stage, as I couldn't find where ICE candidates might be filtered.&nbsp; The STUN server work-around remains effective, though.

**Comment by gjaekel** [comment]
The new lines 95 and 99 introducing the `host` tags ... 
https://github.com/igniterealtime/openfire-pade-plugin/blob/b2ddf237fe2b90f95195ba73c6bfb40a859a4247/src/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJvbWrapper.java#L90-L101
will bin the listeners to this IP addresses instead to `0.0.0.0`. This breaks my installation (DMZ & firewall) because of the **external** IP is used and not the **internal** one and the listener can't be bind on that.
```
20220217-135850.228 DEBUG [Thread-17] [o.j.o.p.o.JitsiJvbWrapper] Exception in thread "main" java.io.IOException: Failed to bind to /193.175.100.141:8180
```

**Comment by deleolajide** [comment]
I need that change in order to test clustering in Openfire on the same PC with 2 different network interfaces and IP addresses. However, we can revert if it is causing issues elsewhere

**Comment by gjaekel** [comment]
FYI: As a workaround, I made `application.conf` r/o and edit it to use the same internal IP at `public` as `private`. This make the JVB visible to Openfire, again.

Now, it seem that I have Pade-1.6.1 on Openfire-4.7.1 on Java-17 (GraalVM-22) up and running. :rocket:

**Comment by gjaekel** [comment]
I wonder if the `private` port should even be left to bind al `localhost` for security reasons (as it's the default without an explicit `host` tag)!

**Comment by gjaekel** [comment]
I just start testing and unfortunately, I have to confirm the ICE issue, even with the `private` listener bound at `0.0.0.0`:
```
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper] WARNING: [92] [confId=74daeb5a866d259e gid=36422 stats_id=Wilfrid-qiY conf_name=bastelkeller@conference.eval.xmpp.dnb.de ufrag=fbo0b1fs43f70p epId=2b8c9ab1 local_ufrag=fbo0b1fs43f70p] ConnectivityCheckClient.startCheckForPair#374: Failed to send BINDING-REQUEST(0x1)[attrib.count=6 len=92 tranID=0xE7A237087F01D289A745B1D7]
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper] java.lang.IllegalArgumentException: No socket found for 10.10.59.52:4443/tcp->172.16.142.3:9/tcp
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at org.ice4j.stack.NetAccessManager.sendMessage(NetAccessManager.java:631)
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at org.ice4j.stack.NetAccessManager.sendMessage(NetAccessManager.java:581)
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at org.ice4j.stack.StunClientTransaction.sendRequest0(StunClientTransaction.java:267)
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at org.ice4j.stack.StunClientTransaction.sendRequest(StunClientTransaction.java:245)
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at org.ice4j.stack.StunStack.sendRequest(StunStack.java:680)
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at org.ice4j.ice.ConnectivityCheckClient.startCheckForPair(ConnectivityCheckClient.java:335)
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at org.ice4j.ice.ConnectivityCheckClient.startCheckForPair(ConnectivityCheckClient.java:231)
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at org.ice4j.ice.ConnectivityCheckClient$PaceMaker.run(ConnectivityCheckClient.java:938)
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at org.ice4j.util.PeriodicRunnable.executeRun(PeriodicRunnable.java:206)
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
20220217-160538.280 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
20220217-160538.281 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
20220217-160538.281 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper]       at java.base/java.lang.Thread.run(Thread.java:833)
20220217-160538.281 DEBUG [Thread-15] [o.j.o.p.o.JitsiJvbWrapper] INFO: [92] [confId=74daeb5a866d259e gid=36422 stats_id=Wilfrid-qiY conf_name=bastelkeller@conference.eval.xmpp.dnb.de ufrag=fbo0b1fs43f70p epId=2b8c9ab1 local_ufrag=fbo0b1fs43f70p] ConnectivityCheckClient$PaceMaker.run#942: Pair failed: 10.10.59.52:4443/tcp/host -> 172.16.142.3:9/tcp/host (stream-2b8c9ab1.RTP)
```

**Comment by gjaekel** [comment]
Found the reason: The "harvester"-enties in `config/sip-properties` are missing!
```
net.java.sip.communicator.service.media.MIN_PORT_NUMBER=10000
org.ice4j.ice.harvest.DISABLE_AWS_HARVESTER=true
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=10.10.1.141
org.ice4j.ice.harvest.USE_DYNAMIC_HOST_HARVESTER=false
-org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=193.175.100.141
```
If I nail them using a r/o file, the harvester is working again and I may start conferences.

_Going to trace down the core reason, now... _

**Comment by GitHub-sKing** [comment]
I want to how to solve?

**Comment by gjaekel** [comment]
What do you mean by "solve", please?

**Comment by GitHub-sKing** [comment]
> 如何解决动态ICE映射？

How to resolve dynamic ICE mapping?

**Comment by GitHub-sKing** [comment]
> 请问“解决”是什么意思？

How would I modify the dynamic ICE mapping?

**Comment by GitHub-sKing** [comment]
> At the moment, you may fix this by editing the config file and making it read-only
> 
> > 目前，您可以通过编辑配置文件并将其设为只读来解决此问题

How to modify it?

**Comment by gjaekel** [comment]
You may add the missing definitions for the harvester at the file `.../plugins/pade/classes/jvb/config/sip-communicator.properties`, see https://github.com/igniterealtime/openfire-pade-plugin/issues/385#issuecomment-1043078073

**Comment by gjaekel** [comment]
If you mean "via the UI": No, you can't; you have to wait for a fix.

**Comment by deleolajide** [comment]
>Even if working, what is the intention of the value overrides in L319 and L325, please?

With clustering, every node reads properties from the same database, it is not possible to use the local and public values stored in properties with JiveGlobals.getProperty. We have to use values stored in the openfire.xml file of each node with JiveGlobals.getXMLProperty.

The code was working on my test Windows PC with two virtual IP addresses, but I can see the issue it will cause elsewhere. I will post a fix ASAP

**Comment by gjaekel** [comment]
> With clustering, every node reads properties from the same database, ...

I understand; this is maybe a meta-issue to be solved at OpenFire level because from my experience it typical for a cluster to have some node-individual settings.

**Comment by deleolajide** [comment]
>this is maybe a meta-issue to be solved at OpenFire level
Openfire has provided a solution. We should store in local openfire.xml file and access with JiveGlobals.getXMLProperty

**Comment by deleolajide** [comment]
Fix posted via commit https://github.com/igniterealtime/openfire-pade-plugin/commit/cfbabc7a903f2063c2c36492f75327c28ee58ac1

**Comment by lochner** [comment]
@deleolajide, thank you for looking into this.&nbsp; Unfortunately, cfbabc7 also does not fix it for me.

<br>I'm confused by the difference between the UI and `JitsiJvbWrapper.java` (private vs local), but it may be a red herring:

_Pade_ > _Networking_ > _IP Address Mapping_ > _Local address_ sets `org.ice4j.ice.harvest.NAT_HARVESTER_PRIVATE_ADDRESS`

https://github.com/igniterealtime/openfire-pade-plugin/blob/9c1803cd215057d9e47a25f02d6472fb8b387a0a/src/java/org/jivesoftware/openfire/plugin/ofmeet/JitsiJvbWrapper.java#L325

<br>Manually adding the following entries to `sip-communicator.properties`, as indicated by @gjaekel in https://github.com/igniterealtime/openfire-pade-plugin/issues/385#issuecomment-1043078073 above, does fix it, though:
```
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=10.0.2.4
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=xxx.xxx.xxx.xxx
```

**Comment by deleolajide** [comment]
>I'm confused by the difference between the UI and JitsiJvbWrapper.java (private vs local), but it may be a red herring:

The confusion is from legacy ofmeet code. Pade stores the property as NAT_HARVESTER_PRIVATE_ADDRESS, but Jisti requires NAT_HARVESTER_LOCAL_ADDRESS. It could be a name change that was not reflected back to ofmeet. In any case, the correct property name for Jitsi is being written to sip-communicator.properties

>Manually adding the following entries to sip-communicator.properties, as indicated by @gjaekel in https://github.com/igniterealtime/openfire-pade-plugin/issues/385#issuecomment-1043078073 above, does fix it, though:

This should be achieved with UI

![image](https://user-images.githubusercontent.com/110731/156007820-24cb0d72-51c1-4330-9546-52a2a2c09a9e.png)

![image](https://user-images.githubusercontent.com/110731/156008169-229a999a-4801-45ec-993d-8bf41e1034ad.png)

However, I noticed that because of the clustering changes I made, it is overriding the local value with the IP address in the openfire.xml file. I have now [added a check to make sure this only happens when clustering is enabled](https://github.com/igniterealtime/openfire-pade-plugin/commit/a9a48ca47e26469e801a92a2dcb96813c2b8f1b1)

**Comment by lochner** [comment]
Thank you @deleolajide!

This issue is fixed for me with today's version 1.6.2-SNAPSHOT-8:
https://www.igniterealtime.org/projects/openfire/plugins/1.6.2-SNAPSHOT/pade.jar?snapshot=20220228.151005-8

It may have been fixed even earlier, as I discovered now that my first attempt to download from the link above, using wget 1.20.3, resulted in the same file as snapshot 1 from 2022-02-15.&nbsp; (The correct file was subsequently downloaded with a browser.)

The failure of wget to follow the download redirects also offers a likely explanation for my earlier trouble with stale files in https://github.com/igniterealtime/openfire-pade-plugin/issues/372#issuecomment-992632668.&nbsp; Apologies for the extra effort caused then and now.

(It would be useful if installed snapshot builds were also uniquely identified on the Openfire plug-in page, as it may prevent others from falling into the same trap.)

**Comment by gjaekel** [comment]
> It may have been fixed even earlier, as I discovered now that my first attempt to download from the link above, using wget 1.20.3, resulted in the same file as snapshot 1 from 2022-02-15.  (The correct file was subsequently downloaded with a browser.)

You might just forget to quote the URL passed to your call of wget at command line.

**Comment by lochner** [comment]
I can confirm that wget downloaded the correct file when the URL was enclosed in quotes.&nbsp; Thanks for following up on this, @gjaekel.

**Comment by gjaekel** [comment]
We ony human. Because I also often stepped into this in former times, I "forced" me to blindly quote every URL on command line.
