### ISSUE TITLE
Feature Request: Allow the moderator to grand this role to other participants

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#39]
In an analogous way to the "kick" feature, allow the current moderator(s) to elect other participants as (co-)moderators. This is helpful for managing bigger audiences.

Note: XMPP-Admins are already treated as moderators.

**Comment by deleolajide** [comment]
I guess this is what you want. A standard XMPP tool to grant/revoke roles to users.

![image](https://user-images.githubusercontent.com/110731/83397973-65988c80-a3f6-11ea-86a6-299edc16cf10.png)

This already implemented in the Converse client. From the pespective of Pade being a unified client for messaging, audio and video communication. There is no point re-writing this code for the Jitsi Client.

**Comment by deleolajide** [comment]
closed in error

**Comment by gjaekel** [comment]
> I guess this is what you want

Technical yes, but I want to have it within the OFMeet client GUI to be used at start of meetings because at our company nobody use an additional text chat client.

**Comment by deleolajide** [comment]
There is now an upstream PR for this - https://github.com/jitsi/jitsi-meet/pull/7248

**Comment by gjaekel** [comment]
Good news!

**Comment by gjaekel** [comment]
Solved by upstream PR.
