### ISSUE TITLE
Revival of the In-Progress Meeting List feature

### ISSUE THREAD

**Issue by cool0707** [igniterealtime/openfire-pade-plugin#391]
To make it easier to handle upstream updates, I'd like to move the code from `app.bundle.min.js` to `custom_ofmeet.js` and revive in-progress meeting list feature.
This has been done in PR #388.

**Comment by deleolajide** [comment]
I am considering this work done. Otherwise, please re-open

**Comment by gjaekel** [comment]
At our site, it's working like before. I keep my ideas to improve privacy on my mind.
