### ISSUE TITLE
Bug: Mute button/hotkey not working in absence of a webcam

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#40]
After entering a room in absence of a webcam (this will produce a yellow alert that *must* be acknowledged) the mic is on, but not mutable via the icon or hotkey. 

A workaround is to open the audio source popup and (re)select the mic source. After this, the icon and/or hotkey is working as expected.

**Comment by deleolajide** [comment]
This one has go upstream to Jitsi. Anything else will be a difficult to support hack as Jitsi continually changes the code base.

**Comment by gjaekel** [comment]
Can you confirm this bug?

**Comment by deleolajide** [comment]
No. I don't have a laptop without a webcam to test with.
