### ISSUE TITLE
mvn -X package failed with latest code

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#417]
Hello,

I try to generate latest pade.jar from current source code and i get a compil/generation issue
Maven compil package issue
I did try out to generate pade.jar using mvn -X package and i get the following error message. Under ubuntu 20.04.4 

Effectively when i try to unzip file /data/PADE/openfire-pade-plugin-main/classes/docs/docs-2.0.7.2.zip I get an error

++ Thanks in advance for help

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:00 min
[INFO] Finished at: 2022-04-30T21:43:17+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.5.0:wget (retrieve-pade-webclient) on project pade: IO Error: Error while expanding /data/PADE/openfire-pade-plugin-main/classes/docs/docs-2.0.7.2.zip: archive is not a ZIP archive -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.5.0:wget (retrieve-pade-webclient) on project pade: IO Error

[DEBUG] Expanding: /data/PADE/openfire-pade-plugin-main/classes/docs/docs-2.0.7.2.zip into /data/PADE/openfire-pade-plugin-main/classes/docs
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:00 min
[INFO] Finished at: 2022-04-30T21:43:17+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.5.0:wget (retrieve-pade-webclient) on project pade: IO Error: Error while expanding /data/PADE/openfire-pade-plugin-main/classes/docs/docs-2.0.7.2.zip: archive is not a ZIP archive -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.5.0:wget (retrieve-pade-webclient) on project pade: IO Error

**Comment by gjaekel** [comment]
[Latest CI build](https://www.igniterealtime.org/projects/openfire/plugins/1.7.0-SNAPSHOT/pade.jar?snapshot=20220430.102422-3) run successfully.

**Comment by deleolajide** [comment]
I suggest you delete  /data/PADE/openfire-pade-plugin-main/classes/docs/docs-2.0.7.2.zip. and clear maven cache as well then try again.  The error message suggest that the file is corrupt.

**Comment by ClaudeStabile** [comment]
@deleolajide 

I have sucessfully build a fresh package build with mvn and latest code from github, so you can close this issue, it is fixed with current source code

Thx

**Comment by ClaudeStabile** [comment]
Problem is gone with lattest code, so closed
