### ISSUE TITLE
Cannot create account with Padé 1.7.0 as previously

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#425]
Hello,

Before 1.7.x release, i was able to create accounts via the web page like this : 
![screenshot9](https://user-images.githubusercontent.com/29485972/170870122-403cda20-8881-4486-86c7-f32335f71fb7.png)
With Padé 1.7.x i am re-directed to option page : 
![screenshot8](https://user-images.githubusercontent.com/29485972/170870150-016b4988-9718-4402-95fd-1d31f953af1f.png)

Is there a way to go back to same behavior as per version 1.6.x ? Login page + account creation was the ideal for most of the usages
With 1.7.x i am not capable to provide same behavior and free account creation

Thanks in advance for hints and sugestions

++

**Comment by deleolajide** [comment]
In 1.7+, there is only a single window for both config and the converse because of changes by Google to the way background pages behave in a browser extension.. In 1.6, separate windows were used. I will have a look at a solution to make it backward compatible

**Comment by ClaudeStabile** [comment]
@deleolajide 

Can you pls let me know when i can do a git clone https://github.com/igniterealtime/openfire-pade-plugin to get this update. I will rebuild Padé with mvn then  and install. I do not think i get it. If you plan to do a new release, i will wait if it make sense.

Thx !

**Comment by deleolajide** [comment]
> Can you pls let me know when i can do a git clone https://github.com/igniterealtime/openfire-pade-plugin to get this update

You can do it now. Your maven build should automatically use docs-2.0.9.1.zip for the Pade Client (Converse)
