### ISSUE TITLE
guide for translation

### ISSUE THREAD

**Issue by bernard-ng** [igniterealtime/openfire-pade-plugin#426]
how to add the translation in another language? example French, I would like to contribute by adding the French support.

**Comment by deleolajide** [comment]
That you for attempting to do this

Guidelines for creating language translations for Openfire plugins can be found at

https://download.igniterealtime.org/openfire/docs/latest/documentation/plugin-dev-guide.html
https://download.igniterealtime.org/openfire/docs/latest/documentation/translator-guide.html

The i18n translation folder for this plugin is

https://github.com/igniterealtime/openfire-pade-plugin/tree/main/src/i18n
