### ISSUE TITLE
Setting UHD resolution up to 4k

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#431]
Hello,

since latest versions, i have noticed that video resolution is limited to 720p even if i set higher value in pade/jitsi openfire settings.

I have also noticed that 720p is the default value set when i navigate to https://www.free-solutions.org/config.js

How can i change increase the resolution ? By default it was going up to 4k with latest jitsi it seems that it is set to 720p by default. Am i correct any clue to set resolution as i want ?

Thanks in advance for hints

**Comment by deleolajide** [comment]
Hi Claude 😊 Have tried changing this  -dele Sent from Mail for Windows From: Claude StabileSent: 25 August 2022 14:44To: igniterealtime/openfire-pade-pluginCc: SubscribedSubject: [igniterealtime/openfire-pade-plugin] Setting UHD resolution up to 4k (Issue #431) Hello,since latest versions, i have noticed that video resolution is limited to 720p even if i set higher value in pade/jitsi openfire settings.I have also noticed that 720p is the default value set when i navigate to https://www.free-solutions.org/config.jsHow can i change increase the resolution ? By default it was going up to 4k with latest jitsi it seems that it is set to 720p by default. Am i correct any clue to set resolution as i want ?Thanks in advance for hints—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by ClaudeStabile** [comment]
@deleolajide Sorry but i can't read what do you mean ?

++

**Comment by deleolajide** [comment]
> How can i change increase the resolution ? By default it was going up to 4k with latest jitsi it seems that it is set to 720p by default. Am i correct any clue to set resolution as i want

**Have you tried changing these values in admin** I think default is 720

![image](https://user-images.githubusercontent.com/110731/187461588-2cc02284-9c0f-4178-ac62-ab22bf147756.png)

**Comment by deleolajide** [comment]
Does Jitsi Videobridge support 4k?

**Comment by ClaudeStabile** [comment]
Hi Dele,

here are settings i use to have and used to work. When we are in p2p it use to easilly go to 4k with 4k cams. Now Chrome shows only 720p max in all cases

These are my settings 
![screenshot17](https://user-images.githubusercontent.com/29485972/187468252-68545422-70a9-465b-8e7a-ef2ab8d53cb4.png)

While i navigate to https://www.free-solutions.org/config.js i saw "resolutions=720" in file
Feel free to have a look

++ Thanks a lot in advance for hints

**Comment by deleolajide** [comment]
How about this

![image](https://user-images.githubusercontent.com/110731/187472554-bfc35d64-568b-4f45-95b1-91878d1247a7.png)

**Comment by ClaudeStabile** [comment]
Let me give a try increasing those values again, i keep you update

**Comment by ClaudeStabile** [comment]
Dele,

I ve tried with this restart OF
![screenshot20](https://user-images.githubusercontent.com/29485972/187476506-7160d6af-b3a2-458b-9a2c-8e3a87dbd27a.png)

No change and btw config.js is still showing resolution=720

++

**Comment by ClaudeStabile** [comment]
Dele,

From jitsi settings doc we have https://jitsi-club.gitlab.io/jitsi-self-hosting/en/01-deployment-howto/03-tuning/
![screenshot22](https://user-images.githubusercontent.com/29485972/187478513-0f7e3f21-a9b0-428f-b687-4bcd79e6e5f9.png)

As config.js currently shows resolution=720, cannot reach a higher value i suspect

Any way to change or access this value ? make sense a good seting that could be nice ideally from OF padé console ?

++

**Comment by deleolajide** [comment]
> Any way to change or access this value ? make sense a good seting that could be nice ideally from OF padé console ?

See https://github.com/igniterealtime/openfire-pade-plugin/blob/3e80ba2e84657421962d488c5071e39fb0e654fb/src/java/org/igniterealtime/openfire/plugin/ofmeet/config/OFMeetConfig.java#L319

Change openfire property called **org.jitsi.videobridge.ofmeet.resolution**

**Comment by ClaudeStabile** [comment]
@deleolajide Cool, this works, i can now reach higher values up to 4k :)
Cool 
Nice to have : a setting box via the console, but that's already sufficient for my usage :) THANKS @deleolajide

**Comment by deleolajide** [comment]
> Nice to have : a setting box via the console

![image](https://user-images.githubusercontent.com/110731/187654630-db335204-05d6-428d-8fa9-abf206f709ab.png)

**Comment by ClaudeStabile** [comment]
@deleolajide 

Works ! up to 4k resolution in p2p mode and jitsi mode with this setting, up to 4k call via https://www.free-solutions.org & https://call.free-solutions.org :)
![4kperfectsettings](https://user-images.githubusercontent.com/29485972/187663549-b60bb1e7-96db-45df-8f22-eb1fef254b55.png)

THANKS !
