### ISSUE TITLE
Cannot create new users with Padé

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#435]
Hello,

Cannot create users 

versions : OF 4.7.3 Padé 1.7.2

After update, cannot create new user via webpage via web page for example at https://www.free-solutions.org/pade
![screenshot1](https://user-images.githubusercontent.com/29485972/199616281-cee605cb-eac7-45d9-8e9c-fd13be3ea71e.png)
Websocket is set to no
![screenshot2](https://user-images.githubusercontent.com/29485972/199616291-38bccfba-fa75-4690-afea-d284384e6425.png)

Thanks in advance for your help

++

**Comment by deleolajide** [comment]
Fixed with pade client 2.1.1

![image](https://user-images.githubusercontent.com/110731/199714468-3c3b1ffd-2da9-4f75-9be9-ddf55495a68d.png)

**Comment by ClaudeStabile** [comment]
Dele,

Thanks i will rebuild pade.jar from source and try out. I need this but that's only for https://www.free-solutions.org so for free usages and testers as usual

Thanks ++
