### ISSUE TITLE
Bug: Left Toolbar renders to wide

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#44]
Caused by the icons of the additional features offered by OFMeet (breakout rooms, contact manager),
on small browser windows, the left toolbar renders to wide. This is caused by the additional items for the Contact Manager and the Breakout Rooms.

**Comment by gjaekel** [comment]
Make it wrapping around by #41.

**Comment by deleolajide** [comment]
New build available with fix from https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v0.9.10-snapshot
