### ISSUE TITLE
Fix webclient's keepalive mechanism

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#445]
The webclient periodically calls a special URL in the domain of the XMPP server: `xmpp.domain.tld/pade/keepalive?room=foo`

* If this domain is different from the one of the Webclient, the corresponding `fetch` call will fail in the browser with a *CORS*-violation.
* In addition, the GET request will immediate redirected by an 302-header to the URL appended with a `/`. This second GET request will get an 200-response with the payload `OK`. This served by a static file.

This will at least fill the client console log with errors.

**Comment by gjaekel** [comment]
The first may be fixed by making `fetch` relaxed to _CORS_ violations.
```
--- lib-jitsi-meet.min.js.20230123-130126	2023-01-23 13:01:26.026395000 +0100
+++ lib-jitsi-meet.min.js	2023-02-02 19:21:11.246276000 +0100
@@ -3240,7 +3240,7 @@
 								shard: e,
 								websocketKeepAliveUrl: t
 							} = this._options, n = t || this.service.replace("wss://", "https://").replace("ws://", "http://");
-							return fetch(n).then((t => {
+							return fetch(n,{mode: 'no-cors'}).then((t => {	// BAO	gj:add no-cors
 								if (!e) return;
 								const n = t.headers.get("x-jitsi-shard");
 								n !== e && (Ws.error(`Detected that shard changed from ${e} to ${n}`), this.eventEmitter.emit(Xs.Events.CONN_SHARD_CHANGED))
```
@deleolajide: Sorry, I'm not able to file a pull request about the because of the "big file"-restriction of the GitHub Webclient.


The second issue, i.e. the redirection is more cosmetically. But might be avoided by adjusting the websocketkeepalive-URL from `.../pade/keepalive` to `.../pade/keepalive/index.html` in the config sevlet.

But in general, I found on the _Jitsi Community_ site (https://community.jitsi.org/t/ws-enable-on-multiple-shards-with-octo-and-jwt/110402), that this Keepalive HTTP call is thought to help to make the **XMMPP-Websocket**-Connection sticky on Load-Balancer setups dealing with shards of XMPP servers. Up to now, this header isn't set; therefore the shard change handling is disabled.

**Comment by Neustradamus** [comment]
@deleolajide: Have you seen?
