### ISSUE TITLE
Feature Request: Extend statistics for Raised Hands

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#45]
With, the number of Raised Hands have become counted and displayed at the bottom.

To ease the use as a simple voting tool, extend the "Raised Hands" statistics by the total number of participants and the percentage of raised hands.

**Comment by gjaekel** [comment]
Implemented by #42. For the number of participans, I wasn't able to find a better source than `APP.conference.getNumberOfParticipantsWithTracks()`. But I don't know the functional meaning of *with tracks*.

**Comment by deleolajide** [comment]
New build available with fix from https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v0.9.10-snapshot

I will keep it open till I can confirm APP.conference.getNumberOfParticipantsWithTracks() will cover webinar uses who may not have audio/video tracks

**Comment by gjaekel** [comment]
Please have a look at `conference.js`: There are more methods, but with my very limited JS-knowledge, I can't get them running. An alternative approach might be to figure out what data sources is used for the display at top.

**Comment by deleolajide** [comment]
> There are more methods,

You are right. APP.conference.listMembers().length would be better

**Comment by gjaekel** [comment]
Maybe my mistake, but some obvious candidates throw just errors. And there is a complete strange one named `get<space>membersCount()`I don't know to how to call.

    get membersCount() {
        return room.getParticipants().length + 1;
    },

Note: The `+1` is because it written one self is not in this list and I would agree :)

We may test this live on my eval stage using the browser debugger if you like.

**Comment by deleolajide** [comment]
ok. I have changed it to APP.conference.listMembers().length and that works with webinar uses. 
I have updated https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v0.9.10-snapshot

I am going to close the issue now. If it still does not work for you, please reopen.

**Comment by gjaekel** [comment]
Seems to work on Eval. On Prod, i'll check it later this day.

            // const handsTotal = 1 + APP.conference.getNumberOfParticipantsWithTracks();
            const handsTotal = 1 + APP.conference.listMembers().length;

I added the 1+ lateron and refactored to the const handsTotal. Maybe I had have an auto-typing error while adding the parts of the string constansts and the func().length
