### ISSUE TITLE
Pade plugin not working for me (IMAGES)

### ISSUE THREAD

**Issue by isaanyoha** [igniterealtime/openfire-pade-plugin#451]
I get this error in my log when I install the plugin. I am using Openfire 4.7.4 & Pade 1.7.6
![ezgif-3-774f91e55c2](https://user-images.githubusercontent.com/4920405/230298648-49111e49-cee7-4c93-87b8-d2ef70a28d95.png)

![ezgif-3-774f91e55c3](https://user-images.githubusercontent.com/4920405/230300044-01499234-a057-4214-bcfa-31b2935c6554.png)

**Comment by deleolajide** [comment]
sorry, i don't have enough information to explain why it is not working for you. Try deleting log files, plugin file and folder. Re-install and try again.

**Comment by gjaekel** [comment]
Please provide at least the complete log files: Stop OpenFire, delete or rotate the log, record a complete startup and share this.

**Comment by isaanyoha** [comment]
Alright. Thanks for the responses, guys. I appreciate your assists
