### ISSUE TITLE
Live Stream button to Youtube is missing with version 1.76

### ISSUE THREAD

**Issue by ClaudeStabile** [igniterealtime/openfire-pade-plugin#452]
Hello,

I have noticed that with 1.76 version the Livestream button is not showing up. 
I have ticked this in settings

![screenshot4](https://user-images.githubusercontent.com/29485972/231721692-36714cc4-8db0-4b1a-807c-ec6a5be5521a.png)

I have also validated ffmpeg key and settings 

![screenshot6](https://user-images.githubusercontent.com/29485972/231722286-fd1fd23c-d056-4f1a-afa2-db691f679612.png)

##**But menu is not showing up after Restart No Live Streaming in version 1.76** 

# In version 1.55 in same conditions i have the Live Stream button showing up :
![screenshot5](https://user-images.githubusercontent.com/29485972/231723041-647f14c8-d2ac-47ca-a583-7dd71ba69fa6.png)

Big thanks in advance for helping out

**Comment by deleolajide** [comment]
Live stream for PADE is different from Jitsi Standalone Live Stream.  It uses the Desktop Recorder button. If you have RTMP streaming configured, the desktop is streamed  to the RTMP server (youtube.com). If no RTMP is configured, then desktop is recorded into a WEBM file and saved locally on the PC.

See https://github.com/igniterealtime/openfire-pade-plugin/wiki/Live-Streaming-to-RTMP-using-ffmpeg
See https://github.com/igniterealtime/openfire-pade-plugin/discussions/262
See https://github.com/igniterealtime/openfire-pade-plugin/discussions/283

![image](https://github.com/igniterealtime/openfire-pade-plugin/assets/110731/5aa7cd32-a69d-4acf-8d44-b24efa1e646c)

**Comment by ClaudeStabile** [comment]
@deleolajide : Thank you very I will try out. I need to record and broadcast an event on Youtube by the end of June. 
Thanks for details and explanations about it.
