### ISSUE TITLE
Proposal: Improve content of web-push messages 

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#46]
The current content of a web-push messages is not very elaborated.

**Comment by gjaekel** [comment]
Make web-pushed message more colloquial:
 *  subject: APP_NAME
 *  body: DISPLAY_NAME invites you to join the room ROOM_NAME

Implemented by #43

**Comment by deleolajide** [comment]
New build available with fix from https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v0.9.10-snapshot
