### ISSUE TITLE
Improve meeting room breakout

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#48]
Fix a number of issues:

1. Add the ability for moderator to broadcast a message to all breakout rooms
2. Fix webinar mode url issue
3. Make anonymous user names unique

**Comment by gjaekel** [comment]
Great! Will have a look on the patch and test it out soon, if there's already a build.

**Comment by deleolajide** [comment]
Not ready for 0.9.11 yet, but updated https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v0.9.10-snapshot
