### ISSUE TITLE
Enhancement: Publish WebPush disposition more often to speed-up population of the Contact Manager

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#49]
At the moment, the disposition to handle the WebPush feature seems to be posted just once at joining the room. This seems to be distributed by a broadcast message to the room and will reach all members already "in" at this moment. If this new participant is unkown to the others, it is added to the contact manager.

From this, all later-joining participants will never get contact information of all the participants already in but just for the next-later-joiners. This will slow down the population of the Contact Manager, obviously

To avoid this I propose to "fire" the information more often, e.g. at some regularly interval and/or at leaving a room. 

The same effect may be reached if all participants will post their own information targeted to the new person as a callback to the announced of joining the room of that new person.

**Comment by deleolajide** [comment]
> To avoid this I propose to "fire" the information more often, e.g. at some regularly interval and/or at leaving a room

The information is sent to all new joiners and existing participants. The issue is that they don't start listening until after they give permissions and consequently miss it. I shall modify it to start listening as soon as they are connected.

**Comment by gjaekel** [comment]
With my fellow Anke I arranged to meet for the following tests. She as well as I were using the same Chrome browser. Both, we have used our meeting plattform several times before, had have the webpush worker enabled a longer time and pre-populated Contact Mangers. But by chance we never meet each other before in a room and, therefore, don't have an entry for the other.
1. First, I joined a room and she come up second. The result was that I got "her" entry, but she don't get mine. 
1. She leave and rejoin. She still get no entry.
1. We leave both and join in the other way around. With this, she got "my" entry.

**Comment by deleolajide** [comment]
> 3\. We leave both and join in the other way around. With this, she got "my" entry.

That confirms that room joiners are missing the broadcasts for existing room occupants

**Comment by deleolajide** [comment]
Thank you for the issue report. A new build is available for testing at https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v0.9.11-snapshot

**Comment by gjaekel** [comment]
Thank *you* for the fix and providing a new snapshot. It's already installed and will be used even tomorrow in an system update event and in a heavy way on next Monday.
