### ISSUE TITLE
Allow to specify hosts entries in config.js with full domain

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#5]
Allow host entries procduced by the `ConfigServlet` to have a domain other than the XMPP Domain.

Please refer to `https://github.com/igniterealtime/openfire-ofmeet-plugin/pull/78`

**Comment by deleolajide** [comment]
I can't accept this PR. The XMPP domain needs to be maintained within Openfire. Changing it outside of Openfire will cause support issues. We have to find a better solution to whatever the problem is
