### ISSUE TITLE
Use getDisplayMedia to obtain a single MediaStream for recording

### ISSUE THREAD

**Issue by deleolajide** [igniterealtime/openfire-pade-plugin#54]
Using getDisplayMedia to obtain a single MediaStream object of the browser tab for jitsi-meet instead of all the remote media streams. See https://github.com/jitsi/jitsi-meet/issues/6014

**Comment by deleolajide** [comment]
This is now implemented as a new toolbar icon that uses getDisplayMedia to record a desktop monitor screen or application window or browser tab with system audio mixed with the user microphone audio. This includes the browser tab where Openfire Mettings is rendered making it an alternative method for recording the meeting into a single webm file.

![image](https://user-images.githubusercontent.com/110731/84764368-83085180-afc5-11ea-941d-0f16e3ec9817.png)

The user has to find and select the exact screen, application or browser tab to record.

![image](https://user-images.githubusercontent.com/110731/84764404-95828b00-afc5-11ea-9131-394e51d14957.png)

**Comment by gjaekel** [comment]
+1!
