### ISSUE TITLE
Enhancement: Show real session time

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#55]
The time display showing the ongoing session time is based on the moment in time a member join to a meeting, i.e. everybody will see another time.

If possible to get from the XMPP server, show a session time based on the creation of the room. IMHO, this information is much more useful for each participant.

**Comment by deleolajide** [comment]
> everybody will see another time.

The timer is for the client-side recording of the conference. It has to reflect the time from the perspective of the person recording the meeting,

> If possible to get from the XMPP server, show a session time based on the creation of the room

Openfire meetings tend to use persistent MUC rooms with tighter security.  If it is a distraction, disable meeting recording

**Comment by gjaekel** [comment]
> The timer is for the client-side recording of the conference. It has to reflect the time from the perspective of the person recording the meeting, If it is a distraction, disable meeting recording

Well, I understand.
