### ISSUE TITLE
Bug: Item state of room locking not propagated

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#56]
The Icon for room locking by password changes with the locking state (open/closed lock).

For other participants, the state of this icon is initialized right on joining. But a state change is not propagated to the other members, .i.e. if on set/clear the password during a session, this change is not reflected by the icon for others.

This might be a bug to be fixed by upstream.

**Comment by deleolajide** [comment]
>This might be a bug to be fixed by upstream.

I agree
