### ISSUE TITLE
Workaround: Prevent disruption of long-muted audio channel

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#58]
If the audio channel is muted for a longer period of about 10min, the audio connection gets lost. One may unmute from within the UI, but no audio data is not transported anymore.

A workaround for users is to re-select the audio input device via the menu at the mic icon. This will open a new "audio track" even if one select the same source as before.

I'll suggest a patch with a workaround: On a 5min interval, if the audio channel is muted, it will be toggled twice. I expect this activity will prevent the drop of the connection. I'll give feedback about this after some days of testing in production.

**Comment by deleolajide** [comment]
Thank you for the issue and PR. If you add "fix #nnn" in the first line of the PR commit description, GitHub will auto-close the issue when it is merged.

**Comment by deleolajide** [comment]
Updated https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v0.9.12-snapshot

**Comment by gjaekel** [comment]
Sorry, there's a serious typo in the patch: I refactored the interval to a constant but left out a factor thousand.

**Comment by gjaekel** [comment]
Today I did two checks by participating muted for 15min on two meetings and was successfully un-muting after this period -- "works for me"™ :)

I'll get additional feedback from others in a few days.

**Comment by gjaekel** [comment]
I just found that you rised the time between unmuting and remuting of the audio channel to 1000ms. But I had proposed 1ms with the intention to switch as fast as possible at the client to keep privacy of a muted participant as good as possible.
