### ISSUE TITLE
No way to change RANDOM_AVATAR_URL_SUFFIX?

### ISSUE THREAD

**Issue by ayushbhat** [igniterealtime/openfire-pade-plugin#68]
Is there any way to edit interface_config.js, particularly the RANDOM_AVATAR_URL_SUFFIX property in that file?

I tired to edit config_custom.js file directly and added the following line, but no help.

![Screenshot_2](https://user-images.githubusercontent.com/10598279/90333431-5aabcc00-dfe3-11ea-9ebb-e77992474d04.png)

**Comment by deleolajide** [comment]
Try adding openfire system property - org.jitsi.videobridge.ofmeet.random.avatar.url.prefix

![image](https://user-images.githubusercontent.com/110731/90333673-b9f7e500-dfbf-11ea-881d-86518c74e094.png)

See https://github.com/igniterealtime/openfire-pade-plugin/blob/9685d012186c21ddff8e866487efa03a4a7ced1e/web/src/main/java/org/jivesoftware/openfire/plugin/ofmeet/InterfaceConfigServlet.java#L79

**Comment by ayushbhat** [comment]
Thanks for quick reply, it worked! But the random avatar doesn't seem to be set.
Is this feature implemented yet?

**Comment by deleolajide** [comment]
Looks like it is broken in Jitsi Meet.
See https://community.jitsi.org/t/how-can-i-use-avatars-from-libreavatar-org-or-my-self-hosted-instance-of-it-instead-of-gravatar/21012/3

**Comment by ayushbhat** [comment]
I'm sorry if I'm asking too much, is there any dirty fix to achieve this random avatar feature just through the plugin?

**Comment by deleolajide** [comment]
> I'm sorry if I'm asking too much, is there any dirty fix to achieve this random avatar feature just through the plugin?

I am trying to reduce the about of hacking I make to Jitsi code, but I am happy to make this change

**Comment by deleolajide** [comment]
Confirmed it works with the Openfire random avatar plugin

![image](https://user-images.githubusercontent.com/110731/90345246-120e0600-e017-11ea-8672-c972f935f781.png)

and updated https://github.com/igniterealtime/openfire-pade-plugin/releases/tag/v1.0.0-snapshot

**Comment by ayushbhat** [comment]
Thanks Sir!
