### ISSUE TITLE
Using a fully custom UI instead of Jitsi-meet.

### ISSUE THREAD

**Issue by ayushbhat** [igniterealtime/openfire-pade-plugin#69]
Can you suggest how could a totally different UI can be use with this plugin instead of Jitsi-meet UI.
Also is there a way to hide lib-jitsi-meet from out code especially when someone does an inspect element on the browsers.

**Comment by deleolajide** [comment]
This issue should be posted at https://github.com/jitsi/lib-jitsi-meet/issues
