### ISSUE TITLE
Cannot see ofmeet/jitsi-meet code in Chrome developer tools / webpack

### ISSUE THREAD

**Issue by rcampion** [igniterealtime/openfire-pade-plugin#7]
I am building pade from source.  0.9.8

When I use Chrome developer tools, I cannot see the code in webpack for ofmeet.

**Comment by rcampion** [comment]
I see the problem I was having.

You are overriding the app.bundle.min.js and lib-jitsi-meet,min.js files in jitsi-meet/libs with those in web/src/main/webapp/libs.

If I rename the web/src/main/webapp/libs directory to something like web/src/main/webapp/libs-orig then the jitsi-meet files will not be overridden as to preserve those generated in in jitsi-meet make.

Now I can see the code.

**Comment by deleolajide** [comment]
Please note that I am completely re-factoring all that code and moving jitsi-meet out of pade. See issue https://github.com/igniterealtime/pade/issues/220

**Comment by rcampion** [comment]
Thanks for the heads-up.

And thank you for your work.  Ofmeet is great!
