### ISSUE TITLE
Active directory authentication

### ISSUE THREAD

**Issue by grego1981** [igniterealtime/openfire-pade-plugin#73]
Hi and thank you for the plugins! Awsome work!
I have managed to connect the plugin but when I start a meeting I get authentication failure when trying to create or join a meeting. I use AD authentication and I'm having trouble on how to configure openfire to accept the authentication for the Jitsi meetings. 

I see the section: "ofmeet and offocus plugins will not work out of the box if your Openfire server is configured to use LDAP 34. You would need to create the Jitsi focus bot user and give it owner/admin permissions to the MUC service manually." I feel that this is where my problem lies but I do not know how to configure since I'm not able to create a local user. (AD & all)

Please help to consolidate settings so as to be able to use it completely!

Thank you!

**Comment by deleolajide** [comment]
> I do not know how to configure since I'm not able to create a local user. (AD & all)

Thanks for the kind words :-) You have 2 options

1. You can either create the **focus** user in AD or
2. Use the Openfire hybrid authentication provider to combine local users with AD users for authentication

see http://yuangh.blogspot.com/2010/10/openfire-mysql-active-directory-english.html

**Comment by grego1981** [comment]
Thank you for youir prompt answer!
I have created an AD user and I'm trying to find how to add the user as an MCU admin....

**Comment by grego1981** [comment]
can you also tell me where can I find the plugin's logs?

**Comment by deleolajide** [comment]
![image](https://user-images.githubusercontent.com/110731/96127167-3a699200-0eec-11eb-99d3-aefc41d753a8.png)

**Comment by deleolajide** [comment]
> can you also tell me where can I find the plugin's logs?

plugin does not have separate log files. it uses openfire logs

![image](https://user-images.githubusercontent.com/110731/96127926-8b798600-0eec-11eb-990c-4118b59f643a.png)

**Comment by grego1981** [comment]
Thank you again! The service conference did not exist, in fact no service was present. I created the service and added the user, but when I try to start a video chat (jitsi) still I get the error below....
![image](https://user-images.githubusercontent.com/9021998/96130577-cbe2ff00-0f00-11eb-960a-b270539148e2.png)

**Comment by grego1981** [comment]
It now works! I disabled the option  Windows NTLM Authentication enabled which was enabled, I do not remember if it was enabled by default.
