### ISSUE TITLE
Invite participants from within jitsi

### ISSUE THREAD

**Issue by grego1981** [igniterealtime/openfire-pade-plugin#74]
Is it possible to add participants to an ongoing jitsi meeting selectable from the user list?

**Comment by deleolajide** [comment]
There 2 methods to do this

![image](https://user-images.githubusercontent.com/110731/96243728-0bf7bf80-0f9d-11eb-8d72-36bddac0f0be.png)
There is no select-able list. You have to use the email client select-able list
and

![image](https://user-images.githubusercontent.com/110731/96243933-52e5b500-0f9d-11eb-8748-e44991daebaa.png)
This uses the history of meeting participants who agree to accept notifications.

![image](https://user-images.githubusercontent.com/110731/96245028-c6d48d00-0f9e-11eb-9523-0efdcd9132ff.png)

**Comment by grego1981** [comment]
Thank you! I think it would be very helpful to have the ability to view the list of users to select, also to be able to select the users prior to starting the meeting!

**Comment by deleolajide** [comment]
Use the settings page to access Search. Use the directory to find users and copy and past into an invitation list

![image](https://user-images.githubusercontent.com/110731/96256472-a57c9c80-0fb0-11eb-842a-525346011399.png)

Then use the invitation list from meetings to either join an existing meeting or use invite to start a new meeting and invite all the participants

![image](https://user-images.githubusercontent.com/110731/96256270-40c14200-0fb0-11eb-89b3-1f972939ed94.png)
