### ISSUE TITLE
MUC Domain on Meetings->Summary Tab is Incorrect if multiple Group Chat Services Exist

### ISSUE THREAD

**Issue by droobah** [igniterealtime/openfire-pade-plugin#78]
I have two Group Chat services named chat and conference respectively.

The chat service is for group chats only, the conference is for ofmeet/webmeetings only. 

When viewing the Summary tab in Meetings, the MUC Room link goes to that chat service and not the conference one.  I see in the jsp for that page, it just picks the first MUC service and uses that as the domain. 

Can we make that configurable via a system property?

**Comment by deleolajide** [comment]
> Can we make that configurable via a system property?

Good idea 👍

**Comment by deleolajide** [comment]
> I see in the jsp for that page, it just picks the first MUC service and uses that as the domain.

Try to fix this and cant find this in the code. can you please paste the permalink to code like this:
https://github.com/igniterealtime/openfire-pade-plugin/blob/10451361cf9d37a830ba2eb4ea19e2b03214c76b/ofmeet/src/web/ofmeet-summary.jsp#L96

**Comment by droobah** [comment]
Here is the line in question.  If it could be hardcoded to conference like the rest of the Jitsi videobridge, I believe it would solve my issue.

https://github.com/igniterealtime/openfire-pade-plugin/blob/10451361cf9d37a830ba2eb4ea19e2b03214c76b/ofmeet/src/web/ofmeet-summary.jsp#L32

**Comment by deleolajide** [comment]
There is already a system property called **ofmeet.main.muc** that defaults to *conference* being used for that purpose at https://github.com/igniterealtime/openfire-pade-plugin/blob/10451361cf9d37a830ba2eb4ea19e2b03214c76b/ofmeet/src/java/org/jivesoftware/openfire/plugin/ofmeet/LobbyMuc.java#L36

We can use that 👍
