### ISSUE TITLE
Feature Request: screen sharing and webcam

### ISSUE THREAD

**Issue by akbarazimifar** [igniterealtime/openfire-pade-plugin#79]
Hello.
I request that the screen sharing and the provider's webcam be displayed at the same time
This means that when the provider shares their screen and is talking at the same time, their webcam will be displayed.
Thanks

**Comment by gjaekel** [comment]
Hello,
this is already implemented! But it is a somewhat hidden feature and I miss it a whole while, too: Enter screen sharing, and after this, just **re-enable** the video by the Icon or pressing the [v] key.

**Comment by akbarazimifar** [comment]
Thank
It is true  .
But with this method, the user has to login twice. In addition, another user will be added to the list of participants.
My other suggestion is that when the user asks permission, the admin should allow the applicant to speak at the conference.
Now the user can participate whenever he wants, just turn on his microphone, then start talking.

**Comment by deleolajide** [comment]
> Enter screen sharing, and after this, just **re-enable** the video by the Icon or pressing the [v] key.

![image](https://user-images.githubusercontent.com/110731/97860839-bd675680-1cfa-11eb-8f33-759205605e74.png)

I prefer this method

**Comment by deleolajide** [comment]
>My other suggestion is that when the user asks permission, the admin should allow the applicant to speak at the conference.

Privacy laws do not allow anyone to stop another person from speaking. You can mute everyone or anyone as a moderator, but you can't stop them from un-muting themselves. Just like real-life, you can force them to leave or ban them or expect them to behave in a civil manner.

**Comment by gjaekel** [comment]
> I prefer this method

Me, too. Since I discovered it ;)
