### ISSUE TITLE
openfire/ofmeet  Make Room Members only

### ISSUE THREAD

**Issue by rcampion** [igniterealtime/openfire-pade-plugin#8]
In Openfire 5.4.1 / ofmeet 0.9.8

For a given service and Group Chat Room Settings.

If I check the Room Option/Make Room Members-only,  I do not get prompted for a user login.

I only get prompted for a login if I disable anonymous logins server wide.

Instead I get a Connection failed for the ofmeet room.

**Comment by deleolajide** [comment]
You can't be prompted for a password when you have allowed anonymous access connections. If you want to have members-only group-chat, then you have to force authentication for all users.
