### ISSUE TITLE
Feature Request: Allow customizing of the confetti tool

### ISSUE THREAD

**Issue by gjaekel** [igniterealtime/openfire-pade-plugin#82]
I just got the user request to prepare a "Xmas edition" of the confetti tool.

It seems to me that the upstream project recently work on this with the similar "haloween" intention (https://github.com/catdad/canvas-confetti/pull/111). Therefore, maybe we just have to update the lib and add an global setting for the used "shape" array.

Then -- like the old tradition of easter eggs -- this global may be easy redefinded or even changed by current date.

**Comment by deleolajide** [comment]
> Therefore, maybe we just have to update the lib and add an global setting for the used "shape" array.

That sounds like a very good plan to me 👍

**Comment by gjaekel** [comment]
V1.1.3 will become the Santa Clause edition :)

![confetti xmas-edition](https://user-images.githubusercontent.com/19855721/101258195-39512600-3721-11eb-9285-ddb54c422e4c.png)
