### ISSUE TITLE
focus user

### ISSUE THREAD

**Issue by Triskele69** [igniterealtime/openfire-pade-plugin#9]
Hello, is there a way to add an ability to change "focus" user username?
I am using LDAP integration and for known reasons i can't create exactly "focus" user within my domain.

**Comment by wrooot** [comment]
What are those known reasons?

**Comment by Triskele69** [comment]
Cannot have user "focus" within my domain because of very strict naming rules.

**Comment by deleolajide** [comment]
This has come up in the past. Unfortunately, focus name is hard-coded in some parts of Jitsi code. Openfire does allow non-LDAP users to be added to the user directory, but it is tricky to setup. See https://discourse.igniterealtime.org/t/hybrid-auth-local-ldap-is-supported/61589

You might be able to use it to add focus as a local non_LDAP user.
